import Head from "next/head";
import Link from "next/link";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row, Form } from "react-bootstrap";
import Axios from "axios";
import Image from "next/image";
import styles from "./styles.module.scss";
import AuthContext from "../../store/auth-context";
import Upload from "../Inputs/Upload/Upload";

export const config = {
  api: {
    bodyParser: false,
  },
};
export default function UploadVerification() {
  const [verified, setVerified] = useState(false);
  const authCtx = useContext(AuthContext);

  const handleUploadFiles = async (event) => {
    // for (let i = 0; i < event.target.files.length; i++) {
    //   const formData = new FormData();

    //   if (event.target.files && event.target.files[i]) {
    //     const ih = event.target.files[i];
    //     formData.append("file", ih);
    //     formData.append("token", authCtx.Token());
    //   }

    //   const route = "/api/case/upload-file";
    //   try {
    //     const rese = await Axios.post(route, formData, {
    //       headers: {
    //         "Content-Type": "multipart/form-data",
    //       },
    //     })
    //       .then((res) => {
    //         console.log(res);
    //       })
    //       .catch((error) => {
    //         alert(error);
    //       });
    //   } catch (err) {
    //     alert("Something went wrong!" + err);
    //   }
    // }
    setVerified(true);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - Verification</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconn.ico" />
      </Head>
      <main className={styles.aboutPage}>
        <Container>
          <h3>ID Verification</h3>
          {!verified ? (
            <Form onSubmit={handleUploadFiles}>
              <input type="file" multiple />

              <Button type="submit" className="mx-auto">
                Upload Files
              </Button>
            </Form>
          ) : (
            <div>Uploaded!</div>
          )}
        </Container>
      </main>
    </div>
  );
}
