import React from "react";
import EndAdornment from "../../components/Inputs/components/EndAdornment";
import Head from "next/head";
import { CheckCircleFill } from "react-bootstrap-icons";
import { Col, Container, Row } from "react-bootstrap";
import styles from "./Test.styles.module.scss";
import Image from "next/image";

import fdaImageSrc from "../../public/assets/test/fda-approved.png";
import LandingSection from "./sections/LandingSection";
import ListSection from "./sections/ListSection";
import OrderSection from "./sections/OrderSection";

const mockData = [
  {
    label: "Value 1",
    value: "value1",
    endAdornment: (
      <EndAdornment text="Most popular" variant="chip" color="orange" />
    ),
  },
  {
    label: "Value 2",
    value: "value2",
    endAdornment: (
      <EndAdornment text="Best quality" variant="chip" color="green" />
    ),
  },
  {
    label: "Value 3",
    value: "value3",
  },
  {
    label: "Value 4",
    value: "value4",
    endAdornment: (
      <EndAdornment text="Most popular" variant="chip" color="orange" />
    ),
  },
  {
    label: "Value 5",
    value: "value5",
    endAdornment: (
      <EndAdornment text="Best quality" variant="chip" color="green" />
    ),
  },
  //   {
  //     label: "Value 6",
  //     value: "value6",
  //   },
  //   {
  //     label: "Value 7",
  //     value: "value7",
  //     endAdornment: (
  //       <EndAdornment text="Most popular" variant="chip" color="orange" />
  //     ),
  //   },
  //   {
  //     label: "Value 8",
  //     value: "value8",
  //     endAdornment: (
  //       <EndAdornment text="Best quality" variant="chip" color="green" />
  //     ),
  //   },
  //   {
  //     label: "Value 9",
  //     value: "value9",
  //   },
];

const Test = () => {
  return (
    <div>
      <Head>
        <title>Pure Blue - Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingSection />
        <ListSection />
        <OrderSection />
      </main>
    </div>
  );
};

export default Test;
