import Head from "next/head";
import { useContext, useState, React, useEffect } from "react";

import { Col, Container, Button, Row } from "react-bootstrap";
import Nav from "react-bootstrap/Nav";
import styles from "./styles.module.scss";
import Orders from "../../components/Orders";
import Membership from "../../components/Membership";
import Profile from "../../components/Profile";
import Case from "../../components/Case";
import Verification from "../../components/Verification";
import AuthContext from "../../store/auth-context";
import Axios from "axios";
export default function Account(props) {
  const [content, setContent] = useState(<div></div>);
  const authCtx = useContext(AuthContext);

  const getCase = async () => {
    const route = "/api/case/get-case";

    try {
      const rese = await Axios.post(route, { Token: authCtx.Token() })
        .then((res) => {
          console.log(res.data.data);
          //setCaseAnswers(res.data.data);
        })
        .catch((error) => {
          props.handleShow(error.response.data);
        });
    } catch (err) {
      props.handleShow(err);
    }
  };

  useEffect(() => {
    getCase();
  }, []);

  // useEffect(() => {
  //   handleSelect("Membership");
  // }, []);

  const handleSelect = (link) => {
    if (link === "Membership") {
      setContent(
        <div>
          <Case handleShow={props.handleShow} />
        </div>
      );
    } else if (link === "Orders") {
      setContent(<Orders handleShow={props.handleShow} />);
    } else if (link === "Profile") {
      setContent(<Profile handleShow={props.handleShow} />);
    }
    // else if (link === "Case") {
    //   setContent(<Case handleShow={props.handleShow} />);
    // }
    else if (link === "IdVerification") {
      setContent(<Verification handleShow={props.handleShow} />);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconn.ico" />
      </Head>
      <main className={styles.accountPage}>
        <Container>
          <Nav
            variant="tabs"
            className={styles.navbar}
            defaultActiveKey="Membership"
            onSelect={handleSelect}
          >
            <Nav.Item>
              <Nav.Link eventKey="Membership">Membership</Nav.Link>
            </Nav.Item>
            <Nav.Item>
              <Nav.Link eventKey="Orders">Orders</Nav.Link>
            </Nav.Item>
            <Nav.Item>
              <Nav.Link eventKey="Profile">Profile</Nav.Link>
            </Nav.Item>
            {/* <Nav.Item>
              <Nav.Link eventKey="Case">Case</Nav.Link>
            </Nav.Item> */}
            <Nav.Item>
              <Nav.Link eventKey="IdVerification">ID Verification</Nav.Link>
            </Nav.Item>
          </Nav>
          <br />
          <br />
          {content}
        </Container>
      </main>
    </div>
  );
}
