import Head from "next/head";
import { Link } from "next/link";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row } from "react-bootstrap";
import Accordion from "react-bootstrap/Accordion";
import Image from "next/image";
import styles from "./styles.module.scss";
import { Check, PatchCheck } from "react-bootstrap-icons";
import { Card, Table } from "react-bootstrap";
import { useAccordionButton } from "react-bootstrap/AccordionButton";
import { AccordionContext, Form } from "react-bootstrap";
export default function Privacy() {
  function ContextAwareToggle({ children, eventKey, callback }) {
    const { activeEventKey } = useContext(AccordionContext);
    const decoratedOnClick = useAccordionButton(
      eventKey,
      () => callback && callback(eventKey)
    );

    const isCurrentEventKey = activeEventKey === eventKey;

    return (
      <button
        type="button"
        className="headerOne"
        style={{
          backgroundColor: isCurrentEventKey ? "#fff" : "#fff",
          border: "0px",
          color: "#000",
          fontWeight: "800",
          padding: "0px 12px 0px 12px",
          width: "100%",
          textAlign: "left",
        }}
        onClick={decoratedOnClick}
      >
        {children}
      </button>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - Privacy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.privacyPage}>
        <Container className={styles.container}>
          <h1>Privacy Policy</h1>
          <p className={styles.blueText}>INTRODUCTION</p>
          <p>
            This Privacy Policy (“Privacy Policy”) describes the types of
            information we may collect from you or that you may provide to
            PureBlue LLC and its affiliates, (collectively, “PureBlue,” “we,”
            “our,” or “us”), and our data protection practices for collecting,
            using, maintaining, protecting and disclosing such information when
            you visit any PureBlue website that links to this Privacy Policy
            (including pureblue.com (collectively, our “Website”), use any
            affiliated mobile applications (the “Apps”), or otherwise provide
            data to PureBlue. We refer to the Website, Apps, and other services
            provided by PureBlue together in this Privacy Policy as the
            “Services.” This Privacy Policy is incorporated into our Terms of
            Use. All capitalized terms used in this Privacy Policy but not
            defined herein have the meanings assigned to them in the Terms of
            Use.
            <br />
            <br /> If you are a California resident, please click our Privacy
            Information for California Residents for more information.
            <br />
            <br /> This policy does not apply to information collected by: the
            physician or healthcare provider that we contract with; any third
            party, including through any application or content (including
            advertising) that may link to or be accessible from or on our
            Website.
          </p>
          <p className={styles.grayText}>
            PLEASE READ THIS PRIVACY POLICY CAREFULLY TO UNDERSTAND OUR POLICIES
            AND PRACTICES REGARDING YOUR INFORMATION AND HOW WE HANDLE YOUR
            INFORMATION. IF YOU DO NOT AGREE TO THIS PRIVACY POLICY, PLEASE DO
            NOT USE THE SERVICES.
          </p>
          <div className={styles.numbers}>
            <b className={styles.privacy}>
              This Privacy Policy contains the following sections:
            </b>
            <br />
            <br />
            <p>
              1.{" "}
              <span className={styles.blueText}>
                The Information We Collect and the Sources of Such Information
              </span>
            </p>
            <p>
              2.{" "}
              <span className={styles.blueText}>
                Purposes for How We Use Your Information
              </span>
            </p>
            <p>
              3.
              <span className={styles.blueText}>
                {" "}
                Online Analytics and Advertising
              </span>
            </p>
            <p>
              4.{" "}
              <span className={styles.blueText}>
                How We Share and Disclose Your Information
              </span>
            </p>
            <p>
              5. <span className={styles.blueText}>Your Marketing Choices</span>
            </p>
            <p>
              6.{" "}
              <span className={styles.blueText}>
                Third Party Services and Notice About Health Information
              </span>
            </p>
            <p>
              7.{" "}
              <span className={styles.blueText}>
                How We Protect Your Information
              </span>
            </p>
            <p>
              8.{" "}
              <span className={styles.blueText}>
                Privacy Information for California Residents
              </span>
            </p>
            <p>
              9.{" "}
              <span className={styles.blueText}>
                Privacy Information for Nevada Residents
              </span>
            </p>
            <p>
              10.{" "}
              <span className={styles.blueText}>
                Retention of Your Information
              </span>
            </p>
            <p>
              11.{" "}
              <span className={styles.blueText}>
                Revisions to Our Privacy Policy
              </span>
            </p>
            <p>
              12. <span className={styles.blueText}>Contacting Us</span>
            </p>
          </div>
          <p className={styles.blueText}>
            THE INFORMATION WE COLLECT AND THE SOURCES OF SUCH INFORMATION
          </p>
          <p>
            We obtain information about you through the means discussed below
            when you use the Services. Please note that we require certain types
            of information necessary to offer our Services safely and
            thoroughly. If you do not provide us with such information, or ask
            us to delete it, you may no longer be able to access or use part or
            all of our Services.
          </p>
          <h2>1. Information You Provide to Us</h2>
          <p>
            We collect a variety of information that you provide directly to us.
            For example, we collect information from you through:
          </p>
          <ul>
            <li>
              Registration, administration, or other support provided to your
              account
            </li>
            <li>
              Communicating, processing, reviewing requests and orders regarding
              products or services
            </li>
            <li>
              Any questions, comments, feedback or other communications, you
              provide to us via form email, or other collection mechanism.
            </li>
            <li>Surveys and research</li>
            <li>
              Customer support and technical assistance, including, but not
              limited to, online chat functionalities
            </li>
            <li>Any uploads or posts</li>
            <li>Any applications you submit</li>
          </ul>
          <p>
            The specific types of information we collect will depend upon the
            Services you use, how you use them, and the information you choose
            to provide. The types of data we collect directly from you includes:
            information by which you are personally identified, including your
            name, billing address, telephone numbers, date of birth,
            credit/debit card number (for payment purposes), demographic
            information (gender and age). Additional information we may collect
            directly from you includes your medical history and health
            information (medical conditions, treatment options, physician
            referrals, prescriptions, and lab results or other related health
            information, such as your physical and emotional characteristics).
          </p>
          <ul>
            <li>
              Credentials, including Log-in, once an account is created and
              other permission details
            </li>
            <li>
              Information for Billing, including, but not limited to, shipping
              address, debit or credit card number(s), expiration date, security
              number, and collected by our payment processors, identity
              verification information
            </li>
            <li>Any information related to purchases or other transactions</li>
            <li>
              Any information related to your customer service and maintenance
              interactions
            </li>
            <li>Demographic information, including your gender and age</li>
            <li>Any user-generated content posted to our Services</li>
            <li>
              Any other information you provide us connected to the usage of our
              Services
            </li>
          </ul>
          <br />
          <h2>
            2. Information We Collect Through Automated Data Collection
            Technologies
          </h2>
          <p>
            This section discusses the information we collect about how you use
            our services and the devices you use to access those Services. As
            discussed further below, we and our service providers (which could
            be third party companies that work with us or on our behalf), may
            use a variety of systems or technologies, including analytics,
            cookies, and other tools, to help collect this data.
            <br />
            <br />
            <b>Our Websites.</b> When you navigate through or interact with our
            Websites, we collect and analyze details of your visits to our
            Website which may include but is not limited to: your device
            information (IP address, browser types browser language, operating
            system, the state or country from which you accessed the Services),
            software and hardware attributes (including device IDs) referring
            and exit pages and URLs, platform type, click count, files
            downloaded, domain names, landing pages, pages viewed and of the
            order of the pages, the amount of time spent on particular pages,
            the terms you use in searches on our sites, when and time you used
            in the Services, error logs, and other similar information.
            <br />
            <br />
            <b>Location Information.</b> When you use the Services, we and our
            service providers may automatically collect general location
            information (e.g., IP address, city/state and or postal code
            associated with an IP address) from your computer or mobile device
            to customize the Services, content promotional offers, and related
            information to enhance user experience. This allows us to enable
            access and increased services based on a user’s general location
            information .
            <br />
            <br />
            Before collecting your GPS location information we will ask your
            permission. In such instances, we will use your precise geo-location
            information to provide customized services, content, promotional
            offers and other information that may be of interest to you. If you
            no longer wish for us and our service providers to collect and use
            GPS location information, you may disable the location features on
            your device. Please see your device manufacturer settings.
            <br />
            <br />
            <b>Our Use of Cookies and Similar Online Tools.</b> To collect the
            information discussed in this Section, we and our service providers
            (including Google Analytics, Google Shopping, Google Adwords, Bing
            Ads, Bing Webmaster Tools, and Facebook) use web server logs,
            cookies, tags, SDKs, tracking pixels, and other similar tracking
            technologies. We use these technologies to offer you a more tailored
            experience.
          </p>
          <ul>
            <li>
              A web server log is a file where website activity is stored.
            </li>
            <li>
              An SDK is a set of tools and/or code that we embed in our Apps and
              software to allow third parties to collect information about how
              users interact with the Services.
            </li>
            <li>
              A cookie is a small text file that is placed on your computer or
              mobile device when you visit a site, that enables us to: (i)
              recognize your computer/device; (ii) store your preferences and
              settings; (iii) understand the parts of the Services you have
              visited and used; (iv), enhance your user experience by delivering
              and measuring the effectiveness of content and advertising
              tailored to your interests; (v) perform searches and analytics;
              and (vi) assist with security and administrative functions.
            </li>
            <li>
              Tracking pixels (sometimes referred to as web beacons or clear
              GIFs) are tiny electronic tags with a unique identifier embedded
              in websites, online ads and/or email that are designed to: (1)
              collect usage information like ad impressions or clicks and email
              open rates; (2) measure popularity of the Services and associated
              advertising; and (3) access user cookies.
            </li>
          </ul>
          <br />
          <p>
            If we adopt additional technologies, we might also gather
            information through other channels and methods.
            <br />
            <br /> Please note that you can change your settings to notify you
            when a cookie is being set or updated, or to block cookies
            altogether. Please check the “Help” section of your browser for more
            information (e.g., Apple Safari; Internet Explorer; Mozilla Firefox;
            or Google Chrome). Please note that by blocking, disabling, or
            managing any or all cookies, you may not have access to certain
            features or offerings.
          </p>
          <br />
          <br />
          <h2>
            3. Information We Collect from Social Media and Other Content
            Platforms
          </h2>
          <p>
            We may collect some information from you (including your name, email
            address, and any comments or content you post relevant to us) if you
            engage in certain social medial sites (“liking” or “following” us on
            Facebook, Instagram, Twitter or other social medial sites. We are
            not responsible for the information you share with these social
            media sites and your interactions with and engagements on these
            sites are governed by the privacy policies of the respective sites.
            <br />
            <br /> If you “like” or “follow” us on Facebook, Instagram, Twitter,
            or other social media sites, we may collect some information from
            you including your name, email address, and any comments or content
            you post relevant to us. We also collect your information if you
            sign up for one of our promotions or submit information to us
            through social media sites.
          </p>
          <h2>4. Information We Receive From Other Sources</h2>
          <p>
            Our third parties and intermediaries, such as the physicians,
            medical professionals, and pharmacies with whom we partner to
            provide you with the Services and their health care services,
            sub-contractors in technical, advertising networks, analytics
            providers, and search information providers. These parties will also
            provide us additional information.
          </p>
          <h2>5. Protected Health Information</h2>
          <p>
            When you set up an account with PureBlue, you are creating a direct
            customer relationship with PureBlue that enables you to access
            and/or utilize the various functions of the Site Offerings as a
            user. As part of that relationship, you may provide certain personal
            information to PureBlue that we do not consider to be “protected
            health information” or “medical information,” such as your name,
            email address, mailing/billing address and telephone number.
            <br />
            <br /> However, where you request Prescription Medications or
            otherwise request certain PureBlue Products, you may also provide
            certain health or medical information that may be protected under
            applicable laws, rules and regulations, such the Health Insurance
            Portability and Accountability Act of 1996, Public Law 104-191, and
            its related regulations and amendments (collectively, “HIPAA”).
            PureBlue is not considered a “covered entity” under HIPAA; provided,
            however, that our Healthcare Providers are “covered entities” under
            HIPAA and, in connection therewith, PureBlue may, in some cases, be
            a “business associate” of the Healthcare Providers. It is important
            to note that HIPAA does not necessarily apply to an entity or person
            simply because there is health information involved, and HIPAA may
            not apply to all of your transactions or communications with
            PureBlue. To the extent PureBlue is deemed a “business associate”
            however, and solely in its role as a business associate, PureBlue
            may be subject to certain provisions of HIPAA with respect to
            “protected health information,” as defined under HIPAA, that you
            provide to the Healthcare Providers (“PHI”). In addition, any
            medical or health information that you provide that is subject to
            specific protections under applicable state laws (collectively, with
            PHI, “Protected Information”), will be used and disclosed only in
            accordance with such applicable laws. However, any information that
            does not constitute Protected Information under applicable laws may
            be used or disclosed in any manner permitted under this Privacy
            Policy. Protected Information does not include information that has
            been de-identified in accordance with applicable laws.
          </p>
          <h2>Possible Risks of Telehealth</h2>
          <ul>
            <li>
              Seeing your health care provider outside the typical healthcare
              setting may feel different and you may find it difficult to
              communicate with and give sufficient information to your health
              care provider.
            </li>
            <li>
              Your health care provider may not be able to provide a diagnosis
              or treatment because of the inability to conduct physical tests
              and a close physical examination, which may require an in-person
              visit.
            </li>
            <li>
              The inability to physically examine you may lead to missed signs
              and symptoms that require emergency medical treatment or further
              medical testing. Your health care provider may not able to provide
              medical treatment for your particular condition via telehealth,
              which may require that you seek alternative care.
            </li>
            <li>
              Technological failures may interrupt your tele-visit with your
              health care provider.
            </li>
            <li>
              Technological failures may cause delays in your evaluation and
              treatment by your health care provider.
            </li>
            <li>
              Technological failures may cause distortion of diagnostic images
              or specimens resulting from electronic transmission issues,
              unauthorized access to your information, or loss of information
              due to technology failures. If you are not in a private place
              during your tele-visit and people are close to you, they may hear
              something that you wish to keep private.
            </li>
            <li>
              Given regulatory requirements in certain jurisdictions, especially
              pertaining to certain prescriptions, your health care provider’s
              treatment options may be limited.
            </li>
          </ul>
          <br />
          <br />
          <p className={styles.blueText}>
            PURPOSES FOR HOW WE USE YOUR INFORMATION
          </p>
          <p>
            We use the information that we collect about you or that you provide
            to us for the following purposes:
          </p>
          <ul>
            <li>For the purposes for which you provided the information;</li>
            <li>
              To contact you when necessary (verify your identity and
              administration of your account, such as payment processing and
              order fulfillment) or if requested (your inquiries related to the
              Services, technical assistance, and customer service);
            </li>
            <li>Help us better cater our Services to our user base;</li>
            <li>
              To provide, maintain, administer, improve, or expand the Services,
              perform business analyses, or for other internal purposes to
              support, improve, or enhance our business, the Services, and other
              products we offer
            </li>
          </ul>
          <p>While providing services, we may use your information to:</p>
          <ul>
            <li>
              Administer, improve, and support the all of our Services and, as
              applicable, facilitate the provision of health care services to
              you by physicians or other health care providers, and operations,
              including to ensure that the physicians or health care providers
              have the Services and support necessary for health care
              operations.
            </li>
            <li>
              Internally research so we can understand the performance of our
              Services, improve, and provide our users with a better experience.
              If we publish or provide the results of this research, it will be
              presented in a de-identified and aggregated form removing any
              personal identifiable information.
            </li>
            <li>
              Communicate with you about our Services, and send you
              communications on behalf of physicians or other health care
              providers to meet your needs.
            </li>
            <li>
              Communicate via postal mail, email, or phone about surveys,
              special events, promotions, or our products and Services and our
              subsidiaries, affiliates, and parent companies those of our
              third-party partners, and any of their related businesses.
            </li>
            <li>Provide you with customer service and technical support.</li>
            <li>
              Verify your identity and administer your account, including
              processing your payments and fulfilling orders.
            </li>
            <li>
              Ensure that content from our Services is presented in the most
              effective manner for you and for your computer or device, allow
              you to participate in interactive features of our Services (when
              you choose to do so), and as part of our efforts to keep our
              Services safe and secure.
            </li>
            <li>
              Measure or understand the effectiveness of advertising and content
              we serve to you and others, and to deliver and customize relevant
              advertising and content to you.
            </li>
            <li>
              Help us improve your overall interests and needs, such as by
              engaging in researching and analysis pertaining to the use of our
              Services.
            </li>
            <li>
              Comply in good faith with any procedures, laws, and regulations.
            </li>
            <li>
              Establish, exercise, or defend our legal rights. Combined
              Information. We may combine the information we collect through
              Services with information that we receive from other sources, both
              online and offline, and use and share such combined information
              aligned with this Privacy Policy.
            </li>
          </ul>
          <br />
          <br />
          <p className={styles.blueText}>ONLINE ANALYTICS AND ADVERTISING</p>
          <h2>1. Online Analytics</h2>
          <p>
            We may use third-party web analytics services such as those of
            Google Analytics, and Cartstack on our Services to collect and
            analyze usage information through cookies and similar tools; engage
            in auditing, research, or reporting; assist with fraud prevention;
            analyze unique user interaction across multiple browsers or devices
            to better tailor services and features; and provide certain features
            to enhance user experience. If you have a Google account with
            personalized advertising enabled, through Google Signals, we will be
            able to gather and analyze engagement information from across the
            various devices you use to access the Services. To prevent Google
            from using your information for analytics (including cross-device
            tracking for personalization purposes), you may install the Google
            Analytics Opt-out Browser Add-on by clicking here. To opt out of
            Google Signals, open your “Settings” app, locate and click on
            “Google,” select “Ads,” and turn ON “Opt out of Ads
            Personalization.” You may also be able to disable cross-device
            tracking through your Android or Apple device-based settings.
            <br />
            <br /> If you receive an email from us, we may use certain analytics
            tools, such as clear GIFs to capture data such as when you open our
            message or click on any links or banners contained in our email.
            This data allows us to gauge the effectiveness of our communications
            and marketing campaigns.
          </p>
          <h2>2. Online Advertising</h2>
          <p>
            The Services may integrate third-party advertising technologies
            (e.g., ad networks and ad servers such as Facebook, Google Ad Words,
            YouTube, Bing, Criteo and others) that use cookies and other
            technologies to deliver relevant content and advertising for
            PureBlue products on the Services, as well as on other websites you
            visit and other applications you use. The ads may be based on a
            myriad of factors such as the content of the page you are visiting,
            information you enter such as your searches, demographic data, and
            other information we collect from you. There is a change these ads
            will be based on your current activity or your activity over time
            and across other websites and online services.
            <br />
            <br /> We sometimes provide our customer information (such as email
            addresses) to service providers, who may “match” this information in
            de-identified form to cookies (or mobile ad identifiers) and other
            proprietary IDs, in order to provide you with more relevant ads when
            you visit other websites and mobile applications.
            <br />
            <br /> We neither have access to, nor does this Privacy Policy
            govern, the use of cookies or other tracking technologies that may
            be placed on your device you use to access the Services by
            non-affiliated third-party advertising network services. For more
            information on browser advertising and how you can generally control
            cookies from being put on your device to deliver tailored
            advertising, you may visit the Network Advertising Initiative’s
            Consumer Opt-Out link, the Digital Advertising Alliance’s Consumer
            Opt-Out link, or Your Online Choices to opt-out of curtained
            advertising from companies that participate in those programs. If
            you are interested in more information about Criteo’s privacy
            practices or opting-out of Criteo’s advertising services, you may
            view their Privacy Policy. To opt out of Google Analytics for
            display advertising or customize Google display network ads, visit
            the Google Ads Settings page. We cannot control these opt-out links
            or if any particular company chooses to participate in these opt-out
            programs. We are not responsible for any choices you make using
            these mechanisms or the continued availability or accuracy of these
            mechanisms.
            <br />
            <br /> Even if you exercise any of the opt out choices above, you
            will still see advertising when you use the Services, but it will
            not be tailored to you based on your online behavior over time.
          </p>
          <h2>3. Mobile Advertising</h2>
          <p>
            Our mobile applications my deliver tailored in-application
            advertisements to you when they are in use. We may use third-party
            service providers to deliver such advertisements on mobile
            applications or for mobile application analytics. Each operating
            system, iOS for Apple phones, Android for Android devices, and
            Windows for Microsoft devices provides its own instructions on how
            to prevent the delivery of tailored in-application advertisements.
            We cannot control how the applicable platform operator allows you to
            control personalized in-application advertisements. Should you wish
            to opt out of tailored in-application advertisements, you should
            contact the platform provider for further details on how to do so.
            You may review the support materials and/or the device settings for
            the respective operating systems to opt-out of tailored in-app
            advertisements
          </p>
          <h2>4. Notice Concerning Do Not Track</h2>
          <p>
            Certain web browsers have a Do Not Track (“DNT”) a privacy
            preference setting that allows users to limit the web browser’s
            ability to collect information on the user. We are committed to
            providing you with meaningful choices about the information
            collected on our website for third party purposes, which is why we
            provide the opt-out mechanisms listed above. However, we do not
            currently recognize or respond to browser-initiated DNT signals. You
            can learn more about Do Not Track here.
          </p>
          <br />
          <br />
          <p className={styles.blueText}>
            THE INFORMATION WE COLLECT AND THE SOURCES OF SUCH INFORMATION
          </p>
          <p>
            We may share your information for our business purposes in the
            following ways:
          </p>
          <ul>
            <li>
              <b>Affiliates and Subsidiaries.</b> In order to deliver products
              and services to you, ensure a consistent level of service across
              our products and services, and enhance our products, services, and
              your customer experience, we may share information we collect
              within any PureBlue LLC member or group (i.e., our subsidiaries
              and affiliates, including our ultimate holding company and its
              subsidiaries).
            </li>
            <li>
              <b>Health Care Providers and Services.</b> We share your
              information with health care providers for the following purposes:
              (i) to schedule and fulfill appointments and provide health care
              services as part of the Services, (ii) to transmit messages you
              send through our Services to your intended recipients, and (iii)
              for other treatment, payment or health care operations purposes,
              including pharmacy services, upon your request.
            </li>
            <li>
              <b>Service Providers.</b> We provide access to or share your
              information with select third parties who use the information to
              perform services on our behalf. We use third parties for a variety
              of services including billing, sales, marketing, advertising,
              analytics, research, customer service, shipping and fulfillment,
              data storage, IT and security, fraud prevention, payment
              processing, and auditing and legal services. These entities may
              also include health care organizations, pharmacies, and other
              third parties that we use to support our business or in connection
              with the administration and support of the Services.
            </li>
            <li>
              <b>Protection of PureBlue and Others.</b> By using the Services,
              you acknowledge and agree that we may access, retain and disclose
              the information we collect from and maintain about you if required
              to do so by law or in a good faith belief that such access,
              retention or disclosure is reasonably necessary to: (a) enforce
              our Terms of Use, this Privacy Policy, or other contracts with
              you, including investigation of potential violations thereof; (b)
              respond to claims that any content violates the rights of third
              parties; (c) respond to your requests for customer service; and/or
              (e) protect the rights, property or personal safety of PureBlue,
              its agents and affiliates, its users and/or the public (d) comply
              with legal process such as a subpoena or court order. This
              includes exchanging information with other companies and
              organizations for fraud protection, spam/malware prevention, and
              other similar purposes.
            </li>
            <li>
              <b>Business Transfers.</b> As our business develops, we may buy,
              merge, or partner with other companies. In such transactions,
              (including in contemplation of such transactions) we may be
              required to transfer a portion or all of our assets, including
              user information. If a portion or all of our assets are sold or
              transferred to a third-party, customer information (including your
              email address) would likely be one of the transferred business
              assets. If such transfer is subject to additional mandatory
              restrictions under applicable laws, we will comply with such
              restrictions.
            </li>
            <li>
              <b>Public Forums.</b> Certain features of our Services make it
              possible for you to share comments publicly with other users. Any
              information that you submit through such features is not
              confidential, and we may use it for any purpose (including in
              testimonials or other marketing materials). For example, if you
              submit a product review on one of our sites, we may display your
              review (along with the name provided, if any) on other PureBlue
              websites and on third-party websites. Any information you post
              openly in these ways will be available to the public at large and
              potentially accessible through third-party search engines.
              Accordingly, please take care when using these features.
            </li>
            <li>
              <b>Consent.</b> We may also disclose your information in other
              ways you direct us to and when we have your consent.
            </li>
          </ul>
          <br />

          <p className={styles.blueText}>YOUR MARKETING PREFERENCES</p>
          <p>
            If you do not want us to use your contact information to contact you
            by email, postal mail, or phone regarding products, services,
            promotions and special events that might appeal to your interests,
            contact us using the information below. In commercial email
            messages, you can also opt out by following the instructions located
            at the bottom of such emails. For example, you may not opt out of
            certain operational emails, such as those reflecting our
            relationship or transactions with you. Please note that, regardless
            of your request, we may still use and share certain information as
            permitted by this Privacy Policy or as required by applicable law.
          </p>
          <p className={styles.blueText}>
            THIRD PARTY SERVICES AND NOTICE ABOUT HEALTH INFORMATION
          </p>
          <p>
            This Privacy Policy does not address, nor are we responsible for,
            the privacy, information, or other practices, including data privacy
            and security processes and standards of any third parties, including
            physicians and other health care providers using the Services, the
            manufacturer of your mobile device and other IT hardware and
            software, and any other third-party mobile application, website, or
            service to which our Services may contain a link. These third
            parties may at times gather information from or about you. We are
            not responsible for the privacy practices of third-party websites.
            The collection, use, and disclosure of your information will be
            subject to the privacy policies of the third-party websites or
            services. We urge you to read the privacy and security policies of
            these third parties.
          </p>
          <p className={styles.blueText}>HOW WE PROTECT YOUR INFORMATION</p>
          <p>
            PureBlue takes reasonable and responsible steps to ensure your
            information is protected against accidental or unlawful destruction
            or accidental loss, alteration, unauthorized disclosure or access.
            However, no data transmission over the Internet, and no means of
            electronic or physical storage, is ever completely secure. .Thus,
            you acknowledge and accept that you provide your personal
            information at your own risk and we cannot guarantee the security of
            such information transmitted to, through, or on our Services or via
            the Internet. You can help protect your Personal Data and other
            information by keeping your password to our Website confidential.
            Where we have given you (or where you have chosen) a password that
            enables you to access the Services, you are responsible for keeping
            this password confidential.
            <br />
            <br />
            Please do not share your password with anyone. Information shared in
            public areas could be viewed by any user of our Services.
          </p>
          <p className={styles.blueText}>
            PRIVACY INFORMATION FOR CALIFORNIA RESIDENTS
          </p>
          <p>
            In accordance with the California Consumer Privacy Act (“CCPA”), we
            are required to provide you with some additional information on how
            we collect, use and share your personal information. These Privacy
            Provisions supplement and do not in any way limit the Privacy Policy
            set forth above and are only applicable to residents of California.
            <br />
            <br />
            Further, if you are a California resident, the CCPA grants you the
            following rights:
          </p>
          <ul>
            <li>
              The right to opt-out from the sale and sharing of your personal
              information
            </li>
            <li>
              If you would like to opt-out from the disclosure or sale of your
              personal information to any third party for marketing purposes,
              please contact us via email at: info@trypureblue.com or send us
              U.S. Mail to:
              <br />
              PureBlue LLC,
              <br /> 42 Broadway, 12th Floor
              <br /> New York, NY 10004
            </li>
            <li>
              The right to request us to disclose certain information to you
              about our collection and use of your personal information over the
              past twelve (12) months
            </li>
            <li>
              The right to request that we delete any of your personal
              information that we collected from you, unless an exception
              applies.
            </li>
          </ul>
          <p>
            For California residents, California law requires us to provide you
            with additional information pertaining to how we collect, use, and
            share your “personal information” (as defined in the California
            Consumer Privacy Act (“CCPA”)).
            <br />
            <br /> Below is a list of categories of personal information we
            collect and disclose. In this Policy, we discuss the specific
            personal information we collect from and regarding our users. Under
            the CCPA, we are also required to provide you with the “categories”
            of personal information we collect and the categories of third
            parties to which we disclose personal information. Please note that
            certain information collected through the Services (e.g., medical
            information), is subject to various health data privacy laws, and is
            thus not subject to the CCPA. Please review the following chart to
            learn more about the categories of personal information we collect
            that are subject to the CCPA and the third parties to whom we
            disclose:
          </p>
          <Table striped bordered hover className={styles.table}>
            <thead className={styles.tableHead}>
              <tr>
                <th>Category of Personal Information</th>
                <th>Categories of Third Parties to Which we Disclose</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  Commercial and transactional information (e.g., information
                  about your purchases)
                </td>
                <td>
                  Service providers; our affiliates; health care providers and
                  services; entities for legal and fraud prevention
                </td>
              </tr>
              <tr>
                <td>
                  Customer service data (e.g., information you provide through a
                  chat or call with our PureBlue's Customer Service Team)
                </td>
                <td>
                  Service providers; our affiliates; health care providers and
                  services; entities for legal and fraud prevention
                </td>
              </tr>
              <tr>
                <td>
                  Demographic and statistical data (e.g., your gender, interests
                  based on products and services you use)
                </td>
                <td>
                  Service providers; our affiliates; entities for legal and
                  fraud prevention
                </td>
              </tr>
              <tr>
                <td>
                  Financial information (e.g., credit card info collected by our
                  payment processors)
                </td>
                <td>
                  Payment processors; service providers; our affiliates;
                  entities for legal and fraud prevention
                </td>
              </tr>
              <tr>
                <td>
                  Geolocation information (e.g., general location and precise
                  location, with your permission)
                </td>
                <td>
                  Service providers; our affiliates; entities for legal and
                  fraud prevention
                </td>
              </tr>
              <tr>
                <td>
                  Internet or other network or device activity (e.g., IP
                  address, browsing history, app usage)
                </td>
                <td>
                  Service providers; our affiliates; entities for legal and
                  fraud prevention
                </td>
              </tr>
              <tr>
                <td>Physical characteristics (e.g., photos of you)</td>
                <td>Service providers; our affiliates</td>
              </tr>
              <tr>
                <td>Physical characteristics (e.g., photos of you)</td>
                <td>Service providers; our affiliates</td>
              </tr>
              <tr>
                <td>
                  User-generated content (e.g., information you choose to post
                  in our online forums)
                </td>
                <td>
                  Service providers; our affiliates; entities for legal and
                  fraud prevention
                </td>
              </tr>
            </tbody>
          </Table>
          <p>
            The business purposes for which we use the personal information we
            collect are: manage, facilitate, and improve the Services; research,
            marketing, and analytics; communicate with users; technical support
            and customer service; security and fraud prevention; and legal
            compliance and defense. For more information about how we use and
            share your personal information, please see the “Purposes for How We
            Use Your Information” and “How We Share and Disclose Your
            Information” sections of this Policy above.
          </p>
          <p className={styles.blueText}>YOUR CALIFORNIA PRIVACY RIGHTS</p>
          <p>
            CCPA Rights Disclosure. If you are a California resident, the CCPA
            permits you to make certain requests about your personal
            information. In particular, the CCPA allows you to request us to:
          </p>
          <ul>
            <li>
              Inform you about the categories of personal information we collect
              or disclose about you; the categories of sources of such
              information; the business or commercial purpose for collecting
              your personal information; and the categories of third parties
              with whom we share/disclose personal information.
            </li>
            <li>
              Provide access to and/or a copy of certain information we hold
              about you.
            </li>
            <li>Delete certain information we have about you.</li>
          </ul>
          <p>
            The CCPA also gives you the right to opt-out of the sale of your
            personal information. The CCPA further prohibits us from
            discriminating against you for exercising your rights under the law,
            including your right to request access to your personal information,
            to delete information, and to opt out of the sale of your personal
            information. <br />
            <br /> Please note that certain information may be exempt from such
            requests under California law. For example, we need certain
            information in order to provide the Services to you. We also will
            take reasonable steps to verify your identity before responding to a
            request.
            <br />
            <br /> If you are a California resident and you would like to
            exercise any of your data rights under California law, you can email
            us at info@trypureblue.com. Please include your full name, email
            address and residential address associated with your use of our
            Services, along with the rights you would like to exercise, so that
            we can process your request in an efficient manner. If you would
            like to receive a copy of your medical record in connection with
            your request, please indicate that in your email message. By
            requesting your medical record in this way, you are agreeing to
            receive your medical record in an unencrypted email message.
            <br />
            <br /> Sale of Personal Information. PureBlue does not, and will
            not, sell information that identifies you such as your name, email
            address, phone number, or postal address. Like many companies with
            an internet presence, we do work with third parties that provide
            marketing and advertising services to us, including interest-based
            advertising services, and these third parties may place tags,
            pixels, cookies, beacons, and other similar tracking mechanisms on
            our Website and App and collect your online identifiers. Because of
            the CCPA’s broad definitions of “sale” and “personal information,”
            making certain online identifiers available to these companies so
            that they can provide marketing and advertising services to PureBlue
            may be considered a “sale” under the CCPA. To opt out of sharing
            your information with participating third parties for interest-based
            advertising, please visit the Network Advertising Initiative’s
            Consumer Opt-Out link, the Digital Advertising Alliance’s Consumer
            Opt-Out link, and Your Online Choices. Please note that these
            opt-outs are device and browser based, so you will need to opt out
            on each of your devices and browsers. For more information, see the
            Online Analytics and Advertising Section above.
            <br />
            <br />
            <b>Shine the Light Disclosure.</b> The California “Shine the Light”
            law gives residents of California the right under certain
            circumstances to request information from us regarding the manner in
            which we share certain categories of personal information (as
            defined in the Shine the Light law) with third parties for their
            direct marketing purposes. We do not share your personal information
            with third parties for their own direct marketing purposes.
          </p>
          <p className={styles.blueText}>
            PRIVACY INFORMATION FOR NEVADA RESIDENTS
          </p>
          <p>
            Under Nevada law, certain Nevada consumers may opt out of the sale
            (as such terms are defined under Nevada law) of “personally
            identifiable information” to a person who further licenses or sells
            such information to additional persons. We do not engage in such
            activity; however, if you are a Nevada resident who has purchased
            services from us, you may submit a request to opt out of any
            potential future sales under Nevada law by email at
            info@trypureblue.com. Please note that we will take reasonable steps
            to verify your identity and the authenticity of the request. Once
            verified, we will maintain your request in the event our practices
            change.
          </p>
          <p className={styles.blueText}>RETENTION OF YOUR INFORMATION</p>
          <p>
            We keep your information for no longer than is necessary for the
            purposes for which it is processed. The length of time for which we
            retain information is determined by the purposes for which we
            collected and use it and/or compliance requirements of applicable
            laws.
          </p>
          <p className={styles.blueText}>REVISIONS TO OUR PRIVACY POLICY</p>
          <p>
            We reserve the right to change this Privacy Policy and the terms of
            this Notice at any time to comply with any changes in the law,
            update our data collection and use practices, the features of our
            Services, or advances in technology. Any revised Privacy Policy will
            be accessible through the Services Site, please be sure to review it
            periodically. The date this Privacy Policy was last revised is
            identified at the top of the document. You are responsible for
            periodically monitoring and reviewing any updates to the Privacy
            Policy. If we make a material change to the Privacy Policy, we will
            provide you with appropriate notice in accordance with legal
            requirements. Your continued use of our Websites or Apps after such
            amendments (and notice, where applicable) will be deemed your
            acknowledgment of these changes to this Privacy Policy.
          </p>
          <p className={styles.blueText}>CONTACTING US</p>
          <p>
            If you would like to opt-out from the disclosure or sale of your
            personal information to any third party for marketing purposes,
            please contact us via email at: info@trypureblue.com or send us U.S.
            Mail to:
            <br /> PureBlue LLC,
            <br /> 42 Broadway, 12th Floor
            <br /> New York, NY 10004
          </p>
        </Container>
      </main>
    </div>
  );
}
