import Head from "next/head";
import Link from "next/link";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row } from "react-bootstrap";
import Axios from "axios";
import Image from "next/image";
import styles from "./styles.module.scss";
import AuthContext from "../../store/auth-context";
import Upload from "../../components/Inputs/Upload/Upload";

export const config = {
  api: {
    bodyParser: false,
  },
};
export default function Verification() {
  const authCtx = useContext(AuthContext);

  const handleUploadFiles = async (event) => {
    const formData = new FormData();

    if (event.target.files && event.target.files[0]) {
      const i = event.target.files[0];
      formData.append("file", i);
      formData.append("token", authCtx.Token());
    }

    const route = "/api/case/upload-file";
    try {
      const rese = await Axios.post(route, formData, {
        headers: {
          "Content-Type": "multipart/form-data",
        },
      })
        .then((res) => {
          console.log(res);
        })
        .catch((error) => {
          alert(error);
        });
    } catch (err) {
      alert("Something went wrong!" + err);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - Verification</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconn.ico" />
      </Head>
      <main className={styles.aboutPage}>
        <Container>
          <input type="file" onChange={handleUploadFiles} />
        </Container>
      </main>
    </div>
  );
}
