import Head from "next/head";
import Link from "next/link";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row } from "react-bootstrap";
import Accordion from "react-bootstrap/Accordion";
import Image from "next/image";
import styles from "./styles.module.scss";
import { Check, PatchCheck } from "react-bootstrap-icons";
import { Card } from "react-bootstrap";
import { useAccordionButton } from "react-bootstrap/AccordionButton";
import ButtonGroup from "react-bootstrap/ButtonGroup";
import ToggleButton from "react-bootstrap/ToggleButton";
import { AccordionContext, Form } from "react-bootstrap";
export default function Home() {
  const [checked, setChecked] = useState(false);
  const [radioValue, setRadioValue] = useState("1");

  const medication = [
    { name: "Sildenafil (generic Viagra)", value: "1" },
    { name: "Viagra", value: "2" },
    { name: "Tadalafil (generic Cialis)", value: "3" },
    { name: "Cialis", value: "4" },
  ];

  const strong = [
    { name: "Begginer", value: "begginer" },
    { name: "Intermediate", value: "intermediate" },
    { name: "Strong", value: "strong" },
  ];

  const times = [
    { name: "4 TIMES", value: "4" },
    { name: "8 TIMES", value: "8" },
    { name: "12 TIMES", value: "12" },
  ];

  function ContextAwareToggle({ children, eventKey, callback }) {
    const { activeEventKey } = useContext(AccordionContext);
    const decoratedOnClick = useAccordionButton(
      eventKey,
      () => callback && callback(eventKey)
    );

    const isCurrentEventKey = activeEventKey === eventKey;

    return (
      <button
        type="button"
        className="headerOne"
        style={{
          backgroundColor: isCurrentEventKey ? "#fff" : "#fff",
          border: "0px",
          color: "#000",
          fontWeight: "800",
          padding: "0px 12px 0px 12px",
          width: "100%",
          textAlign: "left",
        }}
        onClick={decoratedOnClick}
      >
        {children}
      </button>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - Switch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.registerPage}>
        <Container>
          <div className={styles.fieldOne}>
            <Row>
              <Col md={6}>
                <div className={styles.formField}>
                  <Form>
                    <Form.Group as={Col} controlId="formGridSexualActivity">
                      <Form.Label>
                        First decide your preferred medication, select one:
                      </Form.Label>
                      {medication.map((radio, idx) => (
                        <Col md={6}>
                          <ToggleButton
                            key={idx}
                            id={`radio-${idx}`}
                            type="radio"
                            name="radio"
                            className={styles.buttons}
                            value={radio.value}
                            checked={radioValue === radio.value}
                            onChange={(e) =>
                              setRadioValue(e.currentTarget.value)
                            }
                          >
                            {radio.name}
                          </ToggleButton>
                        </Col>
                      ))}
                    </Form.Group>
                    <Form.Group as={Col} controlId="formGridSexualActivity">
                      <Form.Label>
                        How strong per serving you think you need, select one:
                      </Form.Label>
                      {strong.map((radio, idx) => (
                        <Col md={6}>
                          <ToggleButton
                            key={idx}
                            id={`radio-${idx}`}
                            type="radio"
                            name="radio"
                            className={styles.buttons}
                            value={radio.value}
                            checked={radioValue === radio.value}
                            onChange={(e) =>
                              setRadioValue(e.currentTarget.value)
                            }
                          >
                            {radio.name}
                          </ToggleButton>
                        </Col>
                      ))}
                    </Form.Group>

                    <Form.Group as={Col} controlId="formGridSexualActivity">
                      <Form.Label>
                        How many times you believe you will take the medication
                        each month, select one:
                      </Form.Label>
                      <Row>
                        {times.map((radio, idx) => (
                          <Col md={4}>
                            <ToggleButton
                              key={idx}
                              id={`radio-${idx}`}
                              type="radio"
                              name="radio"
                              className={styles.buttons}
                              value={radio.value}
                              checked={radioValue === radio.value}
                              onChange={(e) =>
                                setRadioValue(e.currentTarget.value)
                              }
                            >
                              {radio.name}
                            </ToggleButton>
                          </Col>
                        ))}
                      </Row>
                    </Form.Group>
                  </Form>
                </div>
              </Col>
              <Col md={6}>
                <div className={styles.whitePart}>
                  <h2>YOUR PRICE BASED ON ANSWERS</h2>
                  <h3>
                    You chose Sildenafil at "Intermediate" level 4 times a month
                  </h3>
                  <h1>$24</h1>
                  <p>Change your answers to discover more pricing options.</p>
                  <Button>BACK TO CHECKOUT</Button>
                </div>
              </Col>
            </Row>
          </div>
        </Container>
      </main>
    </div>
  );
}
