import Head from "next/head";
import React, { useEffect, useState, useContext } from "react";
import { Col, Container, Row, Image, Accordion, AccordionBody, AccordionHeader, AccordionItem } from "react-bootstrap";
import styles from "./Semaglutide.styles.module.scss";
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';

const Semaglutide = (props) => {
  return (
      <>
          <Head>
              <title>Pure Blue - Semaglutide</title>
              <meta name="description" content="Generated by create next app"/>
              <link rel="icon" href="/faviconn.ico"/>
          </Head>

          <div className={`${styles['banner']}`}>
              <div className={`${styles['banner-top']} w-100 d-block`}>
                  <Container className={styles['container']}>
                      <h1>Get prescription <span>weight loss</span><br/>medication online</h1>
                      <div className={`${styles['banner-btn']} w-100 d-block horizontal-center`}><a href="#" className={`w-100 d-block text-center fw-semibold`}>Get Started</a></div>
                      <div className={`${styles['banner-box-row']} w-100 d-block horizontal-center`}>
                          <Row className={`row-flex row-flex-wrap gx-2`}>
                              <Col lg={4}>
                                  <div className={`${styles['banner-box']} w-100 d-block`}>
                                      <div
                                          className={`${styles['banner-box-data']} w-100 d-flex flex-wrap align-items-center`}>
                                          <div className={`${styles['banner-box-left']}`}></div>
                                          <p>See if you qualify for Semaglutide. See safety info below</p>
                                      </div>
                                  </div>
                              </Col>
                              <Col lg={4}>
                                  <div className={`${styles['banner-box']} w-100 d-block`}>
                                      <div className={`${styles['banner-box-data']} w-100 d-flex flex-wrap align-items-center`}>
                                          <div className={`${styles['banner-box-left']} ${styles['icon-2']}`}></div>
                                          <p>Lose 20% body weight on average with Semaglutide*</p>
                                      </div>
                                  </div>
                              </Col>
                              <Col lg={4}>
                                  <div className={`${styles['banner-box']} w-100 d-block`}>
                                      <div className={`${styles['banner-box-data']} w-100 d-flex flex-wrap align-items-center`}>
                                          <div className={`${styles['banner-box-left']} ${styles['icon-3']}`}></div>
                                          <p>Access our insurance concierge to help with<br/>cost</p>
                                      </div>
                                  </div>
                              </Col>
                          </Row>
                      </div>
                  </Container>
              </div>
              <div className={`${styles['banner-bottom']} w-100 d-block`}>
                  <Container className={styles['container']}>
                      <Image
                          src="/assets/semaglutide/semaglutide-injection.png"
                          className={`img-fluid d-block m-auto`}
                      />
                  </Container>
              </div>
          </div>

          <div className={`w-100 d-block ${styles['middle']} middle`}>
              <div className={`${styles['middle-top']} w-100 d-block`}>
                  <Container className={styles['container']}>
                      <div className={`${styles['data-img']} w-100 d-block`}>
                          <Image
                              src="/assets/semaglutide/middle-img.png"
                              className={`w-100`}
                          />
                      </div>
                      <div className={`${styles['box-row']} w-100 d-block horizontal-center`}>
                          <Row className={`row-flex row-flex-wrap gx-2`}>
                              <Col md={4}>
                                  <div className={`${styles['data-box-wrp']} w-100`}>
                                      <div className={`${styles['data-box']} horizontal-center`}>
                                          <div className={`${styles['box-icon']}`}>
                                              <Image
                                                  src="/assets/semaglutide/icon-1.png"
                                                  className={`img-fluid d-block m-auto`}
                                              />
                                          </div>
                                          <p>On-demand provider coaching and support</p>
                                      </div>
                                  </div>
                              </Col>
                              <Col md={4}>
                                  <div className={`${styles['data-box-wrp']} w-100`}>
                                      <div className={`${styles['data-box']} horizontal-center`}>
                                          <div className={`${styles['box-icon']}`}>
                                              <Image
                                                  src="/assets/semaglutide/icon-2.png"
                                                  className={`img-fluid d-block m-auto`}
                                              />
                                          </div>
                                          <p>Improves the way your body responds to sugars</p>
                                      </div>
                                  </div>
                              </Col>
                              <Col md={4}>
                                  <div className={`${styles['data-box-wrp']} ${styles['no-border']} w-100`}>
                                      <div className={`${styles['data-box']} horizontal-center`}>
                                          <div className={`${styles['box-icon']}`}>
                                              <Image
                                                  src="/assets/semaglutide/icon-3.png"
                                                  className={`img-fluid d-block m-auto`}
                                              />
                                          </div>
                                          <p>Helps you feel full<br/>faster, longer</p>
                                      </div>
                                  </div>
                              </Col>
                          </Row>
                      </div>
                      <div className={`${styles['info-text']} w-100 d-block horizontal-center text-center`}><strong>Safety info:</strong> GLP-1 medications may have serious side effects, including possible thyroid tumors. Do not use if you or your family have a history of a type of thyroid cancer called MTC or MEN 2. See more serious warnings &amp; safety info here.</div>
                  </Container>
              </div>
              <div className={`${styles['calc-section']} w-100 d-block`}>
                  <Container className={styles['container']}>
                      <div className={`d-flex flex-wrap justify-content-between align-items-end`}>
                          <div className={`${styles['calc-left']} w-100 d-block`}>
                              <div className={`${styles['calc-left-top']} w-100 d-block text-center`}>20%</div>
                              <div className={`${styles['calc-left-bottom']} w-100 d-block`}>
                                  <div className={`${styles['image-row']}`}>
                                      <Image
                                          src="/assets/semaglutide/semaglutide-injection.png"
                                          className={`img-fluid`}
                                      />
                                  </div>
                                  <div className={`${styles['left-text']} w-100 d-block text-center`}>On average, people on Semaglutide lose 15-20% of their weight in a year*.</div>
                              </div>
                          </div>
                          <div className={`${styles['calc-right']} w-100 d-block`}>
                              <div className={`${styles['calc-right-top']} w-100 d-block`}>
                                  <div className={`${styles['title-row-1']} w-100 d-block fw-medium`}>Select your<br/>Current weight
                                      <div className={`fw-bold bold-text ${styles['bold-text']}`}><output>180</output> <span>lbs</span></div>
                                  </div>
                                  <div className={`${styles['range-slider-row']} w-100 d-block`}>
                                      <input type="range" name="weightSlider" min="100" max="300" value="180" onInput="showVal(this.value)" id="weightField" />
                                  </div>
                                  <div className={`${styles['title-row-1']} w-100 d-block fw-medium`}>Weight you<br/>could lose (lbs):
                                      <div className={`fw-bold ${styles['bold-text']} bold-text`} id="amount">28 lbs</div>
                                  </div>
                              </div>
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                  incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                                  exercitation ullamco laboris nisi ut aliquip ex ea tte6nh commodo consequat. Duis aute
                                  irure dolor in eteyyyou reprehenderit in voluptate velit esse cillum dolore euoip
                                  fugiat nulla pariatur. e dolor in reprehenderit in teteye pivoluptate velit esse
                                  cillum dolore eu fugiat nulla jtu ry pariatur.</p>
                          </div>
                      </div>
                  </Container>
              </div>
              <div className={`${styles['revolutionary-section']} revolutionary-section w-100 d-block`}>
                  <Container className={styles['container']}>
                      <Tabs defaultActiveKey="meds" className={`justify-content-center`}>
                          <Tab eventKey="meds" title="Meds">
                              <div className={`${styles['tab-data']} w-100 d-block`}>
                                  <Row>
                                      <Col md={6}>
                                          <h3>Revolutionary weight<br/>
                                              loss medications</h3>
                                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                                              tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                                              veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
                                              ea tte6nh commodo consequat. Duis aute irure dolor in eteyyyou
                                              reprehenderit in voluptate velit esse cillum dolore euoip fugiat nulla
                                              pariatur. e dolor in reprehenderit in teteye pivoluptate velit esse
                                              cillum dolore eu fugiat nulla jtu ry pariatur.</p>
                                      </Col>
                                      <Col md={6}>
                                          <div className={`${styles['product-box']} w-100 d-block`}>
                                              <div className={`${styles['title']} w-100 d-block fw-semibold`}>Semaglutide</div>
                                              <div className={`${styles['product-img']} w-100 d-block`}><img src="/assets/semaglutide/product-img.png" alt="" className={`img-fluid d-block m-auto`} /></div>
                                              <div className="btn-row w-100 d-flex flex-wrap">
                                                  <a href="#" className="black-btn fw-semibold text-center">Get Started</a>
                                                  <a href="#" className="blue-btn fw-semibold text-center">Learn More</a>
                                              </div>
                                              <div className="backend-link w-100 d-block"><a href="#">Important safety information</a></div>
                                          </div>
                                      </Col>
                                  </Row>
                              </div>
                          </Tab>

                          <Tab eventKey="how-it-works" title="How it works">
                              <div className={`${styles['tab-data']} w-100 d-block`}>
                                  <Row>
                                      <Col md={6}>
                                          <h3>Revolutionary weight<br/>
                                              loss medications</h3>
                                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                                              tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                                              veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
                                              ea tte6nh commodo consequat. Duis aute irure dolor in eteyyyou
                                              reprehenderit in voluptate velit esse cillum dolore euoip fugiat nulla
                                              pariatur. e dolor in reprehenderit in teteye pivoluptate velit esse
                                              cillum dolore eu fugiat nulla jtu ry pariatur.</p>
                                      </Col>
                                      <Col md={6}>
                                          <div className={`${styles['product-box']} w-100 d-block`}>
                                              <div className={`${styles['title']} w-100 d-block fw-semibold`}>Semaglutide</div>
                                              <div className={`${styles['product-img']} w-100 d-block`}><img src="/assets/semaglutide/product-img.png" alt="" className={`img-fluid d-block m-auto`} /></div>
                                              <div className="btn-row w-100 d-flex flex-wrap">
                                                  <a href="#" className="black-btn fw-semibold text-center">Get Started</a>
                                                  <a href="#" className="blue-btn fw-semibold text-center">Learn More</a>
                                              </div>
                                              <div className="backend-link w-100 d-block"><a href="#">Important safety information</a></div>
                                          </div>
                                      </Col>
                                  </Row>
                              </div>
                          </Tab>

                          <Tab eventKey="pricing" title="Pricing">
                              <div className={`${styles['tab-data']} w-100 d-block`}>
                                  <Row>
                                      <Col md={6}>
                                          <h3>Revolutionary weight<br/>
                                              loss medications</h3>
                                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                                              tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                                              veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
                                              ea tte6nh commodo consequat. Duis aute irure dolor in eteyyyou
                                              reprehenderit in voluptate velit esse cillum dolore euoip fugiat nulla
                                              pariatur. e dolor in reprehenderit in teteye pivoluptate velit esse
                                              cillum dolore eu fugiat nulla jtu ry pariatur.</p>
                                      </Col>
                                      <Col md={6}>
                                          <div className={`${styles['product-box']} w-100 d-block`}>
                                              <div className={`${styles['title']} w-100 d-block fw-semibold`}>Semaglutide</div>
                                              <div className={`${styles['product-img']} w-100 d-block`}><img src="/assets/semaglutide/product-img.png" alt="" className={`img-fluid d-block m-auto`} /></div>
                                              <div className="btn-row w-100 d-flex flex-wrap">
                                                  <a href="#" className="black-btn fw-semibold text-center">Get Started</a>
                                                  <a href="#" className="blue-btn fw-semibold text-center">Learn More</a>
                                              </div>
                                              <div className="backend-link w-100 d-block"><a href="#">Important safety information</a></div>
                                          </div>
                                      </Col>
                                  </Row>
                              </div>
                          </Tab>

                          <Tab eventKey="safety" title="Safety">
                              <div className={`${styles['tab-data']} w-100 d-block`}>
                                  <Row>
                                      <Col md={6}>
                                          <h3>Revolutionary weight<br/>
                                              loss medications</h3>
                                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                                              tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                                              veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
                                              ea tte6nh commodo consequat. Duis aute irure dolor in eteyyyou
                                              reprehenderit in voluptate velit esse cillum dolore euoip fugiat nulla
                                              pariatur. e dolor in reprehenderit in teteye pivoluptate velit esse
                                              cillum dolore eu fugiat nulla jtu ry pariatur.</p>
                                      </Col>
                                      <Col md={6}>
                                          <div className={`${styles['product-box']} w-100 d-block`}>
                                              <div className={`${styles['title']} w-100 d-block fw-semibold`}>Semaglutide</div>
                                              <div className={`${styles['product-img']} w-100 d-block`}><img src="/assets/semaglutide/product-img.png" alt="" className={`img-fluid d-block m-auto`} /></div>
                                              <div className="btn-row w-100 d-flex flex-wrap">
                                                  <a href="#" className="black-btn fw-semibold text-center">Get Started</a>
                                                  <a href="#" className="blue-btn fw-semibold text-center">Learn More</a>
                                              </div>
                                              <div className="backend-link w-100 d-block"><a href="#">Important safety information</a></div>
                                          </div>
                                      </Col>
                                  </Row>
                              </div>
                          </Tab>
                      </Tabs>
                  </Container>
              </div>
              <div className={`${styles['how-section']} w-100 d-block`}>
                  <div className={`${styles['how-section-top']} w-100 d-block`}></div>
                  <div className={`${styles['how-section-bottom']} w-10 d-block`}>
                      <Container className={styles['container']}>
                          <div className={`${styles['data-row']} w-100 d-block`}>
                              <h3>How PureBlue helps you lose weight</h3>
                              <p>If you don’t use insurance, it typically takes 4-6 weeks to start medication, including
                                  completing your lab test. If you’d like to use your insurance, it can take an
                                  additional 2-3 weeks to try to get coverage. But don’t worry, we’ll handle all the
                                  paperwork.</p>
                              <div className={`${styles['small-title']} w-100 d-block fw-semibold`}>Getting
                                  started <span>$99</span>
                              </div>
                              <div className={`${styles['acco-data-row']} w-100 d-block`}>
                                  <Accordion defaultActiveKey="0">
                                      <AccordionItem eventKey="0" className={styles['accordion-item']}>
                                          <AccordionHeader className={styles['accordion-button']}>Answer health questions and complete your online visit</AccordionHeader>
                                          <AccordionBody className={styles['accordion-body']}>
                                              <p><strong>This is the first item's accordion body.</strong> It is shown
                                                  by default, until the collapse plugin adds the appropriate classes
                                                  that we use to style each element. These classes control the overall
                                                  appearance, as well as the showing and hiding via CSS transitions. You
                                                  can modify any of this with custom CSS or overriding our default
                                                  variables. It's also worth noting that just about any HTML can go
                                                  within the <code>.accordion-body</code>, though the transition does
                                                  limit overflow.</p>
                                          </AccordionBody>
                                      </AccordionItem>

                                      <AccordionItem eventKey="1" className={styles['accordion-item']}>
                                          <AccordionHeader className={styles['accordion-button']}>Take a lab test </AccordionHeader>
                                          <AccordionBody className={styles['accordion-body']}>
                                              <p><strong>This is the second item's accordion body.</strong> It is hidden
                                                  by default, until the collapse plugin adds the appropriate classes
                                                  that we use to style each element. These classes control the overall
                                                  appearance, as well as the showing and hiding via CSS transitions. You
                                                  can modify any of this with custom CSS or overriding our default
                                                  variables. It's also worth noting that just about any HTML can go
                                                  within the <code>.accordion-body</code>, though the transition does
                                                  limit overflow.</p>
                                          </AccordionBody>
                                      </AccordionItem>

                                      <AccordionItem eventKey="2" className={styles['accordion-item']}>
                                          <AccordionHeader className={styles['accordion-button']}>Provider writes an Rx (if appropriate)</AccordionHeader>
                                          <AccordionBody className={styles['accordion-body']}>
                                              <p><strong>This is the third item's accordion body.</strong> It is hidden
                                                  by default, until the collapse plugin adds the appropriate classes
                                                  that we use to style each element. These classes control the overall
                                                  appearance, as well as the showing and hiding via CSS transitions. You
                                                  can modify any of this with custom CSS or overriding our default
                                                  variables. It's also worth noting that just about any HTML can go
                                                  within the <code>.accordion-body</code>, though the transition does
                                                  limit overflow. </p>
                                          </AccordionBody>
                                      </AccordionItem>

                                      <AccordionItem eventKey="3" className={styles['accordion-item']}>
                                          <AccordionHeader className={styles['accordion-button']}>Try to get insurance coverage</AccordionHeader>
                                          <AccordionBody className={styles['accordion-body']}>
                                              <p><strong>This is the third item's accordion body.</strong> It is hidden
                                                  by default, until the collapse plugin adds the appropriate classes
                                                  that we use to style each element. These classes control the overall
                                                  appearance, as well as the showing and hiding via CSS transitions. You
                                                  can modify any of this with custom CSS or overriding our default
                                                  variables. It's also worth noting that just about any HTML can go
                                                  within the <code>.accordion-body</code>, though the transition does
                                                  limit overflow. </p>
                                          </AccordionBody>
                                      </AccordionItem>
                                  </Accordion>
                              </div>
                              <div className={`${styles['btn-row']} btn-row w-100 d-flex flex-wrap`}>
                                  <a href="#" className={`${styles['black-btn']} black-btn fw-semibold text-center`}>Get Medication</a>
                                  <a href="#" className={`${styles['blue-btn']} blue-btn fw-semibold text-center`}>Ongoing Support</a>
                              </div>
                          </div>
                      </Container>
                  </div>
              </div>
              <div className={`${styles['result-section']} w-100 d-block`}>
                  <Container className={styles['container']}>
                      <Row className={`${styles['row']} align-items-center`}>
                          <Col md={6} lg={7}>
                              <div className={`${styles['title']} w-100 d-block fw-semibold`}>Jake lost <span>30 lbs</span><br/>
                                  in 1 year
                              </div>
                              <p>“I started losing weight almost immediately.<br/>To me, truly, this has been a game-changer.”</p>
                          </Col>
                          <Col md={6} lg={5}>
                              <Image
                                  src="/assets/semaglutide/result-img.png"
                                  className={`w-100`}
                              />
                          </Col>
                      </Row>
                  </Container>
              </div>
              <div className={`${styles['included-section']} w-100 d-block`}>
                  <Container className={styles['container']}>
                      <Row className={styles['row']}>
                          <Col md={6}>
                              <h3>What’s <span>included</span></h3>
                              <div className={`${styles['pen-img']} w-100 d-block`}>
                                  <Image
                                      src="/assets/semaglutide/semaglutide-injection.png"
                                      className={`img-fluid`}
                                  />
                              </div>
                          </Col>
                          <Col md={6}>
                              <div className={`${styles['included-bullet']} w-100 d-block`}>
                                  <ul>
                                      <li>Provider consultation</li>
                                      <li>GLP-1 prescription (if appropriate)</li>
                                      <li>Insurance concierge</li>
                                      <li>Ongoing care &amp; support</li>
                                      <li>Tools to track progress</li>
                                  </ul>
                              </div>
                              <div className={`${styles['btn-row']} btn-row w-100 d-flex flex-wrap`}>
                                  <a href="#" className={`${styles['black-btn']} black-btn fw-semibold text-center w-100`}>Get Started</a>
                                  <a href="#" className={`${styles['blue-btn']} blue-btn fw-semibold text-center w-100`}>Learn More</a>
                              </div>
                              <div className={`${styles['small-text']} w-100 d-block`}>Please note: The cost of medication is not included in the Body Program.</div>
                          </Col>
                      </Row>
                  </Container>
              </div>
              <div className={`${styles['gray-box-row']} w-100 d-block`}>
                  <Container className={styles['container']}>
                      <Row className={`gx-4`}>
                          <Col md={4}>
                              <div className={`${styles['box-img']} w-100 d-block`}>
                                  <Image
                                      src="/assets/semaglutide/box-img-1.jpg"
                                      className={`img-fluid`}
                                  />
                              </div>
                              <div className={`${styles['box-caption']} w-100 d-block fw-semibold text-center`}>Which Semaglutide is<br/>right for you?</div>
                          </Col>
                          <Col md={4}>
                              <div className={`${styles['box-img']} w-100 d-block`}>
                                  <Image
                                      src="/assets/semaglutide/box-img-2.jpg"
                                      className={`img-fluid`}
                                  />
                              </div>
                              <div className={`${styles['box-caption']} w-100 d-block fw-semibold text-center`}>Is using medication to lose<br/>weight cheating?</div>
                          </Col>
                          <Col md={4}>
                              <div className={`${styles['box-img']} w-100 d-block`}>
                                  <Image
                                      src="/assets/semaglutide/box-img-3.jpg"
                                      className={`img-fluid`}
                                  />
                              </div>
                              <div className={`${styles['box-caption']} w-100 d-block fw-semibold text-center`}>Learn more about potential<br/>side effects</div>
                          </Col>
                      </Row>
                  </Container>
              </div>
              <div className={`${styles['faq-section']} w-100 d-block`}>
                  <Container className={styles['container']}>
                      <div className={`${styles['faq-container']}`}>
                          <h3>Weight loss <span>FAQs</span></h3>
                          <div className={`${styles['acco-data-row']} w-100 d-block`}>
                              <Accordion defaultActiveKey="0">
                                  <AccordionItem eventKey="0" className={styles['accordion-item']}>
                                      <AccordionHeader className={styles['accordion-button']}>How much does the Body Program cost?</AccordionHeader>
                                      <AccordionBody className={styles['accordion-body']}>
                                          <p><strong>This is the first item's accordion body.</strong> It is shown by
                                              default, until the collapse plugin adds the appropriate classes that we
                                              use to style each element. These classes control the overall appearance,
                                              as well as the showing and hiding via CSS transitions. You can modify any
                                              of this with custom CSS or overriding our default variables. It's also
                                              worth noting that just about any HTML can go within
                                              the <code>.accordion-body</code>, though the transition does limit
                                              overflow.</p>
                                      </AccordionBody>
                                  </AccordionItem>

                                  <AccordionItem eventKey="1" className={styles['accordion-item']}>
                                      <AccordionHeader className={styles['accordion-button']}>Do you accept insurance?</AccordionHeader>
                                      <AccordionBody className={styles['accordion-body']}>
                                          <p><strong>This is the second item's accordion body.</strong> It is hidden by
                                              default, until the collapse plugin adds the appropriate classes that we
                                              use to style each element. These classes control the overall appearance,
                                              as well as the showing and hiding via CSS transitions. You can modify any
                                              of this with custom CSS or overriding our default variables. It's also
                                              worth noting that just about any HTML can go within
                                              the <code>.accordion-body</code>, though the transition does limit
                                              overflow.</p>
                                      </AccordionBody>
                                  </AccordionItem>

                                  <AccordionItem eventKey="2" className={styles['accordion-item']}>
                                      <AccordionHeader className={styles['accordion-button']}>How much will metabolic testing cost?</AccordionHeader>
                                      <AccordionBody className={styles['accordion-body']}>
                                          <p><strong>This is the third item's accordion body.</strong> It is hidden by
                                              default, until the collapse plugin adds the appropriate classes that we
                                              use to style each element. These classes control the overall appearance,
                                              as well as the showing and hiding via CSS transitions. You can modify any
                                              of this with custom CSS or overriding our default variables. It's also
                                              worth noting that just about any HTML can go within
                                              the <code>.accordion-body</code>, though the transition does limit
                                              overflow. </p>
                                      </AccordionBody>
                                  </AccordionItem>

                                  <AccordionItem eventKey="3" className={styles['accordion-item']}>
                                      <AccordionHeader className={styles['accordion-button']}>What if my insurance doesn’t cover the medication?</AccordionHeader>
                                      <AccordionBody className={styles['accordion-body']}>
                                          <p><strong>This is the third item's accordion body.</strong> It is hidden by
                                              default, until the collapse plugin adds the appropriate classes that we
                                              use to style each element. These classes control the overall appearance,
                                              as well as the showing and hiding via CSS transitions. You can modify any
                                              of this with custom CSS or overriding our default variables. It's also
                                              worth noting that just about any HTML can go within
                                              the <code>.accordion-body</code>, though the transition does limit
                                              overflow. </p>
                                      </AccordionBody>
                                  </AccordionItem>

                                  <AccordionItem eventKey="4" className={styles['accordion-item']}>
                                      <AccordionHeader className={styles['accordion-button']}>What can I expect after I sign up? </AccordionHeader>
                                      <AccordionBody className={styles['accordion-body']}>
                                          <p><strong>This is the third item's accordion body.</strong> It is hidden by
                                              default, until the collapse plugin adds the appropriate classes that we
                                              use to style each element. These classes control the overall appearance,
                                              as well as the showing and hiding via CSS transitions. You can modify any
                                              of this with custom CSS or overriding our default variables. It's also
                                              worth noting that just about any HTML can go within
                                              the <code>.accordion-body</code>, though the transition does limit
                                              overflow. </p>
                                      </AccordionBody>
                                  </AccordionItem>
                              </Accordion>
                          </div>
                      </div>
                  </Container>
              </div>
          </div>
      </>
  );
};

export default Semaglutide;
