import Head from "next/head";
import { Link } from "next/link";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row } from "react-bootstrap";
import Accordion from "react-bootstrap/Accordion";
import Image from "next/image";
import styles from "./styles.module.scss";
import { Check, PatchCheck } from "react-bootstrap-icons";
import { Card } from "react-bootstrap";
import { useAccordionButton } from "react-bootstrap/AccordionButton";
import { AccordionContext, Form } from "react-bootstrap";
export default function Faq() {
  function ContextAwareToggle({ children, eventKey, callback }) {
    const { activeEventKey } = useContext(AccordionContext);
    const decoratedOnClick = useAccordionButton(
      eventKey,
      () => callback && callback(eventKey)
    );

    const isCurrentEventKey = activeEventKey === eventKey;

    return (
      <button
        type="button"
        className="headerOne"
        style={{
          backgroundColor: isCurrentEventKey ? "#fff" : "#fff",
          border: "0px",
          color: "#000",
          fontWeight: "800",
          padding: "0px 12px 0px 12px",
          width: "100%",
          textAlign: "left",
        }}
        onClick={decoratedOnClick}
      >
        {children}
      </button>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - Faq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.faqPage}>
        <Container>
          <h2>Frequently Asked Questions</h2>
          <h3>About PureBlue</h3>
          <div className={styles.expand}>
            <Accordion defaultActiveKey="0">
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="0">
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        What is PureBlue?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="0">
                  <Card.Body>
                    PureBlue is a digital telehealth company that services men
                    who need a direct, more convenient and affordable way to
                    procure erectile dysfunction medication legally with a
                    doctor’s approval. PureBlue provides a complete
                    infrastructure that provides potential patients with
                    convenient options that do not require an in-person doctor’s
                    visit but maintain the supervision of licensed US physicians
                    for the prescription of erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="1">
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Who is PureBlue for?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="1">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="2">
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Do I need a prescription to get PureBlue pills?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="2">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="3">
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Can I get a prescription with PureBlue?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="3">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="4">
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        What makes PureBlue unique?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="4">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="5">
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Is sharing my medical history required to get PureBlue
                        Pills?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="5">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="6">
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Can I use my PureBlue prescription at any pharmacy I
                        choose?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="6">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="7">
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Can I get PureBlue in any state?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="7">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="8">
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Are PureBlue pills FDA approved?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="8">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="9">
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Are PureBlue physicians licensed?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="9">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="10"
                  >
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Is my personal information safe?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="10">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <h3>About Erectile Dysfunction</h3>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="11"
                  >
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Is ED normal?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="11">
                  <Card.Body>
                    ED is one of the most common problems that men in the United
                    States face. About 40%* of American men experience ED, and
                    PureBlue provides a direct, convenient and affordable way
                    for men to experience stronger erections without the risk of
                    taking low-quality ED pills produced overseas.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="12"
                  >
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Can young men get erectile dysfunction?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="12">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="13"
                  >
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        What is the difference between Sildenafil and Tadalafil?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="13">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="14"
                  >
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Are generic branded ED pills as effective as branded ED
                        pills?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="14">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="15"
                  >
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        What can I do if my purchased PureBlue erectile
                        dysfunction pills did not work for me?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="15">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="16"
                  >
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        Does PureBlue have a return & refund policy?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="16">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="17"
                  >
                    <Row>
                      <Col xs={1} md={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={11} md={11}>
                        How much do erectile dysfunction pills cost?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="17">
                  <Card.Body>
                    PureBlue is an online outfit that links potential patients
                    who need a more convenient way to procure erectile
                    dysfunction medication legally with a doctor’s approval.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintains the
                    supervision of medical doctors for the prescription of
                    erectile dysfunction medication.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
            </Accordion>
          </div>
        </Container>
      </main>
    </div>
  );
}
