import Head from "next/head";
import Link from "next/link";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row } from "react-bootstrap";
import Accordion from "react-bootstrap/Accordion";
import Image from "next/image";
import styles from "./styles.module.scss";
import { Check, PatchCheck } from "react-bootstrap-icons";
import { Card } from "react-bootstrap";
import { useAccordionButton } from "react-bootstrap/AccordionButton";
import { AccordionContext, Form } from "react-bootstrap";
export default function Faq() {
  function ContextAwareToggle({ children, eventKey, callback }) {
    const { activeEventKey } = useContext(AccordionContext);
    const decoratedOnClick = useAccordionButton(
      eventKey,
      () => callback && callback(eventKey)
    );

    const isCurrentEventKey = activeEventKey === eventKey;

    return (
      <button
        type="button"
        className="headerOne"
        style={{
          backgroundColor: isCurrentEventKey ? "#fff" : "#fff",
          border: "0px",
          color: "#000",
          fontWeight: "800",
          padding: "0px 12px 0px 12px",
          width: "100%",
          textAlign: "left",
        }}
        onClick={decoratedOnClick}
      >
        {children}
      </button>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - Faq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconn.ico" />
      </Head>
      <main className={styles.faqPage}>
        <Container>
          <h2>Frequently Asked Questions</h2>

          <div className={styles.expand}>
            <h4>About PureBlue</h4>
            <Accordion defaultActiveKey="0">
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="1">
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        What is PureBlue?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="1">
                  <Card.Body>
                    PureBlue is a digital telehealth company that connects men
                    who may be suffering from ED with healthcare providers in a
                    more convenient and affordable way as opposed to
                    conventional and uncomfortable in-person doctor visits.
                    PureBlue provides a complete infrastructure that provides
                    potential patients with convenient options that do not
                    require an in-person doctor’s visit, but maintain the
                    supervision of licensed US physicians through telehealth
                    services.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="2">
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Who is PureBlue for?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="2">
                  <Card.Body>
                    PureBlue is for men who want an easy, convenient, and
                    affordable way to access quality healthcare online, from the
                    comfort of their own home.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="3">
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Can I get a prescription with PureBlue?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="3">
                  <Card.Body>
                    PureBlue connects customers with US-licensed physicians to
                    address their health needs. If medication is required, your
                    assigned healthcare provider will issue a prescription that
                    will be fulfilled by a pharmacy within Pure Blue’s network.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="4">
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Are PureBlue physicians licensed?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="4">
                  <Card.Body>
                    Yes. All physicians within the PureBlue network are licensed
                    in the US and are legally permitted to practice medicine and
                    asynchronous telehealth in states that allow asynchronous
                    telehealth.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="5">
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Is my personal information safe?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="5">
                  <Card.Body>
                    Yes. PureBlue adheres to the strict guidelines and
                    regulations that protect patient health information
                    according to the Healthcare Insurance Portability and
                    Affordability Act of 1996 (HIPAA).
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="6">
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Is PureBlue available in South Carolina?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="6">
                  <Card.Body>
                    No. PureBlue is not available in South Carolina
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="7">
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Why is TryPureBlue not available in South Carolina?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="7">
                  <Card.Body>
                    Due to current state laws and regulations, TryPureBlue is
                    not able to operate in South Carolina at this time.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="8">
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Will TryPureBlue be available in South Carolina in the
                        future?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="8">
                  <Card.Body>
                    We are always evaluating opportunities to expand our
                    services to more states. However, at this time, we cannot
                    confirm when or if TryPureBlue will be available in South
                    Carolina.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle className={styles.headerOne} eventKey="9">
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Can I still access TryPureBlue if I am traveling to a
                        different state?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="9">
                  <Card.Body>
                    Yes, if you are traveling to a state where TryPureBlue is
                    available, you can access our services as long as you have a
                    reliable internet connection and a device with a web
                    browser. Please note that some products and services may not
                    be available in certain states due to state-specific laws
                    and regulations.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="10"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        How can I stay updated on TryPureBlue's availability in
                        South Carolina?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="10">
                  <Card.Body>
                    We recommend regularly checking our website or contacting
                    our customer support team for the latest updates on our
                    products and services and availability in different states.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <h4>About Asynchronous Telehealth</h4>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="11"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        What is Asynchronous Telehealth?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="11">
                  <Card.Body>
                    Asynchronous telehealth in the United States refers to a
                    method of providing medical or healthcare services remotely,
                    where the communication between the healthcare provider and
                    the patient does not occur in real time. Instead, it
                    involves the exchange of medical information, such as
                    images, videos, medical records, or messages, at a time
                    convenient for both the patient and the healthcare provider,
                    without the need for simultaneous interaction. PureBlue
                    offers asynchronous telehealth services to make access to
                    healthcare more convenient and less time-consuming for both
                    the patient and the healthcare provider, leading to lower
                    overall healthcare costs for the patient.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="12"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Is Asynchronous Telehealth allowed in the United States?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="12">
                  <Card.Body>
                    Most states allow asynchronous telehealth in the United
                    States, and state laws involving telehealth services are
                    constantly evolving. Our system is constantly updated to
                    reflect relevant changes in state laws that involve
                    telehealth services.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="13"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Do I need to be in a live video conference during my
                        consultation?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="13">
                  <Card.Body>
                    Our initial health questionnaire will provide sufficient
                    information for your assigned healthcare provider to
                    determine whether or not a synchronous (live) telehealth
                    consultation is necessary. If your assigned healthcare
                    provider requires additional information, you will receive a
                    notification through our system, SMS, and e-mail.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="14"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Are PureBlue telehealth services free?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="14">
                  <Card.Body>
                    PureBlue only gets paid when a patient is prescribed
                    medication after accessing our healthcare network. You are
                    not responsible for the cost of the doctor visit, the cost
                    of the medication, or any insurance fees.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <h4>About Payment Methods</h4>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="15"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Does PureBlue require health insurance?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="15">
                  <Card.Body>
                    No. PureBlue does not require health insurance. We aim to
                    provide convenient and affordable telehealth service for men
                    who need ED consultation.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="16"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Does PureBlue accept health insurance?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="16">
                  <Card.Body>
                    Currently, PureBlue does not accept health insurance.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="17"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        What payment methods does PureBlue accept?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="17">
                  <Card.Body>
                    Credit card is the preferred method of payment.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <h4>About Erectile Dysfunction</h4>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="18"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Is ED normal?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="18">
                  <Card.Body>
                    ED is one of the most common problems that men in the United
                    States face. About 40%* of American men experience ED, and
                    PureBlue provides a direct, convenient, and affordable way
                    for men to experience stronger erections without the risk of
                    taking low-quality ED pills produced overseas.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="19"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Can young men get erectile dysfunction?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="19">
                  <Card.Body>
                    Erectile dysfunction can affect men of all ages. Certain
                    health conditions may bring about symptoms of erectile
                    dysfunction regardless of your age. PureBlue is offered for
                    men over 18 to help deal with symptoms of ED. PureBlue’s
                    affiliated licensed physicians can evaluate your health
                    status and recommend a safe and appropriate treatment plan
                    to help you deal with erectile dysfunction.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="20"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        What is the difference between Sildenafil and Tadalafil?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="20">
                  <Card.Body>
                    Sildenafil and Tadalafil are FDA-approved medications for
                    the treatment of erectile dysfunction. Both medications
                    inhibit the phosphodiesterase-5 enzyme (PDE-5), which
                    results in the dilation of blood vessels in the penile
                    region, which makes erections easier to achieve. The main
                    difference between the two medications is that Sildenafil is
                    recommended to be taken 30-60 minutes before sexual activity
                    and stays in the system for 4 hours, while Tadalafil remains
                    active in the body for 36 hours.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
              <Card className={styles.cardHeader}>
                <Card.Header className={styles.header}>
                  <ContextAwareToggle
                    className={styles.headerOne}
                    eventKey="21"
                  >
                    <Row>
                      <Col xs={2} sm={1} className={styles.plus}>
                        <p>+</p>
                      </Col>
                      <Col className={styles.textPart} xs={10} sm={11}>
                        Are generic branded ED pills as effective as branded ED
                        pills?
                      </Col>
                    </Row>
                  </ContextAwareToggle>
                </Card.Header>
                <Accordion.Collapse eventKey="21">
                  <Card.Body>
                    Both generic-branded and branded (Viagra and Cialis) pills
                    contain the same active component. Viagra contains
                    Sildenafil, while Cialis contains Tadalafil, and all
                    generic-branded erectile dysfunction pills available on
                    PureBlue are consistent with the dosage and effectiveness
                    offered by branded erectile dysfunction pills.
                  </Card.Body>
                </Accordion.Collapse>
              </Card>
            </Accordion>
          </div>
        </Container>
      </main>
    </div>
  );
}
