import Head from "next/head";
import Link from "next/link";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row } from "react-bootstrap";
import Accordion from "react-bootstrap/Accordion";
import Image from "next/image";
import styles from "./styles.module.scss";
import { Check, PatchCheck } from "react-bootstrap-icons";
import { Card } from "react-bootstrap";
import { useAccordionButton } from "react-bootstrap/AccordionButton";
import { AccordionContext, Form } from "react-bootstrap";
export default function Telehealth() {
  function ContextAwareToggle({ children, eventKey, callback }) {
    const { activeEventKey } = useContext(AccordionContext);
    const decoratedOnClick = useAccordionButton(
      eventKey,
      () => callback && callback(eventKey)
    );

    const isCurrentEventKey = activeEventKey === eventKey;

    return (
      <button
        type="button"
        className="headerOne"
        style={{
          backgroundColor: isCurrentEventKey ? "#fff" : "#fff",
          border: "0px",
          color: "#000",
          fontWeight: "800",
          padding: "0px 12px 0px 12px",
          width: "100%",
          textAlign: "left",
        }}
        onClick={decoratedOnClick}
      >
        {children}
      </button>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconn.ico" />
      </Head>
      <main className={styles.aboutPage}>
        <Container className={styles.container}>
          <h1>PureBlue Consent To Telehealth</h1>
          <h2>TERMS OF SERVICE</h2>
          <p>
            AMONG OTHER ACTIVITIES, Pure Blue LLC's SERVICES ENABLE COORDINATION
            AND COMMUNICATION WITH A HEALTH CARE PROVIDER. IT DOES NOT REPLACE
            YOUR RELATIONSHIP WITH ANY PHYSICIAN. THESE SERVICES MIGHT NOT BE
            APPROPRIATE FOR ALL MEDICAL CONDITIONS OR CONCERNS. IF YOU HAVE A
            MEDICAL EMERGENCY, IMMEDIATELY CALL YOUR DOCTOR OR DIAL 911 <br />
            <br /> PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BECAUSE THEY
            SET FORTH THE IMPORTANT TERMS YOU WILL NEED TO KNOW ABOUT THE
            SERVICES.
            <br />
            <br />
            YOU UNDERSTAND THAT BY ACCESSING OR USING THE SITES OR SERVICES, YOU
            ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREED TO BE LEGALLY
            BOUND BY AND COMPLY WITH THESE TERMS OF USE. IF YOU DO NOT OR CANNOT
            AGREE WITH ANY PART OF THESE TERMS OF USE, YOU MAY NOT USE THE SITES
            OR ANY SERVICES PROVIDED ON OR THROUGH THE SITES.
            <br />
            <br /> THE TERMS OF USE ARE SUBJECT TO CHANGE AS PROVIDED HEREIN.
          </p>
          <h2>INTRODUCTION</h2>
          <p>
            Pure Blue LLC (collectively, “PureBlue,” “we”, “us”, or “our”) own
            and operate the websites located at www.TryPureBlue.com. The Sites
            are intended to facilitate the provision of the Services to
            registered users. The “Services” may include (i) providing
            individuals with information on health care and wellness
            (“Content”); (ii) providing individuals with access to
            technology-oriented tools for acne treatment; (iii) development and
            gathering of health care records and health care information with
            retention of the same for use in health care provider appointments,
            and communications; (iv) administrative support in connection with
            scheduling, and payment for health care provider services; and (v)
            telecommunications support for using the Services as a means of
            direct access to health care providers provided by PureBlue and
            similar affiliated professional entities for communication,
            consultations, assessments, and treatment by such health care
            organizations and their providers.
            <br />
            <br />
            These terms and conditions of use (“Terms of Use”) describe your
            rights and responsibilities with regard to the PureBlue Sites that
            you may use to receive Services. Your access to and use of the Sites
            is subject to these Terms of Use, our Privacy Policy, as well as all
            applicable laws and regulations. In these Terms of Use, the terms
            “you” and “yours” refer to the person using the Services. Even
            though you may have arrived to the Sites through a website or mobile
            application operated or controlled by a third party, you understand
            and agree that these Terms of Use are entered into between you and
            PureBlue. If you do not accept and agree to be bound by these Terms
            of Use, you are not authorized to access or otherwise use the Sites,
            Services or any information or Content provided through the Sites or
            Services. The Sites and Services are continually under development,
            and PureBlue reserves the right to review or remove any part of
            these Terms of Use in its sole discretion at any time and without
            prior notice to you. Any changes to these Terms of Use are effective
            upon posting to the Sites.
            <br />
            <br />
            Unless otherwise indicated, any new Content added to the Services is
            also subject to these Terms of Use upon posting to the Sites. If you
            disagree with these Terms of Use, your sole and exclusive remedy is
            to discontinue your use of the Sites and/or Services. Your continued
            use after a change has been posted constitutes your acceptance of
            the changes.
          </p>
          <h2>AVAILABILITY</h2>
          <p>
            Certain of our Services are currently only available to individuals
            located in certain states. (See List of States.)
          </p>
          <h2>ELIGIBILITY</h2>
          <p>
            In order to qualify to use the Services, the following must be true:
          </p>
          <ul>
            <li>
              You are age 18 years or over or are accompanied by your
              parent/guardian.
            </li>
            <li>You are located in a State Where We Operate.</li>
            <li>
              You agree to be legally bound by and comply with these Terms of
              Use. You understand and agree that satisfying the above
              requirements does not guarantee that you will receive Services
              through PureBlue. In addition to the above requirements, PureBlue
              and certain affiliated professional entities reserve the right to
              change or include new requirements as deemed appropriate in their
              sole discretion without providing prior notice to you.
            </li>
          </ul>
          <h2>REQUIREMENTS FOR USE</h2>
          <p>
            You must have compatible computing and/or mobile devices, access to
            the Internet, and certain necessary software in order to use the
            Sites.
          </p>
          <h2>FULFILLMENT</h2>
          <p>
            Medical consultations and messages will be reviewed within 24 hours
            of submission.
          </p>
          <h2>SPECIAL CONSENT TO TELEHEALTH SERVICES</h2>
          <p>
            Telemedicine involves the delivery of health care services using
            electronic communications, information technology, or other means
            between a health care provider and a patient who are not in the same
            physical location. Telemedicine may be used for diagnosis,
            treatment, follow-up and/or related patient education, and may
            include, but is not limited to:
          </p>
          <ul>
            <li>
              Electronic transmission of medical records, photo images, personal
              health information, or other data between a patient and health
              care provider;
            </li>
            <li>
              Interactions between a patient and health care provider via audio,
              video, and/or data communications; and
            </li>
            <li>
              Use of output data from medical devices, sound, and video files.
              The electronic systems used in the Services will incorporate
              network and software security protocols to protect the privacy and
              security of health information and imaging data, and will include
              measures to safeguard the data to ensure its integrity against
              intentional or unintentional corruption.
            </li>
          </ul>
          <h2>CALIFORNIA NOTICE TO CONSUMERS</h2>
          <p>
            Medical doctors are licensed and regulated by the Medical Board of
            California.
            <br />
            (800) 633-2322 <br />
            www.mbc.ca.gov/
            <br />
            Complaints may be filed online at http://www.mbc.ca.gov/
            <br />
            Breeze/Complaints.aspx or submitted in hard copy form. A Consumer
            Complaint Form, including instructions for completing it, may be
            found at http://www.mbc.ca.gov/
            <br />
            Consumers/Complaints/
            <br />
            Submit_By_Mail.aspx. A hard copy Consumer Complaint Form should be
            submitted to:
            <br />
            Medical Board of California
            <br />
            Central Complaint Unit
            <br />
            2005 Evergreen Street, Suite 1200
            <br />
            Sacramento, CA 95815
            <br />
            The Central Complaint Unit of the Medical Board of California can be
            contacted by phone at 1-800-633-2322 or 916-263-2382.
          </p>
          <h2>KANSAS</h2>
          <p>
            It is unlawful for any person who is not licensed under the Kansas
            Healing Arts Act to open or maintain an office for the practice of
            the healing arts in this State.
            <br />
            <br />
            This office is maintained under the authority of a person who is
            licensed to practice the healing arts of Kansas.
            <br />
            <br />
            Questions and concerns regarding this professional practice may be
            directed to:
            <br />
            Kansas State Board Of Healing Arts
            <br />
            800 SW Jackson, Lower Level-Suite A
            <br />
            Topeka, Kansas 66612
            <br />
            Phone: (785) 296-7413
            <br />
            Toll Free: 1(888) 886-7205
            <br />
            Fax: (785) 296-0852
            <br />
            Website: www.ksbha.org
          </p>
          <h2>OREGON</h2>
          <p>
            Complaints about physicians, as well as other licensees and
            registrants of the Oregon Medical Board, including physician
            assistants, acupuncturists, and surgical assistants may be reported
            for investigation to:
            <br />
            Oregon Medical Board
            <br />
            Investigations Manager
            <br />
            1500 SW 1st Ave. #620
            <br />
            Portland, OR 97201
            <br />
            P: (971) 673-2702
            <br />
            Toll Free: 1(877) 254-6263
            <br />
            https://www.oregon.gov/omb/investigations/pages/how-to-file-a-complaint.aspx
          </p>
          <h2>TEXAS</h2>
          <p>
            Complaints about physicians, as well as other licensees and
            registrants of the Texas Medical Board, including physician
            assistants, acupuncturists, and surgical assistants may be reported
            for investigation to:
            <br />
            Texas Medical Board
            <br />
            Attention: Investigators
            <br />
            333 Guadalupe, Tower 3, Suite 610
            <br />
            P.O Box 2018, MC-263
            <br />
            Austin, TX 78768-2018
            <br />
            Assistance in filing a complaint is available by calling
            1-800-201-9353. For more information, visit www.tmb.state.tx.us
            <br />
            Las quejas sobre médicos, asi como sobre otros profesionales
            acreditados e inscritos del Consejo Médico de Tejas, incluyendo
            asistentes de médicos, practicantes de acupuntura y asistentes de
            cirugia, se pueden presentar en la siguiente dirección para ser
            investigadas:
            <br />
            Texas Medical Board Attention: Investigations 333 Guadalupe, Tower
            3, Suite 610 P.O. Box 2018, MC-263 Austin, Texas 78768-2018
            <br />
            Si necesita ayuda para presentar una queja, lame al: 1-800-201-9353,
            Para obtener más información, visite nuestro sitio web en
            www.tmb.state.tx.us.
          </p>
          <h2>PRIVACY POLICY</h2>
          <p>
            PureBlue understands the importance of confidentiality and privacy
            regarding your health information. PureBlue will act in accordance
            with HIPAA to protect your private health information.
          </p>
          <h2>YOUR RELATIONSHIP WITH PureBlue</h2>
          <p>
            PureBlue does not provide any medical services, including via the
            Sites and Services. Rather, PureBlue provides a technology platform
            for you to access a health care provider employed or contracted with
            PureBlue physicians or similar affiliated professional entities and
            obtain access to additional information, which you may or may not
            choose to utilize in planning your health care and wellness. The
            health and wellness resources made available through our Services
            are not a substitute for direct in-person health care services in
            all cases. The decision to focus on diagnosis, treatment
            recommendations, or both, rests with you and the health care
            provider. You understand that by coordinating and in certain cases
            consulting with PureBlue or affiliate health care provider through
            the Services, you are not entering into a provider-patient
            relationship with PureBlue itself.
            <br />
            <br /> By accepting the Terms of Use, you agree and consent to
            PureBlue, PureBlue affiliates, or health care providers sending you
            disclosures, notices, messages, reports, and other communications.
            It is your responsibility to monitor these communications. You
            acknowledge and agree that you will not hold us or any PureBlue
            affiliate liable for any loss, injury, or claim of any kind
            resulting from your failure to read these communications or for your
            failure to comply with any treatment recommendations contained in
            these communications.
          </p>
          <h2>CONSULTATIVE SERVICE</h2>
          <p>
            In some cases, a PureBlue physician or affiliated health care
            provider may use the Services to provide advice or treatment to you.
            A health care provider consulting with you through the Services may
            not have the benefit of information that would be obtained by
            examining you in person and observing your physical condition, in
            each instance. Therefore, the health care provider may not be aware
            of facts or information that may affect his or her opinion regarding
            a potential diagnosis or treatment recommendation. To reduce the
            risk to you of this limitation, PureBlue strongly encourages you to
            provide all relevant information and discuss any and all diagnosis
            and treatment options with a health care provider. Moreover, a
            health care provider utilizing PureBlue may be limited by state law
            in prescribing certain medications to you without first conducting
            an in-person physical examination. By deciding to engage the
            Services, you acknowledge and agree that you are aware of these
            limitations and agree to assume the risk of these limitations.
            Furthermore, you agree and accept that: (i) any diagnosis you may
            receive is limited and, in some cases, provisional;
            <br />
            <br /> (ii) the health care services are not intended, in all cases,
            to replace a full medical evaluation or an in-person visit with a
            health care provider; (iii) a health care provider acting through
            the Services may not have important information
            <br />
            <br /> that is usually obtained through a “hands-on” physical
            examination; and (iv) the absence of a physical examination may
            affect the health care provider’s ability to diagnose any potential
            condition, disease or injury.
            <br />
            <br /> For more information regarding the health care services
            offered by health care providers utilizing the Services, please
            visit mdintegrations.com.
          </p>
          <h2>SITE CONTENT</h2>
          <p>
            Except for specific communications received from your PureBlue
            physician or affiliate health care organizations and providers, none
            of the Content you receive through the Sites should be considered
            medical advice.
          </p>
          <h2>REGISTRATION AND USER ACCOUNTS</h2>
          <p>
            Although certain parts of the Sites are accessible by any
            individual, you are obligated to register with PureBlue in order to
            access the Services. The Services are available only to users who
            have registered with PureBlue and to other persons affiliated with
            PureBlue who have been granted accounts with usernames and passwords
            (“Secure Users”). If you are a Secure User, you agree to provide
            information that is accurate, complete and correct, and to
            accurately maintain and update any information about yourself that
            you have provided to PureBlue. If you do not maintain such
            information, or PureBlue has reasonable grounds to suspect as much,
            PureBlue has the right to suspend or terminate your account and your
            use of the Services. You agree to keep confidential your username
            and password and to exit from your Secure User account at the end of
            each session. You are responsible for all activities that occur
            under your account and for maintaining the confidentiality of your
            password. You are responsible for changing your password promptly if
            you think it has been compromised. You may not transfer or share
            your password with anyone, or create more than one account. You may
            not use anyone else’s account at any time. PureBlue explicitly
            disclaims liability for any and all losses and damages arising from
            your failure to comply with this section. You acknowledge and agree
            that: (1) all or any part of the Sites may not be accessible at any
            time, for any period, or for any reason; and (2) PureBlue will not
            be liable if for any reason all or any part of the Sites are
            unavailable at any time or for any period.
          </p>
          <h2>ACCESS RIGHTS AND PROHIBITED USE</h2>
          <p>
            Subject to your compliance with these Terms of Use, we hereby grant
            to you a personal, limited, revocable, non-exclusive, and
            nontransferable right to view, download, access, and use the Sites
            in the United States and to use the Services solely for your
            personal and non-commercial use and only as permitted under these
            Terms of Use, the Consent to Telehealth, and the Privacy Policy.
          </p>
          <h2>OWNERSHIP OF SITE CONTENT</h2>
          <p>
            As between PureBlue and you, PureBlue is the sole and exclusive
            owner of all right, title and interest in and to the Sites and their
            content, features and functionality, other Content, and all
            intellectual property rights therein, and any suggestions, ideas or
            other feedback provided by you.
          </p>
          <h2>LINKS TO THIRD-PARTY HYPERLINKS AND WEBSITES</h2>
          <p>
            The Sites may contain hyperlinks or references to other websites
            (“Linked Sites”) operated by third parties. The Linked Sites may not
            be under our control, therefore, we are not responsible for the
            information, products or services described thereon, or for the
            content of any Linked Site, including, without limitation, any link
            contained in a Linked Site, or any changes or updates to a Linked
            Site. We are providing these Linked Sites to you only as a
            convenience, and the inclusion of any link does not necessarily
            imply endorsement of the Linked Site or any association with its
            operators. Your use of these Linked Sites is at your own risk, and
            we are not liable to you in any way, either directly or indirectly,
            for any content, errors, damage or loss caused by or in connection
            with use of or reliance on information contained in or provided to
            Linked Sites.
            <br />
            <br /> You may have arrived to the Sites through a Linked Site,
            including a Linked Site controlled by a parent, subsidiary or
            affiliate of PureBlue. You understand and agree that we are not
            responsible for the information, products or services described on
            those Linked Sites and only these Terms of Use will apply to your
            use of or access to the Sites.{" "}
          </p>
          <h2>TERMINATION</h2>
          <p>
            The Terms of Use will remain in full force and effect as long as you
            continue to access or use the Sites or Services. You may terminate
            the Terms of Use at any time by discontinuing use of the Sites. Your
            permission to use the Sites automatically terminates if you violate
            these Terms of Use.
            <br />
            <br /> PureBlue may terminate or suspend any of the rights granted
            by these Terms of Use and your access to and use of the Sites or
            Services with or without prior notice, for any reason, and at any
            time. The following provisions survive the expiration or termination
            of these Terms of Use for any reason whatsoever: Disclaimer of
            Warranties; Limitation of Liability; Indemnification; Governing Law,
            Dispute Resolution, Venue, Severability of Provisions; No Waiver;
            and Assignment.
            <br />
            <br /> After such termination, PureBlue will have no further
            obligation to provide the Services, except to the extent an
            affiliated professional entity is obligated to provide you access to
            your health records or is required to provide you with continuing
            care under applicable legal, ethical and professional obligations to
            you.
          </p>
          <h2>DISCLAIMER OF WARRANTIES</h2>
          <p>
            YOU EXPRESSLY AGREE THAT USE OF THE SITES IS AT YOUR SOLE RISK. YOU
            ACKNOWLEDGE AND AGREE THAT THE SITES AND ANY SERVICES ARE PROVIDED
            THROUGH THE SITES ON AN “AS IS” AND “AS AVAILABLE” BASIS. PureBlue
            AND ITS AFFILIATES, INCLUDING WITHOUT LIMITATION ALL AFFILIATED
            PROFESSIONALS, PROFESSIONAL ENTITIES, AND THEIR RESPECTIVE OFFICERS,
            DIRECTORS, MANAGERS, PARTNERS, MEMBERS, EMPLOYEES, AND AGENTS
            (COLLECTIVELY “RELATED PERSONS”) MAKE NO REPRESENTATIONS OR
            WARRANTIES AND EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES OF ANY
            KIND, WHETHER EXPRESS OR IMPLIED, WITH RESPECT TO THE SITES AND
            SERVICES INCLUDING, BUT NOT LIMITED TO, ANY REPRESENTATIONS OR
            WARRANTIES WITH RESPECT TO FITNESS FOR A PARTICULAR USE OR PURPOSE,
            NONINFRINGEMENT, TITLE, AVAILABILITY, SECURITY, OPERABILITY,
            CONDITION, QUIET ENJOYMENT, VALUE, ACCURACY OF DATA, FREEDOM FROM
            VIRUSES OR MALWARE, COMPLETENESS, TIMELINESS, FUNCTIONALITY,
            RELIABILITY, SEQUENCING OR SPEED OF DELIVERY OR SYSTEM INTEGRATION.
            WE MAKE NO WARRANTIES OR REPRESENTATIONS THAT YOUR USE OF THE SITES
            OR SERVICES WILL NOT INFRINGE THE RIGHTS OF THIRD PARTIES. <br />
            <br /> TO THE FULLEST EXTENT OF APPLICABLE LAW, NEITHER PureBlue NOR
            ITS RELATED PERSONS WILL BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY
            YOUR RELIANCE ON INFORMATION OBTAINED THROUGH THE SITES. IT IS YOUR
            RESPONSIBILITY TO EVALUATE THE ACCURACY, COMPLETENESS, TIMELINESS,
            RELIABILITY OR USEFULNESS OF THE SITES. FURTHERMORE, PureBlue DOES
            NOT GUARANTEE THAT THE SITES WILL BE UNINTERRUPTED, OR FREE FROM
            ERROR, DEFECT, LOSS, DELAY IN OPERATION, CORRUPTION, CYBER ATTACK,
            VIRUSES, INTERFERENCE, HACKING, MALWARE, OR OTHER SECURITY
            INTRUSION, AND PureBlue DISCLAIMS ANY LIABILITY RELATING THERETO.
            <br />
            <br /> YOU UNDERSTAND AND AGREE THAT ANY CONTENT, MATERIAL AND/OR
            INFORMATION OBTAINED THROUGH THE USE OF THE SITES ARE USED AT YOUR
            SOLE RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO
            YOUR COMPUTER OR MOBILE PHONE OR LOSS OF DATA THAT RESULTS FROM THE
            DOWNLOAD OF SUCH CONTENT, MATERIAL AND/OR INFORMATION.{" "}
          </p>
          <h2>LIMITATION OF LIABILITY</h2>
          <p>
            YOU UNDERSTAND THAT TO THE EXTENT PERMITTED UNDER APPLICABLE LAW AND
            EXCEPT AS SET FORTH IN THIS SECTION, IN NO EVENT WILL PureBlue, ITS
            RELATED PERSONS OR ENTITIES OR LICENSORS BE LIABLE TO YOU OR TO ANY
            PARTY FOR ANY CLAIMS, LIABILITIES, LOSSES, COSTS OR DAMAGES UNDER
            ANY LEGAL OR EQUITABLE THEORY, WHETHER IN TORT (INCLUDING
            NEGLIGENCE), CONTRACT, WARRANTY, OR OTHERWISE, INCLUDING, BUT NOT
            LIMITED TO, ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
            PUNITIVE OR EXEMPLARY DAMAGES, OR FOR ANY DAMAGES FOR PERSONAL OR
            BODILY INJURY OR EMOTIONAL DISTRESS, INCLUDING DEATH, ARISING OUT OF
            OR IN CONNECTION WITH ANY ACCESS, USE OF (OR INABILITY TO USE) THE
            SITES OR ANY SERVICES PROVIDED THROUGH THE SITES, OR OTHER
            INTANGIBLE LOSSES ARISING OUT OF OR RELATED TO YOUR USE OF THE
            SITES. THIS IS TRUE EVEN IF PureBlue OR RELATED PERSONS HAVE BEEN
            ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES.
            <br />
            <br /> To the extent that we may not, as a matter of applicable law,
            disclaim any implied warranty or limit liabilities, the scope and
            duration of such warranty and the extent of our liability will be
            the minimum permitted under such applicable law.
          </p>
          <h2>INDEMNIFICATION</h2>
          <p>
            You agree to indemnify, defend, and hold harmless PureBlue, its
            affiliates (including without limitation all affiliated
            professionals and professional entities), subsidiaries, and their
            directors, officers, employees, contractors, licensors,
            representatives, proprietors, partners, shareholders, servants,
            principals, agents, assigns, and attorneys harmless from and against
            any and all third-party suits, actions, claims, proceedings,
            damages, settlements, judgments, injuries, liabilities, obligations,
            losses, risks, costs, and expenses (including, without limitation,
            reasonable attorneys’ fees, litigation expenses, and accounting
            fees), relating to or arising from, or alleged to arise from, your
            use of materials or features available on the Site.
          </p>
          <h2>MODIFICATIONS TO THE SITES</h2>
          <p>
            PureBlue reserves the right at any time and for any reason to
            modify, or temporarily or permanently discontinue, the Sites or
            Services or any portion thereof, with or without notice. You agree
            that PureBlue shall not be liable to you or to any third party for
            any modification, suspension, or discontinuance of the Site or
            Services.
          </p>
          <h2>PAYMENT</h2>
          <p>
            You agree to pay all fees due for services requested. You will see a
            prompt for your payment details, such as your credit card
            information and any promotional codes you may have. By entering your
            payment information and submitting your request, you authorize us,
            our affiliates, or our third-party payment processors to charge the
            amount due.
            <br />
            <br /> GOVERNING LAW; DISPUTE RESOLUTION; ARBITRATION; VENUE;
            SEVERABILITY OF PROVISIONS <br />
            <br /> PLEASE READ THIS SECTION CAREFULLY BECAUSE IT REQUIRES YOU
            AND PureBlue TO RESOLVE ALL DISPUTES BETWEEN US AND LIMITS THE
            MANNER IN WHICH YOU CAN SEEK RELIEF FROM PureBlue.
            <br />
            <br /> These Terms of Use and your use of the Sites shall be
            governed by the laws of the State of New York, without giving effect
            to the principles of conflict of laws. Any dispute arising under or
            relating in any way to these Terms of Use will be resolved
            exclusively in the County of Nassau, New York. The parties agree
            that the Supreme Court of the State of New York located in Nassau
            County, New York shall have exclusive personal jurisdiction, subject
            matter jurisdiction, and venue for any such claim.
            <br />
            <br /> All parts of these Terms of Use apply to the maximum extent
            permitted by law. PureBlue and you both agree that if we cannot
            enforce a part of this contract
            <br />
            <br />
            as written, then that part will be replaced with terms that most
            closely match the intent of the part we cannot enforce, to the
            extent permitted by law. <br />
            <br />
            The invalidity of part of these Terms of Use will not affect the
            validity and enforceability of the remaining provisions. The section
            headings are for convenience only and do not have any force or
            effect.{" "}
          </p>
          <h2>NO WAIVER</h2>
          <p>
            No waiver by PureBlue of any term or condition set forth in these
            Terms of Use shall be deemed a further or continuing waiver of such
            term or condition or a waiver of any other term or condition, and
            any failure by PureBlue to assert a right or provision under these
            Terms of Use shall not constitute a waiver of such right or
            provision.
          </p>
          <h2>REMEDIES</h2>
          <p>
            You agree that any violation, or threatened violation, by you of
            these Terms of Use constitutes an unlawful and unfair business
            practice that will cause us irreparable and unquantifiable harm. You
            also agree that monetary damages would be inadequate for such harm
            and consent to our obtaining any injunctive or equitable relief that
            we deem necessary or appropriate. These remedies are in addition to
            any other remedies we may have at law or in equity.
          </p>
          <h2>ASSIGNMENT</h2>
          <p>
            You may not assign any of your rights under this agreement, and any
            such attempt will be null and void.
          </p>
          <h2>DIGITAL MILLENNIUM COPYRIGHT ACT</h2>
          <p>
            PureBlue reserves the right to remove any content or any other
            material or information available on or through our Sites, at any
            time, for any reason. PureBlue otherwise complies with the
            provisions of the Digital Millennium Copyright Act (“DMCA”)
            applicable to Internet service providers (17 U.S.C. § 512, as
            amended), and responds to clear notices of alleged copyright
            infringement. This Section describes the procedure that should be
            followed to file a notification of alleged copyright infringement
            with PureBlue <br />
            <br /> Notification of Claimed Copyright Infringement. If you have
            objections to copyrighted content or material made available on or
            through our Sites, you may submit a notification to our Designated
            Agent at the following address: info@trypureblue.com <br />
            <br />
            Any notification to PureBlue under 17 U.S.C. § 512(c) alleging
            copyright infringement must include the following information:
          </p>
          <ul>
            <li>
              An electronic or physical signature of the person authorized to
              act on behalf of the owner of the exclusive right being infringed;
            </li>
            <li>
              An identification of the copyrighted work or other intellectual
              property that you claim has been infringed or, if multiple
              copyrighted works are covered by a single notification, a
              representative list of such works;
            </li>
            <li>
              An identification of the content or material that you claim is
              infringing and where it is located on our Sites;
            </li>
            <li>
              Information sufficient for PureBlue to contact you, such as your
              address, telephone number, and/or email address;
            </li>
            <li>
              A statement by you that you have a good-faith belief that the use
              of the content or material of which you are complaining is not
              authorized by the copyright owner, its agent, or the law; and
            </li>
            <li>
              A signed statement by you that the above information in your
              notice is accurate and that, under penalty of perjury, you are the
              copyright owner or authorized to act on the copyright owner’s
              behalf.
            </li>
          </ul>
          <h2>
            HIPAA (Health Information Portability and Accountability)
            Information
          </h2>
          <b>
            Uses and disclosures of your protected health information that do
            not require an authorization
          </b>
          <p>
            Treatment. For example, doctors, nurses, and other staff members
            involved in your care will use your PHI to coordinate your care or
            to plan a course of treatment for you.
          </p>
          <p>
            Payment. For example, we may disclose information regarding your
            medical procedures and treatment to your insurance company to
            arrange payment for the services provided to you.
          </p>
          <p>
            Health Care Operations. For example, we may disclose your PHI for
            billing or interpreter support. We may use your PHI to conduct an
            evaluation of the treatment and services provided or to review staff
            performance.
          </p>
          <p>
            Communicating with You. We will use your PHI to communicate with you
            about a number of important topics, including information about your
            care, treatment options and other health-related services
          </p>
          <p>
            We may also contact you at the email, phone number or address that
            you provide, including via text messages, for these communications.
            If your contact information changes, it is important that you let us
            know. We will only provide you a link via text or e-mail which will
            require you to verify yourself prior to opening the message within
            the MDI messaging portal.
          </p>
          <p>
            Business Associates. At times, we need to disclose your PHI to
            persons or organizations outside MDI who assist us with our
            payment/billing and health care operations. We require these
            business associates and their subcontractors to appropriately
            safeguard your PHI.
          </p>
          <p>
            Other Uses and Disclosures. We may be permitted or required by law
            to make certain other uses and disclosures of your PHI without your
            authorization. Subject to conditions specified by law, we may
            release your PHI:
          </p>
          <ul>
            <li>for any purpose required by law</li>
            <li>
              for public health activities, including required reporting of
              disease, injury, birth and death, for required public health
              investigations, and to report adverse events or enable product
              recalls
            </li>
            <li>
              to government agencies if we suspect child/elder adult abuse or
              neglect. We may also release your PHI to government agencies if we
              believe you are a victim of abuse, neglect or domestic
            </li>
            <li>
              to your employer when we have provided screenings and health care
              at their request for occupational health and safety
            </li>
            <li>
              to a government oversight agency conducting audits,
              investigations, inspections and related oversight functions
            </li>
            <li>
              in emergencies, such as to prevent a serious and imminent threat
              to a person or the public
            </li>
            <li>
              if required by a court or administrative order, subpoena or
              discovery request
            </li>
            <li>
              for law enforcement purposes, including to law enforcement
              officials to identify or locate suspects, fugitives or witnesses,
              or victims of crime
            </li>
            <li>to coroners, medical examiners and funeral directors</li>
            <li>
              if necessary to arrange organ or tissue donation or transplant
            </li>
            <li>
              for national security, intelligence, or protective services
              activities
            </li>
            <li>for purposes related to your workers’ compensation benefits</li>
          </ul>
          <p>
            Uses and disclosures of your protected health information based on a
            signed authorization
            <br />
            <br />
            Except as outlined above, we will not use or disclose your PHI for
            any other purpose unless you have signed a form authorizing the use
            or disclosure. You may revoke an authorization in writing, except to
            the extent we have already relied upon it.
            <br />
            <br />
            In some situations, a signed authorization form is required for uses
            and disclosures of your PHI, including:
            <ul>
              <li>most uses and disclosures of psychotherapy notes</li>
              <li>uses and disclosures for marketing purposes</li>
              <li>disclosures that constitute the sale of PHI</li>
              <li>uses and disclosures for certain research protocols</li>
              <li>
                as required by privacy law. The confidentiality of substance use
                disorder and mental health treatment records as well as
                HIV-related information maintained by us is specifically
                protected by state and/or federal law and regulations.
                Generally, we may not disclose such information unless you
                consent in writing, the disclosure is allowed by a court order,
                or in other limited, regulated circumstances.
              </li>
            </ul>
          </p>
          <h2>Your rights</h2>
          <p>
            Access to Your PHI. You can access and inspect paper or electronic
            copies of certain PHI that we maintain about you. You may readily
            access much of your health information without charge using the
            following link: https://privacy.mdintegrations.com. In line with set
            fees under federal and state law, we may charge you for a copy of
            your medical records.
            <br />
            <br /> Amendments to Your PHI. You can request amendments, or
            changes, to certain PHI that we maintain about you that you think
            may be incorrect or incomplete. All requests for changes must be in
            writing, signed by you or your representative, and state the reasons
            for the request. If we decide to make an amendment, we may also
            notify others who have copies of the information about the change.
            Note that even if we accept your request, we may not delete any
            information already documented in your medical record. You can make
            such requests by contacting info@trypureblue.com or directly inside
            your MDI patient portal under the “privacy center” section.
            <br />
            <br /> Accounting for Disclosures of Your PHI. In accordance with
            applicable law, you can ask for an accounting of certain disclosures
            made by us of your PHI. This request must be in writing and signed
            by you or your representative. This does not include disclosures
            made for purposes of treatment, payment, or health care operations
            or for certain other limited exceptions. An accounting will include
            disclosures made in the six years prior to the date of a request.
            <br />
            <br /> Restrictions on Use and Disclosure of Your PHI. You can
            request restrictions on certain of our uses and disclosures of your
            PHI for treatment, payment, or health care operations. We are not
            required to agree but will attempt to accommodate reasonable
            requests when appropriate.
            <br />
            <br /> Restrictions on Disclosures to Health Plans. You can request
            a restriction on certain disclosures of your PHI to your health
            plan. We are only required to honor such requests when services
            subject to the request are paid in full. Such requests must be made
            in writing and identify the services to which the restriction will
            apply.
            <br />
            <br /> Confidential Communications. You can request that we
            communicate with you through alternative means or at alternative
            locations, and we will accommodate reasonable requests. You must
            request such confidential communication in writing to each
            department you would like to accommodate the request.
            <br />
            <br /> Breach Notification. We are required to notify you in writing
            of any breach of your unsecured PHI without unreasonable delay and
            no later than 60 days after we discover the breach.
          </p>
          <h2>Additional Information</h2>
          <p>
            Complaints. If you believe your privacy rights have been violated,
            you can file a complaint with the PureBlue privacy officer by
            contacting info@trypureblue.com or calling 1-888-534-8977.
            <br />
            <br /> You can also file a complaint with the Secretary of the U.S.
            Department of Health and Human Services in Washington D.C.
            <br />
            <br />A complaint must be made in writing and will not in any way
            affect the quality of care we provide you.{" "}
          </p>
        </Container>
      </main>
    </div>
  );
}
