import Head from "next/head";
import Link from "next/link";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row } from "react-bootstrap";
import Accordion from "react-bootstrap/Accordion";
import Image from "next/image";
import styles from "./styles.module.scss";
import { Check, PatchCheck } from "react-bootstrap-icons";
import { Card } from "react-bootstrap";
import { useAccordionButton } from "react-bootstrap/AccordionButton";
import { AccordionContext, Form } from "react-bootstrap";
export default function Home() {
  function ContextAwareToggle({ children, eventKey, callback }) {
    const { activeEventKey } = useContext(AccordionContext);
    const decoratedOnClick = useAccordionButton(
      eventKey,
      () => callback && callback(eventKey)
    );

    const isCurrentEventKey = activeEventKey === eventKey;

    return (
      <button
        type="button"
        className="headerOne"
        style={{
          backgroundColor: isCurrentEventKey ? "#fff" : "#fff",
          border: "0px",
          color: "#000",
          fontWeight: "800",
          padding: "0px 12px 0px 12px",
          width: "100%",
          textAlign: "left",
        }}
        onClick={decoratedOnClick}
      >
        {children}
      </button>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.aboutPage}>
        <Container className={styles.container}>
          <h1>PureBlue Consent To Telehealth</h1>
          <p className={styles.blueText}>
            YOU UNDERSTAND THAT BY CHECKING THE “AGREE” BOX FOR THIS CONSENT TO
            TELEHEALTH YOU CONSENT AND AGREE TO RECEIVE SERVICES USING
            TELEHEALTH TECHNOLOGY; THAT YOU ARE SIGNING THIS CONSENT
            ELECTRONICALLY; AND THAT YOU HAVE REVIEWED, UNDERSTAND, AND ACCEPT
            THE RISKS AND BENEFITS OF TELEHEALTH SERVICES DESCRIBED BELOW AND
            WISH TO RECEIVE SUCH SERVICES.
          </p>
          <p>
            All capitalized terms used in this Consent to Telehealth but not
            defined herein have the meanings assigned to them in the Terms and
            Conditions. For avoidance of any doubt, the terms “PureBlue”, “we”,
            “us”, or “our” refer to PureBlue and the terms “you” and “yours”
            refer to the person using the Service.
          </p>
          <h2>What is Telehealth?</h2>
          <p>
            Telehealth is a way to deliver healthcare services using electronic
            communications, telecommunications, information technology or other
            means between a healthcare provider and a patient who are not in the
            same physical location. It is a convenient way to meet with your
            healthcare provider from any place, including your home.
          </p>
          <h2>How is Telehealth Used?</h2>
          <p>
            Telehealth may be used to deliver clinical health care, including
            diagnosis, treatment and follow-up; health education; and public
            health administration. Telehealth is used to for different
            functions, including:
          </p>
          <ul>
            <li>
              Electronic transmission of medical records, photo images, personal
              health information or other data between you and a health care
              provider;
            </li>
            <li>
              Storage and forwarding of diagnostic images, sound and video files
              to a health care professional; and
            </li>
            <li>
              Audio or video conferencing and/or data communications between you
              and a health care provider.
            </li>
          </ul>
          <h2>Is Your Privacy Protected?</h2>
          <p>
            The PureBlue Service will incorporate network and software security
            protocols in all technologies and electronic systems used to deliver
            telehealth, to protect the privacy and security of health
            information and data, and will include measures to safeguard your
            protected health information and data, to ensure its integrity
            against intentional or unintentional corruption. Your visits with
            your health care provider are private and will not be recorded.
          </p>
          <h2>The Benefits of Telemedicine</h2>
          <ul>
            <li>
              As you do not have to go to a clinic or hospital to see your
              health care provider, it provides an easier, more efficient way
              for you to access medical care and treatment.
            </li>
            <li>
              You can manage your interactions with your health care provider
              more conveniently and efficiently.
            </li>
            <li>
              You can avoid coming in contact with other sick people in a clinic
              or hospital.
            </li>
          </ul>
          <h2>Possible Risks of Telehealth</h2>
          <ul>
            <li>
              Seeing your health care provider outside the typical healthcare
              setting may feel different and you may find it difficult to
              communicate with and give sufficient information to your health
              care provider.
            </li>
            <li>
              Your health care provider may not be able to provide a diagnosis
              or treatment because of the inability to conduct physical tests
              and a close physical examination, which may require an in-person
              visit.
            </li>
            <li>
              The inability to physically examine you may lead to missed signs
              and symptoms that require emergency medical treatment or further
              medical testing. Your health care provider may not able to provide
              medical treatment for your particular condition via telehealth,
              which may require that you seek alternative care.
            </li>
            <li>
              Technological failures may interrupt your tele-visit with your
              health care provider.
            </li>
            <li>
              Technological failures may cause delays in your evaluation and
              treatment by your health care provider.
            </li>
            <li>
              Technological failures may cause distortion of diagnostic images
              or specimens resulting from electronic transmission issues,
              unauthorized access to your information, or loss of information
              due to technology failures. If you are not in a private place
              during your tele-visit and people are close to you, they may hear
              something that you wish to keep private.
            </li>
            <li>
              Given regulatory requirements in certain jurisdictions, especially
              pertaining to certain prescriptions, your health care provider’s
              treatment options may be limited.
            </li>
          </ul>
          <div className={styles.grayField}>
            <h4>
              By accepting this Consent to Telehealth, you acknowledge,
              understand and agree to the following:
            </h4>
            <ul>
              <li>
                I have read this special Consent to Telehealth carefully, and
                understand the risks and benefits of the use of telehealth in
                the medical care and treatment provided to me through PureBlue’s
                platform by “Providers.”
              </li>
              <li>
                I understand the potential risks and benefits of telehealth and
                will not hold PureBlue responsible for any information lost due
                to technological failures.
              </li>
              <li>
                I understand that while the use of telehealth may provide
                potential benefits to me, such benefits cannot be guaranteed. My
                condition may not be cured or improved, and in some cases, may
                get worse.
              </li>
              <li>
                I understand that my health care Provider may determine in his
                or her sole discretion that my condition is not suitable for
                treatment using telehealth, and may advise that I seek medical
                care and treatment in-person or from an alternative source.
              </li>
              <li>
                I understand that the same confidentiality and privacy
                protections that apply to my other health care services also
                apply to telehealth services.
              </li>
              <li>
                I understand that my healthcare information may be shared with
                other individuals in accordance with PureBlue’s Privacy Policy
                and regulations or laws in the state or territory in which I am
                located.
              </li>
              <li>
                I understand that I have access to all of my health and wellness
                information pertaining to the telehealth services in accordance
                with applicable laws and regulations.
              </li>
              <li>
                I understand that I can withhold or withdraw this consent at any
                time by emailing PureBlue at support@pureblue.com with such
                instruction. Otherwise, this consent will be considered renewed
                upon each new telehealth consultation with my health care
                provider.
              </li>
              <li>
                I agree and authorize my health care Provider to share
                information regarding the telemedicine exam with other
                individuals for treatment, payment and health care operations
                purposes.
              </li>
              <li>
                I agree and authorize my health care Provider to release
                information regarding the telehealth exam to PureBlue and its
                affiliates.
              </li>
              <li>
                I agree and understand that my health care information may be
                shared in the following circumstances:
              </li>
            </ul>
            <ul>
              <li>When a valid court order is issued for medical records.</li>
              <li>Reporting suspected abuse, neglect, or domestic violence.</li>
              <li>
                Preventing or reducing a serious threat to anyone’s health or
                safety.
              </li>
            </ul>
          </div>
          <p className={styles.blueText}>
            PureBlue Asynchronous Telehealth Informed Consent
          </p>
          <p>
            You are viewing this form because you have elected to engage in
            asynchronous telehealth visits with an PureBlue health care
            provider.
          </p>
          <p className={styles.grayText}>
            BY CHECKING THE “AGREE” BOX, YOU ACKNOWLEDGE THAT YOU HAVE READ AND
            UNDERSTAND THE TERMS PRESENTED BELOW, AND UNDERSTAND THE RISKS AND
            BENEFITS OF ASYNCHRONOUS TELEHEALTH, AND BY ACCEPTING THESE TERMS
            AND CONDITIONS YOU HEREBY GIVE YOUR INFORMED CONSENT TO PARTICIPATE
            IN ASYNCHRONOUS TELEHEALTH UNDER THESE TERMS.
          </p>

          <div className={styles.blueLine}></div>
          <h2>What is Asynchronous Telehealth?</h2>
          <p>
            Asynchronous telehealth is a way to deliver telehealth using
            asynchronous communication. Asynchronous communication often
            referred to as “store-and-forward” communication, is communication
            that between participants that doesn’t happen at the same time. An
            example of asynchronous communication is a telehealth encounter with
            a health care provider that involves sending photos, video, or other
            communications via email or text message. “Asynchronous” means “not
            occurring at the same time” and is different from “synchronous”
            telemedicine, which generally includes visits conducted in real-time
            between patients and health care Providers through audio- or
            video-based technology including live phone calls or
            video-conferencing. Health care Providers may use asynchronous
            telehealth to aid in diagnoses and medical consultations when live
            communication or face-to-face contact is not possible or necessary.
          </p>
          <h2>How Does PureBlue Offer Asynchronous Telehealth?</h2>
          <p>
            PureBlue’s platform (“Platform”) allows for the following
            asynchronous telehealth services: 1) text-based health care
            provider-patient interactions through short message service (“SMS”)
            and multimedia messaging service (“MMS”) communications; and 2)
            secure information collection through asynchronous store-and-forward
            patient questionnaires.
          </p>
          <h2>The Benefits of Asynchronous Telehealth</h2>
          <ul>
            <li>
              Asynchronous telehealth allows you and your health care provider
              to interact at a time that suits your schedule.
            </li>
            <li>
              You and your health care provider can access telehealth from where
              and when you want, at different times.
            </li>
            <li>
              Because you are not limited by the scheduled time of an in-person
              or synchronous video or audio visit, you can give your health care
              provider more detailed information than you would if you were
              feeling the pressure under a timed visit.
            </li>
          </ul>
          <h2>Possible Risks to Using Asynchronous Telehealth?</h2>
          <ul>
            <li>
              Your visit with your health care provider may be delayed due to
              technological deficiencies, disruptions, or failures, which may
              include poor data quality, Internet outages, or other service
              interruption issues. You may have to reschedule the visit with
              your health care provider should these interruptions occur.
            </li>
            <li>
              Security protocols could fail, causing a breach of privacy of your
              personal health information.
            </li>
            <li>
              Your health care provider may not be able to fully assess your
              condition without access to your complete medical history, which
              may require you to seek alternative care.
            </li>
            <li>
              Your health care provider does not have access of your complete
              medical records. To reduce the chances of negative outcomes such
              as drug interactions and/or allergic reactions, you should
              disclose a full list of your medical history including diagnoses,
              treatments, medications/supplements, and allergies to your health
              care provider.
            </li>
            <li>
              Asynchronous telehealth services are NOT emergency services and
              your Personal Data (as defined in the PureBlue Privacy Policy)
              WILL NOT BE MONITORED AT ALL TIMES. If you think you are
              experiencing a medical emergency, you should CALL 911 IMMEDIATELY.
            </li>
          </ul>
          <p className={styles.grayText}>
            THE CARE YOU RECEIVE WILL BE AT THE SOLE DISCRETION OF THE HEALTH
            CARE PROVIDER WHO IS TREATING YOU, WITH NO GUARANTEE OF DIAGNOSIS,
            TREATMENT, OR PRESCRIPTION. THE HEALTH CARE PROVIDER WILL DETERMINE
            WHETHER OR NOT THE CONDITION BEING DIAGNOSED AND/OR TREATED IS
            APPROPRIATE FOR THE CARE PROVIDED THROUGH AN ASYNCHRONOUS TELEHEALTH
            ENCOUNTER VIA THE PLATFORM.
            <br />
            <br /> ASYNCHRONOUS TELEHEALTH MAY NOT BE AVAILABLE TO YOU AS MANY
            STATES LEGISLATE AGAINST ITS USE.
          </p>
          <div className={styles.grayField}>
            <h4>
              By accepting this Consent to Asynchronous Telehealth, you
              acknowledge, understand and agree to the following:
            </h4>
            <ul>
              <li>
                I have read this special Consent to Asynchronous Telehealth
                carefully, and understand the risks and benefits of the use of
                telehealth in the medical care and treatment provided to me
                through PureBlue’s platform by “Providers.”
              </li>
              <li>
                I have the same privacy rights via asynchronous telehealth that
                I would have during an in-person visit. Dissemination of any
                identifiable images or protected health information from the
                asynchronous telehealth visit to researchers or other
                third-parties will not occur without my written consent. For
                more information about how PureBlue protects your privacy,
                please read the PureBlue Privacy Policy.
              </li>
              <li>
                Asynchronous telehealth may involve electronic communication of
                my protected health information to health care Providers who may
                be located in other areas, including out of state.
              </li>
              <li>
                I understand that I may expect the anticipated benefits from the
                use of asynchronous telehealth, but that no results can be
                guaranteed or assured.
              </li>
              <li>
                I understand that all information submitted to PureBlue via text
                message and entered by my health care provider in the PureBlue
                Platform will be part of my medical record and available to me
                by emailing support@pureblue.com. This information will have the
                same restrictions on dissemination without my consent.
              </li>
              <li>
                I understand that my health care provider’s initial text message
                to me will include his/her name and credentials, and this will
                be recorded in the PureBlue Platform as part of my medical
                record.
              </li>
              <li>
                I understand that I can withhold or withdraw this consent at any
                time by emailing PureBlue at support@pureblue.com with such
                instruction. Otherwise, this consent will be considered renewed
                upon each new asynchronous telehealth consultation with my
                health care provider.
              </li>
              <li>
                I understand that this consent is not a condition of purchase.
              </li>
              <li>
                I understand that my health care information may be shared with
                other individuals in accordance with the PureBlue Privacy Policy
                and regulations or laws in the state or territory in which I am
                located.
              </li>
              <li>
                I agree and understand that my health care information may be
                shared in the following circumstances:
              </li>
            </ul>
            <ul>
              <li>When a valid court order is issued for medical records.</li>
              <li>Reporting suspected abuse, neglect, or domestic violence.</li>
              <li>
                Preventing or reducing a serious threat to anyone’s health or
                safety.
              </li>
            </ul>
          </div>
          <p>
            <b>Call/Email/Text Messaging Consent:</b> I expressly consent to
            allow PureBlue or its health care Providers to call, email, or text
            me (via SMS and/or MMS) with or regarding Personal Data (as defined
            in the PureBlue Privacy Policy), appointments, or similar matters
            related to my telehealth encounters using the contact information I
            have provided. I understand and agree that any calls or texts to me
            may be placed using an auto-dialer or a pre-recorded or artificial
            voice, even if my number is on a do-not-call list, and that my phone
            carrier’s normal rates may apply. This Asynchronous Telehealth
            Informed Consent is valid during your entire treatment with
            PureBlue.
          </p>
        </Container>
      </main>
    </div>
  );
}
