import Head from "next/head";
import Link from "next/link";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row } from "react-bootstrap";
import Accordion from "react-bootstrap/Accordion";
import Image from "next/image";
import styles from "./styles.module.scss";
import { Check, PatchCheck } from "react-bootstrap-icons";
import { Card } from "react-bootstrap";
import { useAccordionButton } from "react-bootstrap/AccordionButton";
import ButtonGroup from "react-bootstrap/ButtonGroup";
import ToggleButton from "react-bootstrap/ToggleButton";
import { AccordionContext, Form } from "react-bootstrap";
import ShipInfo from "../../components/ShipInfo";

export default function Home() {
  const [formData, setFormData] = useState({
    firstName: "",
    lastName: "",
    shippingAddress: "",
    shippingCityName: "",
    shippingState: "",
    shippingZip: "",
  });

  const handleChange = (event) => {
    const { value, name } = event.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  async function submitHandler(event) {
    event.preventDefault();
    const route = "/api/user/updateShippingInfo";
    try {
      const rese = await Axios.post(route, { Token: authCtx.Token(), formData })
        .then((res) => {
          console.log(res.data);
          setShipInfo(false);
          props.reloadInfo();
        })
        .catch((error) => {
          console.log(error);
          return alert("Not Good!");
        });
    } catch (err) {
      return alert("Something went wrong!" + err);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - Order</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.orderPage}>
        <Container>
          <div className={styles.fieldOne}>
            <Col md={{ span: 7, offset: 5 }}>
              <div className={styles.callUs}>
                <Link href="tel: 1-888-534-8977">
                  <a>
                    Call toll free to order:{" "}
                    <span className={styles.blueText}>1-888-534-8977</span>
                  </a>
                </Link>
              </div>
            </Col>
            <Row>
              <Col md={6}>
                <div className="d-flex pb-5 justify-content-center">
                  <Image
                    src="/assets/order/bottle.png"
                    height={180}
                    width={100}
                  />
                </div>
                <Row>
                  <Col md={8}>
                    <h3>17 x Sildenafil </h3>
                    <ul>
                      <li>
                        <Check className={styles.checkmark} />
                        Seventeen 30 MG Sildenafil
                      </li>
                      <li>
                        <Check className={styles.checkmark} />
                        Discreet shipping to your house
                      </li>
                      <li>
                        <Check className={styles.checkmark} />
                        FREE online physician consultation.
                      </li>
                      <li>
                        <Check className={styles.checkmark} />
                        Monthly refills
                      </li>
                      <li>
                        <Check className={styles.checkmark} />
                        24/7 support
                      </li>
                    </ul>
                  </Col>
                  <Col md={4}>
                    <Button className={styles.switch}>SWITCH</Button>
                  </Col>
                </Row>
                <div className={styles.totalPrice}>
                  <Row className={styles.row}>
                    <Col xs={6}>Price</Col>
                    <Col xs={6}>$50.00/MO</Col>
                  </Row>
                  <Row className={styles.row}>
                    <Col xs={6}>Shipping</Col>
                    <Col xs={6}>$29.95</Col>
                  </Row>
                  <Row className={styles.row}>
                    <Col xs={6}>Service Charge including Tax</Col>
                    <Col xs={6}>$4.25</Col>
                  </Row>
                  <Row className={styles.row}>
                    <Col xs={6}>Grand Total</Col>
                    <Col xs={6}>$84.20</Col>
                  </Row>
                </div>
                <ul>
                  <li>
                    <Check className={styles.checkmark} />
                    Automatic refills every 30 days.
                  </li>
                  <li>
                    <Check className={styles.checkmark} />
                    Cancel anytime. No gimmicks.
                  </li>
                  <li>
                    <Check className={styles.checkmark} />
                    Payment does not guarantee a prescription.
                  </li>
                  <li>
                    <Check className={styles.checkmark} />
                    100% refund if no prescription is written.
                  </li>
                </ul>
                <p className={styles.valid}>
                  Valid US Government issued ID verification required after
                  checkout.
                </p>
              </Col>
              <Col md={6}>
                <div className={styles.formField}>
                  <div className={styles.formHeader}>
                    <p>1. Shipping Address</p>
                  </div>
                  <div className={styles.formBody}>
                    <Form onSubmit={submitHandler}>
                      <Row className="mb-3 pt-5">
                        <Form.Group as={Col} controlId="firstName">
                          <Form.Control
                            required
                            name="firstName"
                            type="text"
                            onChange={handleChange}
                            placeholder="First Name"
                            value={formData.email}
                            className={styles.formControl}
                          />
                          <Form.Control.Feedback type="invalid">
                            Incorrect Name
                          </Form.Control.Feedback>
                        </Form.Group>

                        <Form.Group as={Col} controlId="lastName">
                          <Form.Control
                            required
                            name="lastName"
                            type="text"
                            onChange={handleChange}
                            placeholder="Last Name"
                            value={formData.email}
                            className={styles.formControl}
                          />
                          <Form.Control.Feedback type="invalid">
                            Incorrect Last Name
                          </Form.Control.Feedback>
                        </Form.Group>
                      </Row>
                      <Row className="mb-3">
                        <Form.Group as={Col} controlId="shippingAddress">
                          <Form.Control
                            required
                            name="shippingAddress"
                            type="text"
                            onChange={handleChange}
                            placeholder="Enter Street Address"
                            value={formData.email}
                            className={styles.formControl}
                          />
                          <Form.Control.Feedback type="invalid">
                            Incorrect Street Address
                          </Form.Control.Feedback>
                        </Form.Group>
                      </Row>
                      <Row className="mb-3">
                        <Form.Group as={Col} controlId="shippingCityName">
                          <Form.Control
                            required
                            name="shippingCityName"
                            type="text"
                            onChange={handleChange}
                            placeholder="Enter City"
                            value={formData.email}
                            className={styles.formControl}
                          />
                          <Form.Control.Feedback type="invalid">
                            Incorrect City
                          </Form.Control.Feedback>
                        </Form.Group>
                      </Row>
                      <Row className="mb-3">
                        <Form.Group as={Col} controlId="shippingState">
                          <Form.Control
                            required
                            name="shippingState"
                            type="text"
                            onChange={handleChange}
                            placeholder="Enter State"
                            value={formData.email}
                            className={styles.formControl}
                          />
                          <Form.Control.Feedback type="invalid">
                            Incorrect State
                          </Form.Control.Feedback>
                        </Form.Group>
                        <Form.Group as={Col} controlId="formGridFirstname">
                          <Form.Group as={Col} controlId="shippingZip">
                            <Form.Control
                              required
                              name="shippingZip"
                              type="text"
                              onChange={handleChange}
                              placeholder="Enter Zipcode"
                              value={formData.email}
                              className={styles.formControl}
                            />
                            <Form.Control.Feedback type="invalid">
                              Incorrect Zipcode
                            </Form.Control.Feedback>
                          </Form.Group>
                        </Form.Group>
                      </Row>
                      <Button type="submit" className={styles.button}>
                        SAVE AND CONTINUE
                      </Button>
                    </Form>
                  </div>
                </div>
                <div className={styles.formField}>
                  <div className={styles.formHeader}>
                    <p>2. Billing Address</p>
                  </div>
                  <div className={styles.formBody}>
                    <Form onSubmit={submitHandler}>
                      <Row className="mb-3 pt-5">
                        <Form.Group as={Col} controlId="billingFirstName">
                          <Form.Control
                            required
                            name="billingFirstName"
                            type="text"
                            onChange={handleChange}
                            placeholder="Billing First Name"
                            value={formData.email}
                            className={styles.formControl}
                          />
                          <Form.Control.Feedback type="invalid">
                            Incorrect Name
                          </Form.Control.Feedback>
                        </Form.Group>
                        <Form.Group as={Col} controlId="billingLastName">
                          <Form.Control
                            required
                            name="billingLastName"
                            type="text"
                            onChange={handleChange}
                            placeholder="Billing Last Name"
                            value={formData.email}
                            className={styles.formControl}
                          />
                          <Form.Control.Feedback type="invalid">
                            Incorrect Last Name
                          </Form.Control.Feedback>
                        </Form.Group>
                      </Row>
                      <Row className="mb-3">
                        <Form.Group as={Col} controlId="billingAddress">
                          <Form.Control
                            required
                            name="billingAddress"
                            type="text"
                            onChange={handleChange}
                            placeholder="Enter Street Address"
                            value={formData.email}
                            className={styles.formControl}
                          />
                          <Form.Control.Feedback type="invalid">
                            Incorrect Street Address
                          </Form.Control.Feedback>
                        </Form.Group>
                      </Row>
                      <Row className="mb-3">
                        <Form.Group as={Col} controlId="billingCityName">
                          <Form.Control
                            required
                            name="billingCityName"
                            type="text"
                            onChange={handleChange}
                            placeholder="Enter City"
                            value={formData.email}
                            className={styles.formControl}
                          />
                          <Form.Control.Feedback type="invalid">
                            Incorrect City
                          </Form.Control.Feedback>
                        </Form.Group>
                      </Row>
                      <Row className="mb-3">
                        <Form.Group as={Col} controlId="billingState">
                          <Form.Control
                            required
                            name="billingState"
                            type="text"
                            onChange={handleChange}
                            placeholder="Enter State"
                            value={formData.email}
                            className={styles.formControl}
                          />
                          <Form.Control.Feedback type="invalid">
                            Incorrect State
                          </Form.Control.Feedback>
                        </Form.Group>
                        <Form.Group as={Col} controlId="billingZip">
                          <Form.Control
                            required
                            name="billingZip"
                            type="text"
                            onChange={handleChange}
                            placeholder="Enter Zipcode"
                            value={formData.email}
                            className={styles.formControl}
                          />
                          <Form.Control.Feedback type="invalid">
                            Incorrect Zipcode
                          </Form.Control.Feedback>
                        </Form.Group>
                      </Row>
                      <Button type="submit" className={styles.button}>
                        SAVE AND CONTINUE
                      </Button>
                    </Form>
                  </div>
                </div>
                <div className={styles.formField}>
                  <div className={styles.formHeader}>
                    <p>3. Secure Payment</p>
                  </div>
                  <div className={styles.formBody}>
                    {/* <div key={`inline-radio`} className="mb-3">
                        <Form.Check
                          inline
                          className={styles.radioButton}
                          label={cc()}
                          name="group2"
                          type="radio"
                          id={`inline-radio-4`}
                        />
                        <Form.Check
                          inline
                          className={styles.radioButton}
                          label={pp()}
                          name="group2"
                          type="radio"
                          id={`inline-radio-5`}
                        />
                      </div>
                      <Button className={styles.button}>PAY NOW</Button> */}
                  </div>
                </div>
              </Col>
            </Row>
          </div>
        </Container>
      </main>
    </div>
  );
}
