import Head from "next/head";
import Link from "next/link";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row } from "react-bootstrap";
import Accordion from "react-bootstrap/Accordion";
import Image from "next/image";
import styles from "./styles.module.scss";
import { Check, PatchCheck } from "react-bootstrap-icons";
import { Card } from "react-bootstrap";
import { useAccordionButton } from "react-bootstrap/AccordionButton";
import { AccordionContext, Form } from "react-bootstrap";
export default function Terms() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - Terms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.termsPage}>
        <Container className={styles.container}>
          <h1>Terms and Conditions</h1>
          <p>
            Thank you for visiting the PureBlue website located at PureBlue.com
            (the “Site”). The Site is an Internet property of PureBlue, LLC
            (collectively, “PureBlue,” “we,” “our” or “us”). The following
            PureBlue Terms and Conditions (“Terms and Conditions”) are inclusive
            of the PureBlue Privacy Policy (“Privacy Policy”), the Consent to
            Telehealth, the Frequently Asked Questions (“FAQ”) and any and all
            other applicable operating rules, policies, price schedules and
            other supplemental terms and conditions or documents that may be
            published from time to time, which are expressly incorporated herein
            by reference (collectively, the “Agreement”).
            <br />
            <br /> Subject to your compliance with these Terms and Conditions,
            we hereby grant to you a personal, limited, revocable,
            non-exclusive, and nontransferable right to view, download, access,
            and use the Sites in the United States and to use the Services
            solely for your personal and non-commercial use and only as
            permitted under these Terms and Conditions, the Consent to
            Telehealth, and the Privacy Policy.
            <br />
            <br /> Each end-user visitor to the Site (“user,” “you” or “your”)
            agrees to the terms of the Agreement, in their entirety when she/he:
            (a) accesses or uses the Site; (b) accesses and/or downloads any of
            the: (i) blog posts, text, audio, video, photographs, graphics,
            artwork, testimonials and/or other content featured on the Site,
            including erectile dysfunction (“ED”) related content (collectively,
            “Informational Content”); and/or (ii) links to third party websites,
            products and/or services (“Third-Party Links,” and together with the
            Informational Content, the “Content”); (c) accesses certain product
            review sections, message boards, comments sections, customer ratings
            and other interactive features of the Site (collectively,
            “Interactive Services”); (d) registers to receive the PureBlue
            e-mail newsletter (“Newsletter”); (e) purchases any of the
            non-prescription items made available by and through the Site
            (collectively, the “PureBlue Products”) as provided by PureBlue; (f)
            purchases prescription medicines via the Site (“Prescription
            Medications,” and together with the PureBlue Products, the
            “Products”), as same are prescribed by certain third-party licensed
            medical doctors (“Healthcare Providers”) that provide
            telemedicine-related services in connection with the Site
            (“Telemedicine Services”); and/or (g) utilizes the various contact
            forms and/or contact information made available on the Site as a
            means to contact directly, or request to be contacted by, PureBlue
            (collectively, the “Contact Services,” and together with the Site,
            Content, Social Media Pages, PureBlue Products, Newsletter,
            Prescription Medications and Telemedicine Services, the “Site
            Offerings”).
            <br />
            <br /> Third-Party Links may not be under our control; therefore, we
            are not responsible for the information, products or services
            described thereon, or for the content of any Third-Party Links,
            including, without limitation, any link contained in a Third-Party
            Link, or any changes or updates to a Third-Party Link. We are
            providing these Third-Party Links to you only as a convenience, and
            the inclusion of any Third-Party Link does not necessarily imply
            endorsement of its content or any association with its operators.
            Your use of these Third-Party Links is at your own risk, and we are
            not liable to you in any way, either directly or indirectly, for any
            content, errors, damage or loss caused by or in connection with use
            of or reliance on information contained in or provided to or
            provided by Third-Party Links.
          </p>
          <br />
          <p className={styles.grayText}>
            PLEASE REVIEW THE TERMS OF THE AGREEMENT CAREFULLY. IF A USER DOES
            NOT AGREE WITH THE TERMS OF THE AGREEMENT IN THEIR ENTIRETY, THAT
            USER IS NOT AUTHORIZED TO USE THE SITE OFFERINGS IN ANY MANNER OR
            FORM.
            <br />
            <br /> NEW JERSEY STATE RESIDENTS ARE ENCOURAGED TO REVIEW THEIR
            RIGHTS UNDER THE AGREEMENT, AS PROVIDED UNDER THE NEW JERSEY
            TRUTH-IN-CONSUMER CONTRACT WARRANTY AND NOTICE ACT (“TCCWNA”).
          </p>
          <h2>Disclaimers</h2>
          <p>
            You expressly agree that use of the site is solely at your sole
            risk. You acknowledge and understand that the Content and PureBlue
            Products have not been evaluated by the US Food & Drug
            Administration (“FDA”). The Content, PureBlue Products and other
            material made available by and through the Site Offerings: (a) are
            not intended to diagnose, treat, cure or prevent any medical
            condition or disease; (b) are not in any way intended as medical
            advice or as a substitute for medical advice and/or medical
            treatment; and (c) should only be used in conjunction with the
            guidance and care of your physician. You further understand that the
            PureBlue Products and Prescription Medications are not intended for
            use by persons under eighteen (18) years of age. You understand and
            agree that some of the Content associated with the PureBlue Products
            and/or the efficacy of the PureBlue Products, is obtained from
            independent third-party sources, such as news agencies, scientific
            reports and/or scientific/research entities (collectively,
            “Third-Party Sources”). PureBlue does not warrant or represent that
            such Content is error-free, and PureBlue does not represent or
            endorse any Third-Party Sources or the methods that they use to
            arrive at their conclusions. All PureBlue Product specifications,
            performance data and other related information made available via
            the Site Offerings is for informational and illustrative purposes
            only, and do not constitute a guarantee or representation that the
            PureBlue Products will conform to such specifications or performance
            data. PureBlue does not warrant or represent that the PureBlue
            Products will provide you with any particular benefits, or that your
            results will match those of others who have used the PureBlue
            Products. Individual results will vary from person to person, and
            are dependent on factors including pre-existing medical conditions,
            age, weight, body chemistry, diet and exercise regimen.
            <br />
            <br /> You should always consult with your physician or other
            healthcare professional before utilizing any PureBlue Products,
            Prescription Medications and/or adopting any treatment for a health
            problem, whether featured by and through the Site Offerings or
            otherwise, especially if you suffer from any medical condition
            including, but not limited to, strokes, high blood pressure, heart,
            liver, kidney or thyroid disease, diabetes, skin diseases or
            ailments, anemia, depression, anxiety, have a family history of
            these or other mental or physical illnesses. Your physician should
            allow for proper follow-up visits and individualize your treatment
            plan as appropriate. If you have or suspect that you have a medical
            problem as a result of using any PureBlue Products, Prescription
            Medications and/or treatment for a health problem, promptly contact
            your health care provider. Never disregard professional medical
            advice or delay in seeking professional advice because of something
            that you have read on the Site or in connection with any other Site
            Offerings.
            <br />
            <br /> Without limiting the foregoing, those who are taking
            medication or are under treatment for any disease, or are pregnant
            or lactating, please consult with your physician or other health
            care professional before utilizing any PureBlue Products,
            Prescription Medications and/or adopting any treatment for a
            health-related problem. The PureBlue Products may include
            ingredients that you may be allergic to. You should always check the
            ingredients in any PureBlue Products and Prescription Medications to
            avoid potential allergic reactions. If you have, or suspect that you
            are experiencing, an allergic reaction or other adverse health
            event, promptly contact your health care provider.
          </p>
          <h2>1. Scope;</h2>
          <p>
            Modification of Agreement. The Agreement constitutes the entire and
            only agreement between users and PureBlue with respect to users’ use
            of the Site Offerings, and supersedes all prior or contemporaneous
            agreements, representations, warranties and/or understandings with
            respect to same. We may amend the Agreement from time to time in our
            sole discretion, without specific notice to you; provided, however,
            that: (a) any amendment or modification to the arbitration
            provisions, prohibition on class action provisions or any other
            provisions applicable to dispute resolution (collectively, “Dispute
            Resolution Provisions”) shall not apply to any disputes incurred
            prior to the applicable amendment or modification; and (b) any
            amendment or modification to pricing and/or billing provisions
            (“Billing Provisions”) shall not apply to any charges incurred prior
            to the applicable amendment or modification. The latest Agreement
            will be posted on the Site. We recommend that you read the Terms and
            Conditions each time you use the website. If you object to any
            changes, your sole recourse will be to cease using the web sites and
            our services. Your continued access to and use of the Websites or
            Services signifies your acknowledgement and acceptance of any such
            changes to these Terms and Conditions (other than with respect to
            disputes arising prior to the amendment or modification of the
            Dispute Resolution Provisions, or charges incurred prior to the
            amendment or modification of the Billing Provisions, which shall be
            governed by the Dispute Resolution Provisions and/or Billing
            Provisions then in effect at the time of the subject dispute or
            incurred charges, as applicable) and agreement to be bound thereby.
          </p>
          <h2>2. Requirements;</h2>
          <p>
            Eligibility to Access Site Offerings; Necessary Equipment. The Site
            Offerings are available only to individuals who: (i) are 18 years of
            age or older; (ii) are located in a State of the United States where
            we operate. For a list of states click here; (iii) consent to be
            legally bound by and comply with these Terms as posted and may be
            updated from time to time at our sole discretion; (iv) have
            compatible computing and/or mobile devices, access to the Internet,
            and certain necessary software in order to use the Platform. Any
            fees or charges incurred by your mobile service and Internet Service
            Provider in connection with your use of the Services are your sole
            responsibility.
            <br />
            <br /> You understand and agree that satisfying the above
            requirements does not guarantee that you will access the Site
            Offerings. To the extent permitted by applicable law, PureBlue may
            terminate your right to access the Site Offerings at any time where
            you: (i) are in any way in breach of the Agreement; (ii) are engaged
            in any improper conduct in connection with the Site Offerings;
            and/or (iii) are, at any time, conducting any unauthorized
            commercial activity by or through your use of the Site Offerings.
          </p>
          <h2>3. Registration Forms.</h2>
          <p>
            You may register to purchase Products and/or utilize certain Site
            Offerings, including the Contact Services. You must provide us with
            accurate and complete registration information and advise us
            promptly of any changes. Failure to do so will entitle us to
            immediately terminate your use of certain Site Offerings that
            require registration. The information you provide to us or the
            purposes of registration will be dealt with in accordance with our
            privacy policy.
          </p>
          <h2>4. Purchasing Products.</h2>
          <p>
            You can purchase, by and through the Site: (a) PureBlue Products by
            completing the applicable Form and providing the requisite
            Registration Data; and (b) Prescription Medication by completing the
            applicable Form, providing the requisite Registration Data,
            completing the Telemedicine Services process and receiving approval
            from a Healthcare Provider.
            <br />
            <br /> There is only one option for purchasing products by and
            through the site: (a) Automatic Renewal Program option. All
            automatic renewals can be managed in the account portal
            <br />
            <br />
            Automatic Renewal Program: Where you purchase Products in connection
            with an automatically renewing subscription model (“Automatic
            Renewal Program”), your Payment Method will be charged the
            applicable amount for the subject Products on a recurring basis for
            as long as that Automatic Renewal Program subscription remains
            active (the “Recurring Fees”). Such Recurring Fees will be charged
            in advance and you acknowledge and agree that PureBlue will not
            obtain any additional authorization from you for the applicable
            Automatic Renewal Program’s Recurring Fees. Every time that you
            accept delivery of the subject Products, you re-affirm that PureBlue
            is authorized to charge your Payment Method and to have the
            Recurring Fees applied to same. You may cancel a subscription at any
            time up to forty-eight (48) hours before the applicable renewal
            processing date of your subscription. If you wish to cancel an
            Automatic Renewal Program, you may do so at any time by: (i) signing
            in to your member portal here; (ii) calling us at: 1-866-453-6143;
            or (iii) e-mailing us at: info@trypureblue.com. Please be advised,
            all automatic renewal program subscription orders must be cancelled
            within (12) hours of the renewal subscription date to avoid the
            order being shipped and you incurring charges for same.
            <br />
            <br /> General Billing Terms: You must promptly notify us if your
            Payment Method is cancelled or is no longer valid (e.g., due to loss
            or theft) or your Product shipment may be delayed or cancelled.
            Changes to such information can be made by contacting a customer
            care professional at: 1-866-453-6143 or info@trypureblue.com. If you
            participate in an automatic shipment Recurring Fee program using a
            credit card and your credit card fails to process for a subsequent
            shipment, you agree that PureBlue may contact you on any phone
            number (including a cell phone number) or e-mail address provided by
            you for alternate payment information. If you fail to pay for any
            product or service received, your account may be sent to collection.
            UNLESS OTHERWISE INDICATED, ALL SALES ARE FINAL AND NON-REFUNDABLE.
            The fees associated with your purchases will appear on your Payment
            Method statement through the identifiers “PureBlue”. All prices
            displayed on the Site are quoted in U.S. Dollars, are payable in
            U.S. Dollars and are valid and effective only in the United States.
            Failure to use the Products does not constitute a basis for refusing
            to pay any of the associated charges. Subject to the conditions set
            forth herein, you agree to be bound by the Billing Provisions of
            PureBlue in effect at any given time. Upon reasonable prior notice
            to you (with Site-updates and/or e-mail sufficing), PureBlue
            reserves the right to change its Billing Provisions whenever
            necessary, in its sole discretion. Continued use of the Site and/or
            purchase of Products after receipt of such notice shall constitute
            consent to any and all such changes; provided, however, that any
            amendment or modification to the Billing Provisions shall not apply
            to any charges incurred prior to the applicable amendment or
            modification.
            <br />
            <br /> Restrictions: You agree that any Products you purchase from
            PureBlue will be used for your personal, non-commercial use. You
            agree that you will not re-sell, re-distribute, or export any
            Product that you order from PureBlue. PureBlue does not accept
            orders from dealers, wholesalers, or customers who are resellers or
            who intend to resell Products offered on the Site. If PureBlue
            discovers that you are placing orders with the intent to resell
            Products offered on the Site, we will immediately cancel your order,
            suspend or terminate your account and, at our option, pursue any and
            all available legal remedies under applicable law. To the extent
            that your conduct may be fraudulent, such as attempting to purchase
            or purchasing Products through the use of fake or stolen cards,
            PureBlue will report you to federal, state and/or local enforcement
            authorities and take any additional legal action deemed appropriate
            by PureBlue.
          </p>
          <br />
          <br />
          <h2>5. Products.</h2>
          <p>
            All Products purchased from PureBlue remain, at all times, subject
            to the disclaimers contained herein and on the Site. Prices for
            Products are subject to change at any time. All Products offered by
            PureBlue are subject to availability and PureBlue reserves the right
            to reject all or any part of an order without prior notice. You will
            be notified if any of the Products in your order are no longer
            available or if all or any part of your order is cancelled. PureBlue
            will refund any amount already paid on ordered Products that are no
            longer available or any cancelled part of any order.
          </p>
          <h2>6. Return and Refund Policy.</h2>
          <p>
            If you wish to return PureBlue Products, you may contact a customer
            care professional at: 1-866-453-6143. Prescription Medications can
            not be returned or refunded.
          </p>
          <h2>7. Telemedicine Services.</h2>
          <p>
            Telemedicine involves the delivery of health care services using
            electronic communications, information technology, or other means
            between a health care provider and a patient who are not in the same
            physical location. Telemedicine may be used for diagnosis,
            treatment, follow-up and/or related patient education, and may
            include, but is not limited to: (i) Electronic transmission of
            medical records, photo images, personal health information, or other
            data between a patient and health care provider; (ii) Interactions
            between a patient and health care provider via audio, video, and/or
            data communications; and (iii) Use of output data from medical
            devices, sound, and video files.
            <br />
            <br /> Where you request Prescription Medication, you must complete
            the medical intake Form. Upon completion of same, PureBlue will
            submit same to a participating Healthcare Provider who will perform
            the requisite Telemedicine Services to determine your suitability
            for Prescription Medication before prescribing same.
            <br />
            <br /> You should always consult with your physician or other
            healthcare professional before utilizing any Prescription
            Medications and/or adopting any treatment for a health problem
            recommended by and through the Telemedicine Services.
            <br />
            <br /> Your physician should allow for proper follow-up visits and
            individualize your treatment plan as appropriate. Never disregard
            professional medical advice or delay in seeking professional advice
            because of something that you have read on the Site or in connection
            with any Telemedicine Services.
            <br />
            <br /> Please be advised that PureBlue does not itself offer the
            Telemedicine Services made available via the Site Offerings, nor can
            PureBlue issue a prescription for the Prescription Medication. The
            ultimate terms and conditions of any such prescription made
            available via the Telemedicine Services will be determined by the
            applicable Healthcare Provider(s). You understand and agree that
            PureBlue shall not be liable to you or any third party for any
            medical services and/or medications offered by any Healthcare
            Provider(s) by and/or through the Telemedicine Services.
            <br />
            <br /> Please see our Consent to Telehealth for a description of the
            risks and benefits of telemedicine. The Consent to Telehealth is
            hereby incorporated into these Terms of Use by reference and
            constitutes a part of these Terms of Use.
          </p>
          <h2>8. Content.</h2>
          <p>
            The Site contains Content which includes, but is not limited to,
            product reviews, text, audio, video, photographs, graphics, artwork,
            testimonials and other information about PureBlue and/or the
            PureBlue Products. The Content is compiled, distributed and
            displayed by PureBlue, as well as third-party content providers,
            such as Third-Party Sources and other Site users (collectively,
            “Third-Party Providers”). PureBlue does not control and is not
            responsible for the completeness, accuracy, appropriateness and/or
            usefulness of the Content provided by Third-Party Providers that is
            made available by and through the Site Offerings. Such Third-Party
            Content should not necessarily be relied upon. Reliance on any
            Content or other information made available to you by and through
            the Site Offerings is solely at your own risk. PureBlue does not
            represent or warrant that the Content and other information posted
            by and through the Site Offerings is accurate, complete, up-to-date
            or appropriate. You understand and agree that PureBlue will not be
            responsible for, and undertakes no responsibility to monitor or
            otherwise police Content provided by Third-Party Providers. You may
            find certain Content to be outdated, harmful, inaccurate and/or
            deceptive. You agree that PureBlue shall have no obligation and
            incur no liability to you in connection with any Content. Please use
            caution, common sense and safety when using the Content. The Content
            is offered for informational purposes only and is at all times
            subject to the disclaimers contained herein and on the Site.
          </p>
          <h2>9. License and Restrictions to User Content.</h2>
          <p>
            PureBlue may, in PureBlue sole discretion, permit you from time to
            time to submit, upload, publish or otherwise make available to
            PureBlue through the Interactive Services textual, audio, and/or
            visual content and information, including commentary and feedback
            related to the Services, initiation of vehicle repair quote
            requests, and submission of entries for competitions and promotions
            ("User Content"). Any User Content provided by you remains your
            property. However, by providing User Content to PureBlue, you grant
            PureBlue a worldwide, perpetual, irrevocable, transferrable,
            royalty-free license, with the right to sublicense, use, copy,
            modify, create derivative works of, distribute, publicly display,
            publicly perform, and otherwise exploit in any manner such User
            Content in all formats and distribution channels now known or
            hereafter devised (including in connection with the Interactive
            Services and PureBlue business and on third-party sites and
            services), without further notice to or consent from you, and
            without the requirement of payment to you or any other person or
            entity. You represent and warrant that: (i) you either are the sole
            and exclusive owner of all User Content or you have all rights,
            licenses, consents and releases necessary to grant PureBlue the
            license to the User Content as set forth above; and (ii) neither the
            User Content nor your submission, uploading, publishing or otherwise
            making available of such User Content nor PureBlue use of the User
            Content as permitted herein will infringe, misappropriate or violate
            a third party's intellectual property or proprietary rights, or
            rights of publicity or privacy, or result in the violation of any
            applicable law or regulation. You agree to not provide User Content
            that is defamatory, libelous, hateful, violent, obscene,
            pornographic, unlawful, or otherwise offensive, as determined by
            PureBlue in its sole discretion, whether or not such material may be
            protected by law. PureBlue may, but shall not be obligated to,
            review, monitor, or remove User Content, at PureBlue sole discretion
            and at any time and for any reason, without notice to you.
            <br />
            <br /> PureBlue reserves the right to take whatever lawful actions
            it may deem appropriate in response to actual or suspected
            violations of the foregoing, including, without limitation, the
            suspension or termination of a User's access and/or account.
            PureBlue may cooperate with legal authorities and/or third parties
            in the investigation of any suspected or alleged crime or civil
            wrong.
            <br />
            <br />
            Except as may be provided in the Privacy Policy or prohibited by
            applicable law, PureBlue reserves the right at all times to disclose
            any information as PureBlue deems necessary to satisfy any
            applicable law, regulation, legal process or governmental request,
            or to edit, refuse to post or to remove any information or
            materials, in whole or in part, in PureBlue’s sole discretion.
          </p>
          <h2>10. Protected Health Information.</h2>
          <p>
            When you set up an account with PureBlue, you are creating a direct
            customer relationship with PureBlue that enables you to access
            and/or utilize the various functions of the Site Offerings as a
            user. As part of that relationship, you may provide certain personal
            information to PureBlue that we do not consider to be “protected
            health information” or “medical information,” such as your name,
            email address, mailing/billing address and telephone number.
            <br />
            <br />
            However, where you request Prescription Medications or otherwise
            request certain PureBlue Products, you may also provide certain
            health or medical information that may be protected under applicable
            laws, rules and regulations, such the Health Insurance Portability
            and Accountability Act of 1996, Public Law 104-191, and its related
            regulations and amendments (collectively, “HIPAA”). PureBlue is not
            considered a “covered entity” under HIPAA; provided, however, that
            our Healthcare Providers are “covered entities” under HIPAA and, in
            connection therewith, PureBlue may, in some cases, be a “business
            associate” of the Healthcare Providers. It is important to note that
            HIPAA does not necessarily apply to an entity or person simply
            because there is health information involved, and HIPAA may not
            apply to all of your transactions or communications with PureBlue.
            To the extent PureBlue is deemed a “business associate” however, and
            solely in its role as a business associate, PureBlue may be subject
            to certain provisions of HIPAA with respect to “protected health
            information,” as defined under HIPAA, that you provide to the
            Healthcare Providers (“PHI”). In addition, any medical or health
            information that you provide that is subject to specific protections
            under applicable state laws (collectively, with PHI, “Protected
            Information”), will be used and disclosed only in accordance with
            such applicable laws. However, any information that does not
            constitute Protected Information under applicable laws may be used
            or disclosed in any manner permitted under this Privacy Policy.
            Protected Information does not include information that has been
            de-identified in accordance with applicable laws.
          </p>
          <h2>11. Representations and Warranties.</h2>
          <p>
            Each user hereby represents and warrants to PureBlue as follows: (a)
            all information user provides at all times in connection with user’s
            use of the Site Offerings, and in communications with Healthcare
            Providers, is true, accurate, current and complete, and user agrees
            to maintain and promptly update such information to keep it true,
            accurate, current and complete as long as user is using the Site
            Offerings; (b) where user purchases or attempts to purchase
            Products, that user is doing so for her/his own personal use, and
            with no intent to resell such Products; (c) the Agreement
            constitutes the legal, valid and binding obligation of user, which
            is fully enforceable against such user in accordance with its terms;
            (d) user understands and agrees that user has independently
            evaluated the desirability of utilizing the Site Offerings and that
            user has not relied on any representation and/or warranty other than
            those set forth in the Agreement; and (e) the execution, delivery
            and performance of the Agreement by user will not conflict with or
            violate: (i) any applicable law; (ii) any order, judgment or decree
            applicable to user; and/or (iii) any agreement or other instrument
            applicable to user.
          </p>
          <h2>12. Indemnification.</h2>
          <p>
            Each user agrees to indemnify, hold harmless and promptly defend
            PureBlue and, if applicable, its shareholders, directors, officers,
            employees and agents, from and against any action, cause, claim,
            damage, debt, demand or liability, including, without limitation,
            costs and attorneys’ fees, asserted by any person, arising out of or
            relating to: (a) User’s breach of this Agreement; (b) User’s use of
            the Site Offerings, including, without limitation, any data or work
            transmitted or received by User; (c) User’s dispute with any
            Healthcare Provider(s) and/or other third party(ies) and/or (d) any
            unacceptable, unauthorized and/or improper use of the Site
            Offerings. The provisions of this Section 12 are for the benefit of
            PureBlue, its parent, subsidiaries and/or affiliates, and each of
            their respective officers, directors, members, employees, agents,
            shareholders, licensors, suppliers and/or attorneys. Each of these
            individuals and entities shall have the right to assert and enforce
            these provisions directly against users on its own behalf.
          </p>
          <h2>13. Proprietary Rights.</h2>
          <p>
            PureBlue has the exclusive right, title, and interest in the Site
            Offerings, including the information, graphics, design, compilation,
            magnetic translation, digital conversion, software,documentation,
            marks, business processes, know-how, service names and other matters
            related to same, (Collectively, Proprietary Content). The “PureBlue”
            name and logo, and all associated graphics, icons and service names,
            are intellectual property of PureBlue the use of any trademark
            without the applicable trademark owner's express written consent is
            strictly prohibited. No User shall copy, recompile, disassemble,
            reverse engineer, make or distribute any other form of, or create
            derivative works from, the Proprietary Content without prior written
            consent. All Proprietary Content is protected under United States
            and foreign laws, whether owned by PureBlue or third parties with
            whom we associate to deliver the Site Offerings. The posting of
            information or material by and through the Site Offerings does not
            constitute a waiver of any right in or to such information and/or
            materials.
          </p>
          <h2>14. Legal Warning.</h2>
          <p>
            You must exercise caution and sound judgment in using the Site
            Offerings. You are prohibited from any attempt to damage, destroy,
            tamper with, vandalize and/or otherwise interfere with the operation
            of the Site Offerings. Any such attempt is a violation of criminal
            and civil law and PureBlue will diligently pursue any and all
            remedies against any offending individual or entity to the fullest
            extent permissible by law and in equity.
          </p>
          <h2>15. Disclaimer of Warranties.</h2>
          <p>
            THE SITE OFFERINGS AND THE OTHER PRODUCTS AND SERVICES OFFERED BY
            AND THROUGH SAME ARE PROVIDED TO USERS ON AN “AS IS” AND “AS
            AVAILABLE” BASIS. ANY ACCESS TO OR USE OF THE SITE OFFERINGS IS
            VOLUNTARY AND AT THE SOLE RISK OF THE USER. PUREBLUE AND EACH
            THIRD-PARTY OFFERING PRODUCTS OR SERVICES THROUGH THE SERVICE, TO
            THE FULLEST EXTENT PERMITTED BY LAW, MAKES NO REPRESENTATIONS OR
            WARRANTIES OF ANY NATURE, EXPRESS OR IMPLIED, STATUTORY OR
            OTHERWISE, IN CONNECTION WITH THIS AGREEMENT, THE SITE OFFERINGS AND
            THE PRODUCTS AND SERVICES OFFERED BY AND THROUGH SAME OR ANY OTHER
            MATTER, INCLUDING WITHOUT LIMITATION ALL WARRANTIES OF
            MERCHANTABILITY, TITLE AND FITNESS FOR A PARTICULAR PURPOSE.
            PUREBLUE DOES NOT WARRANT OR GUARANTEE THAT THE USE OF THE SITE
            OFFERINGS WILL RESULT IN ANY SPECIFIC MEDICAL BENEFIT OR OTHER
            HEALTH-RELATED OUTCOME. PUREBLUE DOES NOT WARRANT OR GUARANTEE THAT
            THE SITE OFFERINGS AND THE OTHER PRODUCTS AND SERVICES OFFERED BY
            AND THROUGH SAME WILL BE WITHOUT ERRORS, DISRUPTIONS, DELAYS,
            DEFECTS, INTERFERENCES, IMPERFECTIONS, CYBER ATTACK, MALWARE OR
            OTHER ADVERSE INCIDENT.: NO ADVICE OR INFORMATION, WHETHER ORAL OR
            WRITTEN, OBTAINED BY ANY USER FROM PUREBLUE OR OTHERWISE THROUGH OR
            FROM THE SITE OFFERINGS SHALL CREATE ANY WARRANTY NOT EXPRESSLY
            STATED IN THE AGREEMENT.
          </p>
          <h2>16. Limitation of Liability.</h2>
          <p>
            EACH USER EXPRESSLY ACKNOWLEDGES AND AGREES THAT PUREBLUE SHALL NOT
            BE LIABLE, IN CONTRACT, TORT (INCLUDING, WITHOUT LIMITATION,
            NEGLIGENCE), PRE-CONTRACT OR OTHER REPRESENTATIONS (OTHER THAN
            FRAUDULENT MISREPRESENTATIONS) OR OTHERWISE OUT OF OR IN CONNECTION
            WITH THE SITE OFFERINGS FOR ANY DIRECT, INDIRECT, INCIDENTAL,
            SPECIAL, CONSEQUENTIAL AND/OR EXEMPLARY DAMAGES INCLUDING, BUT NOT
            LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR
            OTHER INTANGIBLE LOSSES, IN ANY CASE, WHETHER OR NOT SUCH LOSSES OR
            DAMAGES WERE WITHIN THE CONTEMPLATION OF PUREBLUE AT THE DATE ON
            WHICH THE EVENT GIVING RISE TO THE LOSS OCCURRED,, THIS LIMITATION
            APPLIES TO ALL CAUSES OF ACTION, IN THE AGGREGATE INCLUDING, BUT NOT
            LIMITED TO, BREACH OF CONTRACT, BREACH OF WARRANTY, NEGLIGENCE,
            STRICT LIABILITY, MISREPRESENTATION AND ANY AND ALL OTHER TORTS.
            EACH USER HEREBY RELEASES PUREBLUE FROM ANY AND ALL OBLIGATIONS,
            LIABILITIES AND CLAIMS IN EXCESS OF THE LIMITATIONS STATED HEREIN.
            IN NO EVENT SHALL PUREBLUE TOTAL LIABILITY TO ANY USER FOR ALL LOSS,
            COST, DAMAGE, LIABILITY OR EXPENSE (INCLUDING ATTORNEYS FEES AND
            COSTS) THAT THE USER MAY SUFFER OR INCUR, UNDER ANY THEORY OF
            LIABILITY, IN CONTRACT, TORT (INCLUDING, BUT NOT LIMITED TO,
            NEGLIGENCE), OR OTHERWISE, EXCEED THE LESSER OF THE AMOUNT PAID BY
            THE USER, IF ANY, FOR THE RIGHT TO ACCESS OR PARTICIPATE IN ANY
            ACTIVITY RELATED TO THE SITE OFFERINGS OR FIVE HUNDRED DOLLARS
            ($500.00). ANY CLAIMS ARISING OUT OF THE USE OF THE SITE OFFERINGS
            AND THE OTHER PRODUCTS AND SERVICES OFFERED BY AND THROUGH SAME,
            MUST BE BROUGHT BY ANY USER OR PUREBLUE WITHIN ONE (1) YEAR OF THE
            DATE OF THE EVENT WHICH GAVE RISE TO THE CAUSE OF ACTION. THE
            NEGATION OF DAMAGES SET FORTH ABOVE IS A FUNDAMENTAL ELEMENT OF THE
            BASIS OF THE BARGAIN BETWEEN EACH USER AND PUREBLUE. ACCESS TO THE
            SITE OFFERINGS WOULD NOT BE PROVIDED TO USERS WITHOUT SUCH
            LIMITATIONS. SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS ON
            LIABILITY AND IN SUCH JURISDICTIONS THE LIABILITY OF PUREBLUE SHALL
            BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.
          </p>
          <h2>17. Copyright Policy/DMCA Compliance Procedure.</h2>
          <p>
            PureBlue reserves the right to terminate the account of any user who
            infringes upon third-party copyrights or to remove any content or
            any other material or information available on or through the Site,
            at any time, for any reason. PureBlue otherwise complies with the
            provisions of the Digital Millennium Copyright Act (“DMCA”)
            applicable to Internet service providers (17 U.S.C. § 512, as
            amended), and responds to clear notices of alleged copyright
            infringement. This Section describes the procedure that should be
            followed to file a notification of alleged copyright infringement
            with PureBlue. If you have objections to copyrighted content or
            material made available on or through our the, you may submit a
            notification to our Designated Agent. Any notification to PureBlue
            under 17 U.S.C. § 512(c) alleging copyright infringement must
            include the following information: (a) an electronic or physical
            signature of the person authorized to act on behalf of the owner of
            the copyrighted work; (b) an identification and location of the
            copyrighted work that such party claims has been infringed upon; (c)
            a written statement by such party that it has a good faith belief
            that the disputed use is not authorized by the owner, its agent or
            the law; (d) such party’s name and contact information, such as
            telephone number or e-mail address; and (e) a statement by such
            party that the above information in such party’s notice is accurate
            and, under penalty of perjury, that such party is the copyright
            owner or authorized to act on the copyright owner’s behalf. Contact
            us at for information or notice of claims.
          </p>
          <h2>18. Editing, Deleting and Modification.</h2>
          <p>
            PureBlue reserves the right, in its sole discretion, to edit and/or
            delete any documents, information or Content appearing on the Site.
          </p>
          <h2>19. Use of Registration Data.</h2>
          <p>
            All material submitted by users through or in association with the
            Site Offerings including, without limitation, the Registration Data,
            shall be subject to the Privacy Policy.
          </p>
          <h2>20. Governing Law.</h2>
          <p>
            The Agreement shall be treated as though it were executed and
            performed in New York, NY and shall be governed by and construed in
            accordance with the laws of the State of New York (without regard to
            conflict of law principles).
          </p>
          <h2>21. Dispute Resolution and Arbitration.</h2>
          <p>
            The parties hereby agree to arbitrate all claims that may arise
            under the Agreement. Without limiting the foregoing, should a
            dispute arise between the parties (including the Covered Parties)
            including, without limitation, any matter concerning the Site
            Offerings, the terms and conditions of the Agreement or the breach
            of same by any party hereto: (a) the parties agree to submit their
            dispute for resolution by arbitration before the American
            Arbitration Association (“AAA”) in New York, NY, in accordance with
            the then current Commercial Arbitration rules of the AAA; and (b)
            you agree to first commence a formal dispute proceeding by
            submitting a written description of the dispute, which shall include
            all relevant documents and information, and the proposed resolution.
            You may send the written description of any dispute you have with us
            by US Mail to PureBlue,
            <br />
            <br /> Attention: Customer Service Department -<br />
            42 Broadway, 12th Floor
            <br /> New York, NY 10004
            <br />
            <br /> PureBlue will contact you by letter at the billing address
            you provided to us or at the e-mail address you provided to us. You
            agree to negotiate with PureBlue, or its designated representative
            in good faith about your problem or dispute. We may choose to
            provide you with a final written settlement offer after receiving
            your initial written description of the dispute (“Final Settlement
            Offer”). If we provide you with a Final Settlement Offer and you do
            not accept it, or we cannot otherwise satisfactorily resolve your
            dispute and you wish to proceed, you may give us notice of your
            intention to proceed to arbitration and commence arbitration
            proceedings with the AAA, in your county of residence. For claims of
            Ten Thousand Dollars ($10,000.00) or less, you can choose whether
            the arbitration proceeds in person, by telephone or based only on
            submissions. If the arbitrator awards you relief that is greater
            than our Final Settlement Offer, then we will pay all filing,
            administration and arbitrator fees associated with the arbitration
            and, if you retained an attorney to represent you in connection with
            the arbitration, we will reimburse any reasonable attorneys' fees
            that your attorney accrued for investigating, preparing and pursuing
            the claim in arbitration. Any award rendered shall be final and
            conclusive to the parties and a judgment thereon may be entered in
            any court of competent jurisdiction. Although we may have a right to
            an award of attorneys' fees and expenses if we prevail in
            arbitration, we will not seek such an award from you unless the
            arbitrator determines that your claim was frivolous.
            <br />
            <br /> To the extent permitted by law, you agree that you will not
            bring, join or participate in any class action lawsuit as to any
            claim, dispute or controversy that you may have against the Covered
            Parties and/or their respective employees, officers, directors,
            members, representatives and/or assigns. You agree to the entry of
            injunctive relief to stop such a lawsuit or to remove you as a
            participant in the suit. You agree to pay the attorney's fees and
            court costs that any Covered Party incurs in seeking such relief.
            This provision preventing you from bringing, joining or
            participating in class action lawsuits: (i) does not constitute a
            waiver of any of your rights or remedies to pursue a claim
            individually and not as a class action in binding arbitration as
            provided above; and (ii) is an independent agreement. You may
            opt-out of these dispute resolution provisions by providing written
            notice of your decision within thirty (30) days of the date that you
            first access the Site.
          </p>
          <h2>22. California User Consumer Rights.</h2>
          <p>
            In accordance with Cal. Civ. Code Sec. 1789.3, California State
            resident Users may file grievances and complaints with the
            California Department of Consumer Affairs, 400 R Street, Ste. 1080,
            Sacramento, CA 95814; or by phone at 916-445-1254 or 800-952-5210;
            or by email to dca@dca.ca.gov.
          </p>
          <h2>23. California Proposition 65 Warnings.</h2>
          <p>
            Proposition 65, officially the Safe Drinking Water and Toxic
            Enforcement Act of 1986, is a law that requires warnings be provided
            to California consumers when they might be exposed to chemicals
            identified by California lawmakers as causing cancer or reproductive
            toxicity. The warnings are intended to help California State
            consumers make informed decisions about their exposures to these
            chemicals from the products they use. The California Office of
            Environmental Health Hazard Assessment (“OEHHA”) administers the
            Proposition 65 program and publishes the listed chemicals, which
            includes more than 850 chemicals. In August 2016, OEHHA adopted new
            regulations, effective on August 30, 2018, which change the
            information required in Proposition 65 warnings. We are providing
            the following warning for products linked to this page:
            <br />
            <br /> WARNING: Bisphenol A (BPA): Product containers may have
            linings containing bisphenol A (BPA), a chemical known to the State
            of California to cause harm to the female reproductive system. Jar
            lids and bottle caps may also contain BPA. You can be exposed to BPA
            when you ingest Products packaged in these containers. For more
            information go to: www.P65Warnings.ca.gov/BPA.
            <br />
            <br /> Additional Information about Proposition 65
            <br />
            <br /> For background on the new Proposition 65 warnings, see
            https://www.p65warnings.ca.gov/new-proposition-65-warnings.
            Proposition 65 and its regulations are posted at
            https://oehha.ca.gov/proposition-65/law/proposition-65-law-and-regulations.
          </p>
          <h2>24. Precedence.</h2>
          <p>
            To the extent that anything in or associated with the Site Offerings
            is in conflict or inconsistent with the Agreement, the Agreement
            shall take precedence. PureBlue failure to enforce any provision of
            the Agreement shall not be deemed a waiver of such provision nor of
            the right to enforce such provision.
          </p>
          <h2>25. No Agency Created.</h2>
          <p>
            Nothing contained in this Agreement shall give either party the
            right to bind the other or be deemed to constitute either party as
            agent for or partner of the other.
          </p>
          <h2>26. Assignment.</h2>
          <p>
            PureBlue may assign its rights and obligations under the Agreement,
            in whole or in part, to any party at any time without notice to
            user. The Agreement is not assignable by you, and you may not
            delegate your duties under it.
          </p>
          <h2>27. Severability.</h2>
          <p>
            In the event that any provision of this Agreement is found to be
            void and unenforceable by a court of competent jurisdiction, then
            such unenforceable provision shall be deemed modified so as to be
            enforceable (or if not subject to modification, then eliminated
            herefrom) to the extent necessary to permit the remaining provisions
            to remain in full force and effect.
          </p>
          <h2>28. Doctor and Pharmacy Information.</h2>
          <p>
            Marc Serota, M.D; CEO MD Integrations; Board certified: Dermatology,
            Allergy/Immunology, Pediatrics; 816-679-2211 (Cell);
            mj.serota@gmail.com (Email).
            <br />
            <br />
            Cole Maudlin, Chief Executive Officer; GenRx Pharmacy; 17250 N
            Hartford Dr Ste 115, Scottsdale, AZ 85255; d.maduri@gogomeds.com
            (email); 1-866-453-6143 (office)
          </p>
          <h2>29. Contact Us.</h2>
          <p>
            If you have any questions about the Agreement, Site Offerings or the
            practices of PureBlue, you may utilize the contact method applicable
            to the subject matter of your inquiry, as set forth on the “Contact
            Us” page of the Site, or you can e-mail us at: info@trypureblue.com;
            call us at: 1-866-453-6143; or send us U.S. mail to:
            <br /> PureBlue (d/b/a PureBlue),
            <br /> 42 Broadway, 12th Floor
            <br /> New York, NY 10004
            <br />
            <br /> MD Integrations
            <br /> 9071 E Mississippi Ave, Unit 6C, Denver, CO 80247
            <br /> Dr. Andrew Sakla Licenses
          </p>
          <br />
          <br />
          <div className={styles.grayField}>
            <h3>Our Clinicians</h3>
            <br />
            <Row>
              <Col md={6}>
                <p>
                  Alabama - AL DO.2327 12/31/2023 <br />
                  Alaska - AK 160520 12/31/2024
                  <br />
                  Arizona - AZ 8699 12/31/2024
                  <br />
                  Arkansas - AR E-13340 10/31/2023
                  <br />
                  California - CA 18058 10/31/2023
                  <br />
                  Colorado - CO DR.0063114 4/30/2023
                  <br />
                  Connecticut - CT 66855 10/31/2023
                  <br />
                  Delaware - DE C2-0023917 3/31/2023
                  <br />
                  Florida - FL OS12612 3/31/2024
                  <br />
                  Georgia - GA 78730 10/31/2024
                  <br />
                  Hawaii - HI DOS-2214 6/30/2024
                  <br />
                  Idaho - ID O-1465 6/30/2024
                  <br />
                  Illinois - IL 36.148872 7/31/2023
                  <br />
                  Indiana - IN 02006145A 10/31/2023
                  <br />
                  Iowa - IA DO-05075 10/1/2024
                  <br />
                  Kansas - KS 05-43760 10/31/2023
                  <br />
                  Kentucky - KY 4809 2/28/2023
                  <br />
                  Louisiana - LA 324077 10/31/2023
                  <br />
                  Maine - ME DO3113 10/31/2024
                  <br />
                  Maryland - MD H0088559 9/30/2023
                  <br />
                  Massachusetts - MA 285750 10/20/2024
                  <br />
                  Michigan - MI 5101025238 10/1/2025
                  <br />
                  Minnesota - MN TM 2634 12/31/2023
                  <br />
                  Mississippi - MS 29513 6/30/2023
                  <br />
                  Missouri - MO 2020022922 1/31/2024
                  <br />
                  Montana - MT MED-PHYS-LIC-100712 3/31/2023
                  <br />
                  Nebraska - NE 2238 10/1/2024
                  <br />
                  Nevada - NV DO3035 12/31/2023
                  <br />
                  New Hampshire - NH 22026 6/30/2023
                </p>
              </Col>
              <Col md={6}>
                <p>
                  New Jersey - NJ 25MB10941200 6/30/2023
                  <br />
                  New Mexico - NM TM2022-0975 7/1/2025
                  <br />
                  New York - NY 297988 9/30/2024
                  <br />
                  North Carolina - NC 2019-02671 10/20/2023
                  <br />
                  North Dakota - ND 17208 10/20/2023
                  <br />
                  Ohio - OH 34.014602 6/11/2024
                  <br />
                  Oklahoma - OK 7062 6/30/2023
                  <br />
                  Oregon - OR DO198547 12/31/2023
                  <br />
                  Pennsylvania - PA OS020431 10/31/2024
                  <br />
                  Rhode Island - RI DO01057 6/30/2024
                  <br />
                  South Carolina - SC MDO.82979 6/30/2023
                  <br />
                  South Dakota - SD 12999 3/1/2023
                  <br />
                  Tennessee - TN 3331 10/31/2024
                  <br />
                  Texas - TX S1698 5/31/2024
                  <br />
                  Utah - UT 10385749-1204 5/31/2024
                  <br />
                  Vermont - VT 32.0133963 9/30/2024
                  <br />
                  Virginia - VA 102206300 10/31/2024
                  <br />
                  Washington - WA OP61055072 10/20/2023
                  <br />
                  West Virginia - WV 3750 6/30/2023
                  <br />
                  Wisconsin - WI 72103-21 10/31/2023
                  <br />
                  Wyoming - WY 14047A 6/30/2023
                  <br />
                  District of Columbia - DC DO034895 12/31/2024
                  <br />
                </p>
              </Col>
            </Row>
            <br />
            <br />
            <p>
              If you are from any of the following states you will be required
              to have a video consultation. The states that do not provide
              asynchronous tele-medicine are as follows.
              <br />
              <br /> NH, DE, LA, NJ, NM, WV and ID
            </p>
          </div>
        </Container>
      </main>
    </div>
  );
}
