import Head from "next/head";
import Link from "next/link";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row } from "react-bootstrap";
import Accordion from "react-bootstrap/Accordion";
import Image from "next/image";
import styles from "./styles.module.scss";
import { Check, PatchCheck } from "react-bootstrap-icons";
import { Card } from "react-bootstrap";
import { useAccordionButton } from "react-bootstrap/AccordionButton";
import { AccordionContext, Form } from "react-bootstrap";
export default function TreatmentPlanSildenafilTadalafil() {
  function ContextAwareToggle({ children, eventKey, callback }) {
    const { activeEventKey } = useContext(AccordionContext);
    const decoratedOnClick = useAccordionButton(
      eventKey,
      () => callback && callback(eventKey)
    );

    const isCurrentEventKey = activeEventKey === eventKey;

    return (
      <button
        type="button"
        className="headerOne"
        style={{
          backgroundColor: isCurrentEventKey ? "#fff" : "#fff",
          border: "0px",
          color: "#000",
          fontWeight: "800",
          padding: "0px 12px 0px 12px",
          width: "100%",
          textAlign: "left",
        }}
        onClick={decoratedOnClick}
      >
        {children}
      </button>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pure Blue - Treatment Plan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconn.ico" />
      </Head>
      <main className={styles.treatmentPage}>
        <Container>
          <h1 className={styles.h1}>
            SILDENAFIL AND TADALAFIL: <br />
            TREATMENT PLAN
          </h1>
          <p className={styles.gray}>ERECTILE DYSFUNCTION ("ED") MEDICATIONS</p>
          <div className={styles.line}></div>
          <h4>
            BELOW IS A KEY GUIDE TO HELP YOU UNDERSTAND THE POTENTIAL RISKS AND
            BENEFITS OF SILDENAFIL OR TADALAFIL TO TREAT ERECTILE DYSFUNCTION
            (ED). PLEASE THOROUGHLY REVIEW THE PACKAGE INSERT THAT COMES WITH
            YOUR MEDICATION AND COMMUNICATE HONESTLY WITH YOUR PROVIDER ABOUT
            ANY CONCERNS.
          </h4>
          <p>
            You must contact the provider if there are any problems, changes or
            side effects. Or, if you visit a new provider for treatment. ED may
            indicate that there are other health issues that should be
            addressed, which is why we recommend routine testing of labs, and
            regular visits with your primary care provider. Because ED may be a
            sign of other medical problems such as hypertension, diabetes, or
            vascular disease, telling your primary care physician may lead to
            early treatment of problems while they may still be reversible, or
            before they become more harmful to your wellbeing . Your
            telemedicine provider and your primary care provider must be kept
            informed of any changes to your medication regimen. Your safety is
            paramount. You must disclose your health history and any
            health-related changes so that your provider can address your needs
            to help safeguard your wellbeing.
            <br />
            <br />
            Sildenafil and tadalafil are prescription medications commonly used
            to help treat erectile dysfunction (ED) and should only be used
            after you’ve been diagnosed with ED. Take them as directed. Do not
            these medications if you’re not healthy enough for sexual activity.
            Sildenafil is the same medication that’s in Viagra, which has been
            approved for ED treatment. Tadalafil is the same medication in
            Cialis which can be prescribed as needed, or on a daily maintenance
            dosing schedule.
          </p>
          <div className={styles.line}></div>
          <h3>SIDE EFFECTS, CONTRAINDICATIONS, AND WARNINGS:</h3>
          <p className={styles.grayArea}>SIDE EFFECTS (MILD):</p>
          <p>
            These are rather common, however most only last as long as the
            medication is still in the system. That means it's a shorter
            duration for sildenafil, but longer for tadalafil.
          </p>
          <table>
            <thead>
              <tr>
                <td scope="col" className={styles.th}>
                  Symptom
                </td>
                <td scope="col" className={styles.th}>
                  Frequency
                </td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">Headache</th>
                <td>16-28% vs 7% for placebo</td>
              </tr>
              <tr>
                <th scope="row">Upset stomach</th>
                <td>10-29% vs 2% for placebo</td>
              </tr>
              <tr>
                <th scope="row">Flushing</th>
                <td>10-29% vs 2% for placebo</td>
              </tr>
              <tr>
                <th scope="row">Stuffy nose</th>
                <td>4% vs 2% for placebo</td>
              </tr>
              <tr>
                <th scope="row">Dizziness.</th>
                <td>3-4% vs 2% for placebo</td>
              </tr>
              <tr>
                <th scope="row">Muscle aches</th>
                <td>3-4% vs 2% for placebo</td>
              </tr>
              <tr>
                <th scope="row">Dyspepsia (‘reflux’)</th>
                <td>3-17% vs 2% for placebo</td>
              </tr>
            </tbody>
          </table>
          <p className={styles.grayArea}>
            SIDE EFFECTS (Severe, VERY uncommon)
          </p>
          <p className={styles.effects}>
            Erections that last several hours. Go to an emergency room if you
            have an erection that lasts more than 4 hours.
          </p>
          <p className={styles.effects}>
            Decreased eyesight or loss of sight in one or both eyes.
          </p>
          <p className={styles.effects}>Sudden decrease or loss of hearing.</p>
          <p className={styles.effects}>
            Heart attack, stroke, irregular heartbeats, and death. Most of these
            happened in people who already had heart problems.
          </p>
          <p className={styles.effects}>Seizures</p>
          <p className={styles.effects}>Low blood pressure causing dizziness</p>
          <p className={styles.effects}>Allergic reaction</p>
          <p className={styles.effects}>Stevens-Johnson syndrome</p>
          <p className={styles.effects}>Anemia</p>
          <p>
            If any of these <b>SEVERE</b> side effects occur,{" "}
            <b>seek medical care immediately.</b>
          </p>
          <p className={styles.grayArea}>WARNINGS</p>
          <p>
            Sildenafil does not protect against sexually transmitted diseases.
            If there is any concern about STDs, wear a condom to protect
            yourself and your sexual partner. You should inform your partner if
            you have any sexually transmitted infections and get their consent
            to engage in sexual activity.
            <br />
            <br />
            This medication is a phosphodiesterase inhibitor, which is generally
            safe. There are, however, rare and serious potential side effects.
            Phosphodiesterase inhibitors were first developed to treat blood
            pressure and in some cases, they can result in dangerously low blood
            pressure, especially if taken with other medications that lower
            blood pressure, like nitrites and nitrates. These medications should
            never be taken simultaneously with sildenafil. Additionally,
            recreational use of nitrates/nitrites (such as “poppers”) should
            never be taken in conjunction with sildenafil. There is always a
            chance that the medication will not work, regardless of whether a
            patient is healthy and compliant with taking the medication.
            Phosphodiesterases have been shown to be ineffective in about 15% of
            patients.
            <br />
            <br />
            Do not use this in combination with any illegal drugs. Taking with
            alcohol may make the medication less effective and increase the
            chances of side effects such as headache or flushing. Patients with
            Pulmonary Veno-Occlusive Disease (PVOD) should not use this
            medication.
            <br />
            <br />A potential side effect is an erection that can last longer
            than desired (priapism). In this case, a sometimes painful
            engorgement of the penis can persist and damage the vessels and
            tissue of the penis. On occasion, the damage can be permanent. It is
            important that you immediately seek treatment at an emergency room
            if such an erection lasts for longer than four hours, even if it’s
            not painful. Patients with penile structural abnormalities or
            conditions which may predispose them to priapism should also be
            cautious.
            <br />
            <br />
            Changes to vision can be another potential side effect from use of
            the medication. It has been documented that some users see a blue
            tint in their vision. In rare cases, blindness can occur which can
            be permanent. Patients with a history of non-arteritic anterior
            ischemic optic neuropathy (NAION) should be cautious. It is
            important that you immediately seek treatment or visit an urgent
            care/emergency room if you are experiencing vision issues.
            <br />
            <br />
            For patients whose kidney/liver function is reduced, it is
            recommended to not exceed the maximum single dose of 25 mg
            sildenafil within 48 hour period. The same applies to patients who
            are taking erythromycin, itraconazole, ketoconazole, saquinavir, and
            ritonavir (common in HIV medications and Paxlovid, a treatment for
            COVID-19).
            <br />
            <br />
            Nerve damage from surgery, trauma or radiation therapy can interfere
            with the body’s ability to get and maintain an erection. Men with a
            history of prostate cancer surgery may have great issues with
            maintaining an erection.
            <br />
            <br />
            On occasion, sexual activity comes with cardiac risk. Patients must
            communicate with their provider about any history of chest pain,
            heart disease, high/low blood pressure, irregular heartbeats,
            coronary artery disease, aortic stenosis, idiopathic hypertrophic
            subaortic stenosis, coronary ischemia, heart attacks, strokes, heart
            defects or heart failure. It is also recommended that doses of
            sildenafil &gt; 25 mg not be given to patients within 4 hours of
            taking an alpha-blocker medication. If you are not sure about the
            medications which you are taking and if they are safe, please make
            sure to ask your doctor, telemedicine provider, or pharmacist.
            <br />
            <br /> Pilots and air traffic controllers should not take sildenafil
            within six hours of aviation related duties, due to the potential
            vision changes that can happen when taking this medication for ED.
            Additionally, pilots and air traffic controllers should not take
            Cialis (tadalafil) within 36 hours of aviation related duties.
          </p>
          <div className={styles.line}></div>
          <h3>HOW TO TAKE THIS MEDICATION:</h3>
          <p>
            Do not take the medicine on an empty stomach and avoid fatty foods
            for at least two hours before taking the pill. Fat interferes with
            its absorption. Avoid alcohol while taking this medication.
            Grapefruit juice can possibly affect the absorption of this
            medication since it increases the blood level after an initial delay
            in absorption.
            <br />
            <br /> For your first experience with this medication, it is
            recommended to take it alone (without engaging in sexual acts) in
            case there are any side effects.
            <br />
            <br />
            This medication can aid the patient in getting an erection but it
            does not always persist during intercourse. On occasion, erections
            may persist but it may be challenging to orgasm. Some patients may
            experience premature ejaculation, especially after periods of
            abstaining from sexual activity. It is best to communicate with your
            provider and sexual partner to address any issues.
            <br />
            <br />
            Do not take more than the prescribed dose within a 24 hour-period.
            <br />
            <br /> If you are taking an alpha blocker (usually for high blood
            pressure or enlarged prostate) be sure that you are stable on the
            alpha blocker before lowering the dose of the alpha blocker. If you
            are already taking this medication and begin the use of an alpha
            blocker, start on the lowest dose of the alpha blocker. Do not take
            this medication within four hours of taking alpha blockers.
            <br />
            <br /> It is not recommended to take different types of ED
            medications simultaneously. They should not be taken within 48 hours
            of each other. Do not take sildenafil or tadalafil together, or
            within 48 hours of one another.
          </p>
          <div className={styles.line}></div>
          <h3>UNDERSTANDING THE SCIENCE BEHIND ERECTIONS:</h3>
          <p>
            Penile tissue releases Nitric Oxide (NO) when the brain processes
            erotic stimulation. This release of NO increases a chemical known as
            Guanosine MonoPhosphate (cyclic-GMP) which causes the relaxation of
            the muscles in the penis, in a process known as tumescence. The
            swelling causes the veins in the penis to collapse, which restricts
            blood from leaving the penis. This is what causes a persistent
            erection. Eventually, the penis will become flaccid again as the
            blood is released, in a process known as detumescence. It is caused
            by chemicals known as phosphodiesterases which break down the
            cyclic-GMP in a reversal of how the erection started. Sildenafil is
            a phosphodiesterase inhibitor, meaning it blocks your body’s
            phosphodiesterases which inhibits the breakdown of cyclic-GMP, so
            the blood stays in the penis for longer, resulting in a longer
            erection.
            <br />
            <br />
            Certain phosphodiesterase inhibitors can react differently in the
            body. This medication can be effective in as little as one hour and
            will be out of the bloodstream in up to eight hours, whereas
            tadalafil may not take effect for two hours and can work for up to
            36 hours.
          </p>
          <div className={styles.line}></div>
          <h3>OTHER WAYS TO TREAT ED:</h3>
          <p>
            There are other ways to treat ED. Below are some options that should
            be carefully discussed with your provider before treatment.
            <br />
            <br /> A vacuum-tube device is an option. It creates a vacuum
            suction around the penis, which forces blood to fill the penis and
            results in an erection. A ring device that is placed at the base of
            the shaft can also restrict blood from leaving the penis, but should
            be removed 30 minutes later so there is no risk of tissue damage.
            Discuss with a provider before use.
            <br />
            <br />
            Alprostadil is another option that can be used as a penile
            suppository or as a penile injection. Alprostadil acts as a
            vasodilator, which causes blood to fill the penis. Discuss with a
            provider before use.
            <br />
            <br /> Surgery is another option. Surgical options include the
            placement of a rod, inflatable implant or a semi-rigid implant.
            Discuss these options with your provider.
            <br />
            <br /> Healthy lifestyle choices and alterations are also encouraged
            for improvement in a patient’s ability to get and maintain an
            erection. Healthy eating, exercise, adequate sleep, managing stress
            and limited alcohol/nicotine consumption are some of the ways to
            improve overall sexual performance. Alcohol acts as a depressant in
            the nervous system which can inhibit messaging between the brain and
            the body. Smoking can damage blood vessels and impede the body’s
            ability to achieve an erection. <br />
            <br /> Contact your provider with any and all concerns. If you are
            experiencing a medical emergency, seek treatment immediately.
          </p>
          <div className={styles.line}></div>
          <h3>COMMUNICATION WITH YOUR PCP:</h3>
          <p>
            Please see your PCP and notify them that you have started taking
            medications for erectile dysfunction.We recommend that you visit
            your PCP on an annual basis. ED may be a early sign of the following
            conditions: heart disease, atherosclerosis, high cholesterol, high
            blood pressure, diabetes, obesity, metabolic syndrome, Parkinson’s
            disease, multiple sclerosis, sleep apnea, prostate disease, other
            genitourinary diseases, low testosterone, psychological conditions,
            certain medications, smoking, drug and alcohol use.Please remember
            to let us know of any changes in your health. If you have any
            anatomic problems or urology surgeries that could impact erectile
            dysfunction or if there is any change to your cardiovascular health
            please always let myself and your primary doctor know as this may
            impact the treatment recommendations for your ED.
            <br />
            <br /> If you do not have a PCP, please click on the following link:
            <Link href="https://www.google.com/search?q=primary+care+doctor+near+me">
              https://www.google.com/search?q=primary+care+doctor+near+me
            </Link>
          </p>
          <div className={styles.line}></div>
          <h3>DRUG INTERACTIONS:</h3>
          <p>
            While your prescribing physician has reviewed the medications you
            have reported, it is important for you to be aware of the many drug
            interactions which can occur with phosphodiesterases. The following
            list is long, but not complete. Please review the PDR (Physicians
            Desk Reference) for a complete list.
          </p>
          <ul>
            <li>
              Alfuzosin (Uroxatral) (Treats High Blood Pressure or Enlarged
              Prostate)
            </li>
            <li>Aliskiren (Tekturna, Rasilez) (Treats High Blood Pressure)</li>
            <li>
              Alpha-blockers (e.g., Cardura, Coreg Flomax, Hytrin, Minipress,
              Oravase, Rapaflo, Regitine,Trandate) (Treats High Blood Pressure
              or Enlarged Prostate)
            </li>
            <li>
              Ambrisentan (Letairis) (Treats PAH–High Blood Pressure in the
              Arteries of the Lungs)
            </li>
            <li>Amlodipine (Norvasc) (Treats High Blood Pressure)</li>
            <li>Amprenavir (Agenerase) (Treats HIV)</li>
            <li>
              Amyl Nitrite (Amyl nitrite Systemic, Poppers, Rush) (Recreational
              Drug)
            </li>
            <li>Aprepitant (Emend) (Treats Nausea)</li>
            <li>Atazanavir (Reyataz) (Treats HIV)</li>
            <li>Atropine (Isopto Atropine) (Treats Eye Conditions)</li>
            <li>
              Boceprevir (Pegasys, Pegintron) (Treats PAH and Hepatitis C)
            </li>
            <li>
              Butyl Nitrate (Poppers, Rush, Liquid Gold) (It is a recreational
              drug)
            </li>
            <li>Brigatinib (Alunbrig) (Cancer)</li>
            <li>Capecitabine (Xeloda) (Cancer)</li>
            <li>Cariprazine (Vraylar) (Psychiatric Disorders)</li>
            <li>Ceritinib (Zykadia) (Cancer)</li>
            <li>Cimetidine (Tagamet) (Stomach Ulcers)</li>
            <li>Ciprofloxacin (Proquin, Cipro) (Antibiotic)</li>
            <li>Clarithromycin (Biaxin) (Antibiotic)</li>
            <li>Clopidogrel (Plavix) (Blood Thinner)</li>
            <li>Cobicistat (Stribild, Tybost) (Treats HIV)</li>
            <li>Conivaptan (Vaprisol) (Treats Low Sodium in the blood)</li>
            <li>Crizotinib (Xalkori) (Cancer)</li>
            <li>Darunavir (Prezista) (Treats HIV)</li>
            <li>
              Dasabuvir (Viekira XR, Viekira Pak–contains Ritonavir*) (Treats
              Hepatitis C)
            </li>
            <li>Delavirdine (Treats HIV)</li>
            <li>Dihydroergotamine (Migranal) (Treats Migraines)</li>
            <li>
              Diltiazem (e.g., Cartia, Cardizem, Dilacor XR, Tiazac,) (Treats
              High Blood Pressure)
            </li>
            <li>
              Doxazosin (Cardura, Carduran) (Treats High Blood Pressure or
              Enlarged Prostate)
            </li>
            <li>Dronedarone (Multaq) (Irregular Heartbeats)</li>
            <li>
              Duloxetine (Cymbalta) (Treats Depression and certain nerve pain
              disorders)
            </li>
            <li>
              Erythromycin (Erythrocin, Ery-Tab, E-Mycin, Eryc) (Antibiotic)
            </li>
            <li>Fluconazole (Diflucan) (Treats Fungal and Yeast Infections)</li>
            <li>
              Fluoxetine (e.g., Prozac, Sarafem) (Treats Psychiatric disorders
              like depression)
            </li>
            <li>
              Fluvoxamine (Faverin, Fevarin, Floxyfral, Dumyrox, Luvox) (Treats
              OCD)
            </li>
            <li>Fosamprenavir (Lexiva) (Treats HIV)</li>
            <li>Grapefruit juice</li>
            <li>Idelalisib (Zydelig) (Treats Cancer–Leukemia)</li>
            <li>Imatinib (Gleevec) (Treats Cancer–Leukemia)</li>
            <li>Indinavir (Crixivan) (Treats HIV)</li>
            <li>Isavuconazonium (Cresemba) (Treats Fungal Infections)</li>
            <li>Isocarboxazid (Marplan) (Treats Depression)</li>
            <li>
              Isosorbide Dinitrate or Monohydrate (Isordil Titradose,
              Dilatrate-SR, Imdur, Imdur ER, Ismo, Monoket, IsoDitrate) (Treats
              Heart Disease and Chest Pain)
            </li>
            <li>Itraconazole (Sporanox, Onmel) (Treats Fungus and Yeast)</li>
            <li>Ivacaftor (Kalydeco) (Treats Cystic Fibrosis)</li>
            <li>
              Ketoconazole (Nizoral, Extina, Ketodan Kit, Kuric, Nizoral A-D,
              Xolegel) (Treats Fungal Infections)
            </li>
            <li>
              Lopinavir; Ritonavir (Kaletra) (Contains Ritonavir and Treats HIV)
            </li>
            <li>Lorcaserin (Belviq) (Weight Control)</li>
            <li>Lurasidone (Latuda) (Treats Depression)</li>
            <li>
              Mifepristone, RU-486 (Korlym, Mifeprex) (Treats Cushing’s Syndrome
              and Ends Pregnancy)
            </li>
            <li>Mitotane (Lysodren) (Treats Cancer and Cushing‘s Syndrome)</li>
            <li>
              Monoamine oxidase inhibitors (e.g., Azilect, Marplan, Nardil,
              Parnate) (Treats Depression)
            </li>
            <li>Nebivolol (Bystolic) (Treats High Blood Pressure)</li>
            <li>Nelfinavir (Viracept) (Treats HIV)</li>
            <li>
              Nesiritide (Natrecor) (Treats Heart Failure but is an IV drug)
            </li>
            <li>Netupitant (Akynzeo) (Prevents Nausea and Vomiting)</li>
            <li>
              Nifedipine (Procardia, Nifedical XL, Adalat, Procardia XL) (Heart
              Disease among others)
            </li>
            <li>Nilotinib (Tasigna) (Treats Cancer–Leukemia)</li>
            <li>
              Nitrates (Isordil Titradose, Dilatrate-SR, Imdur, Imdur ER, Ismo,
              Monoket, IsoDitrate) (Treats Heart Disease and Chest Pain)
            </li>
            <li>
              Nitroglycerin (Nitro-bid, Nitrocot SA Capsule, Nitro-dur,
              Nitrostat, Nitrodisc, Nitrek transdermal, Minitran, Nitrol
              ointment, Transderm-Nitro, Nitro-Time, Nitrotab, NitroMist,
              Nitro-Par, Nitrolingual, Nitroquick, Transderm-Nitro, Nitrogard,
              Nitroglyn, Nitrong) (Treats Chest Pain and Heart Conditions)
            </li>
            <li>
              Nitroprusside (Nipride RTU, Nitropress) (Heart Failure and High
              Blood Pressure)
            </li>
            <li>
              Ombitasvir; Paritaprevir; Ritonavir (Technivie, Viekira Pak)
              (Treat Hepatitis C)
            </li>
            <li>
              Phenoxybenzamine (Dibenzyline) (Treat High Blood Pressure and
              Pheochromocytoma)
            </li>
            <li>
              Phentolamine (Regitine, Oraverse) (Erectile Dysfunction, High
              Blood Pressure)
            </li>
            <li>Phenylephrine (e.g.,Sudafed) (Decongestant)</li>
            <li>Posaconazole (Noxafil) (Treats Fungal Infections)</li>
            <li>
              Prazosin (e.g., Minipress, Vasoflex, Lentopres, Hypovase) (Treats
              High Blood Pressure, PTSD, and Anxiety)
            </li>
            <li>Ribociclib (Kisqali) (Treats Cancer)</li>
            <li>
              Riociguat (Adempas) (Treats High Blood Pressure in the Arteries of
              the Lung)
            </li>
            <li>
              Ritonavir (Norvir) (Also found in Technivie and Viekira Pak)
              (Treats HIV and Hepatitis C)
            </li>
            <li>
              Sapropterin (Kuvan) (Treats a disorder that causes amino acid
              buildup in the brain)
            </li>
            <li>Saquinavir (Invirase, Fortovase) (Treats HIV)</li>
            <li>Silodosin (Rapaflo) (Treats an Enlarged Prostate)</li>
            <li>
              Tacrolimus (Prograft, Advagraf XL, Protopic, Hecoria) (Treats
              Organ Transplants)
            </li>
            <li>Tamsulosin (Flomax) (Treats an Enlarged Prostate)</li>
            <li>Telaprevir (Incivek, Incivo) (Treats Hepatitis C)</li>
            <li>Telithromycin (Ketek, Ketek Pak) (Antibiotic)</li>
            <li>
              Telotristat Ethyl (Xermelo) (Treats diarrhea in cancer patients)
            </li>
            <li>Terazosin (Hytrin) (Treats High Blood Pressure)</li>
            <li>Tipranavir (Aptivus) (Treats HIV)</li>
            <li>
              Verapamil (Calan, Isoptin) (Treats High Blood Pressure, Angina,
              Irregular Heart Beats)
            </li>
            <li>Vigabatrin (Sabril) (Treats Seizure Disorders)</li>

            <li>Voriconazole (Vfend) (Treats Fungal Infection)</li>
          </ul>
        </Container>
      </main>
    </div>
  );
}
